# SPDX-License-Identifier: 0BSD

"""Lifecycle helper: get_config_dict."""

from __future__ import annotations

from typing import Any

# ruff: noqa: F821


def build_config_dict(app: Any, context=None):
    mc = __import__("meshchatx.meshchat", fromlist=["*"])
    g = mc.__dict__
    for _k in (
        "LXMF",
        "RNS",
        "AsyncUtils",
        "InterfaceEditor",
        "InterfaceConfigParser",
        "web",
        "json",
        "logger",
        "logging",
        "os",
        "sys",
        "time",
        "asyncio",
        "traceback",
        "copy",
        "shutil",
        "tempfile",
        "threading",
        "base64",
        "configparser",
        "sqlite3",
        "secrets",
        "re",
        "io",
        "contextlib",
        "datetime",
        "platform",
        "cast",
        "UTC",
    ):
        if _k in g:
            globals()[_k] = g[_k]
    ctx = context or app.current_context
    if not ctx:
        return {}
    return {
        "display_name": ctx.config.display_name.get(),
        "identity_hash": ctx.identity.hash.hex(),
        "identity_public_key": ctx.identity.get_public_key().hex(),
        "lxmf_address_hash": ctx.local_lxmf_destination.hexhash,
        "telephone_address_hash": ctx.telephone_manager.telephone.destination.hexhash
        if ctx.telephone_manager.telephone
        else None,
        "is_transport_enabled": (
            app.reticulum.transport_enabled()
            if hasattr(app, "reticulum") and app.reticulum
            else False
        ),
        "auto_announce_enabled": ctx.config.auto_announce_enabled.get(),
        "auto_announce_interval_seconds": ctx.config.auto_announce_interval_seconds.get(),
        "last_announced_at": ctx.config.last_announced_at.get(),
        "theme": ctx.config.theme.get(),
        "theme_preset": ctx.config.theme_preset.get(),
        "accent_color": ctx.config.accent_color.get(),
        "custom_canvas_color": ctx.config.custom_canvas_color.get(),
        "custom_surface_color": ctx.config.custom_surface_color.get(),
        "language": ctx.config.language.get(),
        "auto_resend_failed_messages_when_announce_received": ctx.config.auto_resend_failed_messages_when_announce_received.get(),
        "allow_auto_resending_failed_messages_with_attachments": ctx.config.allow_auto_resending_failed_messages_with_attachments.get(),
        "auto_send_failed_messages_to_propagation_node": ctx.config.auto_send_failed_messages_to_propagation_node.get(),
        "delivery_helptips_enabled": ctx.config.delivery_helptips_enabled.get(),
        "show_suggested_community_interfaces": ctx.config.show_suggested_community_interfaces.get(),
        "lxmf_delivery_transfer_limit_in_bytes": ctx.config.lxmf_delivery_transfer_limit_in_bytes.get(),
        "lxmf_propagation_transfer_limit_in_bytes": ctx.config.lxmf_propagation_transfer_limit_in_bytes.get(),
        "lxmf_propagation_sync_limit_in_bytes": ctx.config.lxmf_propagation_sync_limit_in_bytes.get(),
        "lxmf_local_propagation_node_enabled": ctx.config.lxmf_local_propagation_node_enabled.get(),
        "lxmf_local_propagation_node_address_hash": ctx.message_router.propagation_destination.hexhash,
        "lxmf_preferred_propagation_node_destination_hash": ctx.config.lxmf_preferred_propagation_node_destination_hash.get(),
        "lxmf_preferred_propagation_node_auto_select": ctx.config.lxmf_preferred_propagation_node_auto_select.get(),
        "lxmf_preferred_propagation_node_auto_sync_interval_seconds": ctx.config.lxmf_preferred_propagation_node_auto_sync_interval_seconds.get(),
        "lxmf_preferred_propagation_node_last_synced_at": ctx.config.lxmf_preferred_propagation_node_last_synced_at.get(),
        "lxmf_user_icon_name": ctx.config.lxmf_user_icon_name.get(),
        "lxmf_user_icon_foreground_colour": ctx.config.lxmf_user_icon_foreground_colour.get(),
        "lxmf_user_icon_background_colour": ctx.config.lxmf_user_icon_background_colour.get(),
        "lxmf_inbound_stamp_cost": ctx.config.lxmf_inbound_stamp_cost.get(),
        "lxmf_propagation_node_stamp_cost": ctx.config.lxmf_propagation_node_stamp_cost.get(),
        "lxmf_propagation_sequential_validation": ctx.config.lxmf_propagation_sequential_validation.get(),
        "lxmf_propagation_static_peers_bypass_sequential": ctx.config.lxmf_propagation_static_peers_bypass_sequential.get(),
        "lxmf_propagation_max_inbound_syncs": ctx.config.lxmf_propagation_max_inbound_syncs.get(),
        "lxmf_flood_protection_enabled": ctx.config.lxmf_flood_protection_enabled.get(),
        "lxmf_flood_threshold_per_minute": ctx.config.lxmf_flood_threshold_per_minute.get(),
        "lxmf_flood_max_stamp_cost": ctx.config.lxmf_flood_max_stamp_cost.get(),
        "lxmf_flood_cooldown_seconds": ctx.config.lxmf_flood_cooldown_seconds.get(),
        "page_archiver_enabled": ctx.config.page_archiver_enabled.get(),
        "page_archiver_max_versions": ctx.config.page_archiver_max_versions.get(),
        "archives_max_storage_gb": ctx.config.archives_max_storage_gb.get(),
        "backup_max_count": ctx.config.backup_max_count.get(),
        "crawler_enabled": ctx.config.crawler_enabled.get(),
        "crawler_max_retries": ctx.config.crawler_max_retries.get(),
        "crawler_retry_delay_seconds": ctx.config.crawler_retry_delay_seconds.get(),
        "crawler_max_concurrent": ctx.config.crawler_max_concurrent.get(),
        "crawler_max_hops": ctx.config.crawler_max_hops.get(),
        "crawler_max_rtt_ms": ctx.config.crawler_max_rtt_ms.get(),
        "crawler_max_depth": ctx.config.crawler_max_depth.get(),
        "crawler_max_pages_per_node": ctx.config.crawler_max_pages_per_node.get(),
        "crawler_requests_per_day_per_node": ctx.config.crawler_requests_per_day_per_node.get(),
        "crawler_refresh_days": ctx.config.crawler_refresh_days.get(),
        "auth_enabled": app.auth_enabled,
        "privacy_mode_enabled": ctx.config.privacy_mode_enabled.get(),
        "multi_session_warning_enabled": ctx.config.multi_session_warning_enabled.get(),
        "voicemail_enabled": ctx.config.voicemail_enabled.get(),
        "voicemail_greeting": ctx.config.voicemail_greeting.get(),
        "voicemail_auto_answer_delay_seconds": ctx.config.voicemail_auto_answer_delay_seconds.get(),
        "voicemail_max_recording_seconds": ctx.config.voicemail_max_recording_seconds.get(),
        "voicemail_tts_speed": ctx.config.voicemail_tts_speed.get(),
        "voicemail_tts_pitch": ctx.config.voicemail_tts_pitch.get(),
        "voicemail_tts_voice": ctx.config.voicemail_tts_voice.get(),
        "voicemail_tts_word_gap": ctx.config.voicemail_tts_word_gap.get(),
        "custom_ringtone_enabled": ctx.config.custom_ringtone_enabled.get(),
        "ringtone_filename": ctx.config.ringtone_filename.get(),
        "ringtone_preferred_id": ctx.config.ringtone_preferred_id.get(),
        "ringtone_volume": ctx.config.ringtone_volume.get(),
        "notification_sound_enabled": ctx.config.notification_sound_enabled.get(),
        "notification_sound_preferred_id": ctx.config.notification_sound_preferred_id.get(),
        "notification_sound_volume": ctx.config.notification_sound_volume.get(),
        "map_offline_enabled": ctx.config.map_offline_enabled.get(),
        "map_mbtiles_dir": ctx.config.map_mbtiles_dir.get(),
        "map_tile_cache_enabled": ctx.config.map_tile_cache_enabled.get(),
        "map_default_lat": ctx.config.map_default_lat.get(),
        "map_default_lon": ctx.config.map_default_lon.get(),
        "map_default_zoom": ctx.config.map_default_zoom.get(),
        "map_tile_server_url": ctx.config.map_tile_server_url.get(),
        "map_nominatim_api_url": ctx.config.map_nominatim_api_url.get(),
        "map_overlay_max_bytes": ctx.config.map_overlay_max_bytes.get(),
        "map_overlay_max_features": ctx.config.map_overlay_max_features.get(),
        "map_overlay_max_kmz_uncompressed_bytes": ctx.config.map_overlay_max_kmz_uncompressed_bytes.get(),
        "map_data_max_bytes": ctx.config.map_data_max_bytes.get(),
        "map_data_announce_enabled": ctx.config.map_data_announce_enabled.get(),
        "map_data_announce_interval": ctx.config.map_data_announce_interval.get(),
        "map_data_display_name": ctx.config.map_data_display_name.get(),
        "map_overlay_max_sources": ctx.config.map_overlay_max_sources.get(),
        "map_overlay_max_concurrent_jobs": ctx.config.map_overlay_max_concurrent_jobs.get(),
        "map_overlay_path_timeout_seconds": ctx.config.map_overlay_path_timeout_seconds.get(),
        "map_overlay_transfer_timeout_seconds": ctx.config.map_overlay_transfer_timeout_seconds.get(),
        "map_overlay_job_timeout_seconds": ctx.config.map_overlay_job_timeout_seconds.get(),
        "map_overlay_max_retries": ctx.config.map_overlay_max_retries.get(),
        "map_overlay_retry_delay_seconds": ctx.config.map_overlay_retry_delay_seconds.get(),
        "do_not_disturb_enabled": ctx.config.do_not_disturb_enabled.get(),
        "telephone_enabled": ctx.config.telephone_enabled.get(),
        "telephone_allow_calls_from_contacts_only": ctx.config.telephone_allow_calls_from_contacts_only.get(),
        "telephone_announce_enabled": ctx.config.telephone_announce_enabled.get(),
        "telephone_audio_profile_id": ctx.config.telephone_audio_profile_id.get(),
        "telephone_call_mode_id": ctx.config.telephone_call_mode_id.get(),
        "telephone_web_audio_enabled": ctx.config.telephone_web_audio_enabled.get(),
        "telephone_web_audio_allow_fallback": ctx.config.telephone_web_audio_allow_fallback.get(),
        "call_recording_enabled": ctx.config.call_recording_enabled.get(),
        "block_attachments_from_strangers": ctx.config.block_attachments_from_strangers.get(),
        "block_all_from_strangers": ctx.config.block_all_from_strangers.get(),
        "show_unknown_contact_banner": ctx.config.show_unknown_contact_banner.get(),
        "warn_on_stranger_links": ctx.config.warn_on_stranger_links.get(),
        "banished_effect_enabled": ctx.config.banished_effect_enabled.get(),
        "banished_text": ctx.config.banished_text.get(),
        "banished_color": ctx.config.banished_color.get(),
        "message_font_size": ctx.config.message_font_size.get(),
        "messages_sidebar_position": ctx.config.messages_sidebar_position.get(),
        "app_sidebar_layout": ctx.config.app_sidebar_layout.get(),
        "messages_multi_pane_enabled": ctx.config.messages_multi_pane_enabled.get(),
        "nomad_tabs_enabled": ctx.config.nomad_tabs_enabled.get(),
        "rrc_enabled": ctx.config.rrc_enabled.get(),
        "rrc_unread_badges_enabled": ctx.config.rrc_unread_badges_enabled.get(),
        "message_icon_size": ctx.config.message_icon_size.get(),
        "ui_transparency": ctx.config.ui_transparency.get(),
        "ui_glass_enabled": ctx.config.ui_glass_enabled.get(),
        "live_transport_mode": ctx.config.live_transport_mode.get(),
        "webtransport_sidecar_enabled": ctx.config.webtransport_sidecar_enabled.get(),
        "message_outbound_bubble_color": ctx.config.message_outbound_bubble_color.get(),
        "message_inbound_bubble_color": ctx.config.message_inbound_bubble_color.get(),
        "message_failed_bubble_color": ctx.config.message_failed_bubble_color.get(),
        "message_waiting_bubble_color": ctx.config.message_waiting_bubble_color.get(),
        "translator_argos_enabled": ctx.config.translator_argos_enabled.get(),
        "translator_libretranslate_enabled": ctx.config.translator_libretranslate_enabled.get(),
        "libretranslate_url": ctx.config.libretranslate_url.get(),
        "libretranslate_api_key": ctx.config.libretranslate_api_key.get(),
        "desktop_open_calls_in_separate_window": ctx.config.desktop_open_calls_in_separate_window.get(),
        "desktop_hardware_acceleration_enabled": ctx.config.desktop_hardware_acceleration_enabled.get(),
        "blackhole_integration_enabled": ctx.config.blackhole_integration_enabled.get(),
        "announce_store_lxmf_delivery": ctx.config.announce_store_lxmf_delivery.get(),
        "announce_store_lxst_telephony": ctx.config.announce_store_lxst_telephony.get(),
        "announce_store_nomadnetwork_node": ctx.config.announce_store_nomadnetwork_node.get(),
        "announce_store_lxmf_propagation": ctx.config.announce_store_lxmf_propagation.get(),
        "announce_store_map_data": ctx.config.announce_store_map_data.get(),
        "announce_max_stored_lxmf_delivery": ctx.config.announce_max_stored_lxmf_delivery.get(),
        "announce_max_stored_nomadnetwork_node": ctx.config.announce_max_stored_nomadnetwork_node.get(),
        "announce_max_stored_lxmf_propagation": ctx.config.announce_max_stored_lxmf_propagation.get(),
        "announce_max_stored_map_data": ctx.config.announce_max_stored_map_data.get(),
        "announce_fetch_limit_lxmf_delivery": ctx.config.announce_fetch_limit_lxmf_delivery.get(),
        "announce_fetch_limit_nomadnetwork_node": ctx.config.announce_fetch_limit_nomadnetwork_node.get(),
        "announce_fetch_limit_lxmf_propagation": ctx.config.announce_fetch_limit_lxmf_propagation.get(),
        "announce_fetch_limit_map_data": ctx.config.announce_fetch_limit_map_data.get(),
        "announce_search_max_fetch": ctx.config.announce_search_max_fetch.get(),
        "discovered_interfaces_max_return": ctx.config.discovered_interfaces_max_return.get(),
        "csp_extra_connect_src": ctx.config.csp_extra_connect_src.get(),
        "csp_extra_img_src": ctx.config.csp_extra_img_src.get(),
        "csp_extra_frame_src": ctx.config.csp_extra_frame_src.get(),
        "csp_extra_script_src": ctx.config.csp_extra_script_src.get(),
        "csp_extra_style_src": ctx.config.csp_extra_style_src.get(),
        "telephone_tone_generator_enabled": ctx.config.telephone_tone_generator_enabled.get(),
        "telephone_tone_generator_volume": ctx.config.telephone_tone_generator_volume.get(),
        "location_source": ctx.config.location_source.get(),
        "location_manual_lat": ctx.config.location_manual_lat.get(),
        "location_manual_lon": ctx.config.location_manual_lon.get(),
        "location_manual_alt": ctx.config.location_manual_alt.get(),
        "telemetry_enabled": ctx.config.telemetry_enabled.get(),
        "nomad_render_markdown_enabled": ctx.config.nomad_render_markdown_enabled.get(),
        "nomad_render_html_enabled": ctx.config.nomad_render_html_enabled.get(),
        "nomad_render_plaintext_enabled": ctx.config.nomad_render_plaintext_enabled.get(),
        "nomad_micron_wasm_enabled": ctx.config.nomad_micron_wasm_enabled.get(),
        "nomad_micron_default_engine": ctx.config.nomad_micron_default_engine.get()
        or "js",
        "nomad_default_page_path": ctx.config.nomad_default_page_path.get(),
        "local_message_auto_delete_enabled": ctx.config.local_message_auto_delete_enabled.get(),
        "local_message_auto_delete_value": ctx.config.local_message_auto_delete_value.get(),
        "local_message_auto_delete_unit": ctx.config.local_message_auto_delete_unit.get()
        or "days",
        "message_blocklist_enabled": ctx.config.message_blocklist_enabled.get(),
    }


# try and get a name for the provided identity hash
