// SPDX-License-Identifier: 0BSD

export function createDefaultConfig(): Record<string, any> {
    return {
        identity_hash: "",
        lxmf_address_hash: "",
        theme: "dark",
        theme_preset: "default",
        accent_color: null,
        custom_canvas_color: null,
        custom_surface_color: null,
        is_transport_enabled: false,
        auto_resend_failed_messages_when_announce_received: null,
        allow_auto_resending_failed_messages_with_attachments: null,
        auto_send_failed_messages_to_propagation_node: null,
        delivery_helptips_enabled: true,
        show_suggested_community_interfaces: null,
        lxmf_delivery_transfer_limit_in_bytes: 1000 * 1000 * 10,
        lxmf_propagation_transfer_limit_in_bytes: 1000 * 256,
        lxmf_propagation_sync_limit_in_bytes: 1000 * 10240,
        lxmf_local_propagation_node_enabled: null,
        lxmf_propagation_sequential_validation: true,
        lxmf_propagation_static_peers_bypass_sequential: true,
        lxmf_propagation_max_inbound_syncs: 3,
        lxmf_preferred_propagation_node_destination_hash: null,
        lxmf_preferred_propagation_node_auto_select: null,
        archives_max_storage_gb: 1,
        backup_max_count: 5,
        block_attachments_from_strangers: true,
        block_all_from_strangers: false,
        show_unknown_contact_banner: true,
        warn_on_stranger_links: true,
        banished_effect_enabled: true,
        banished_text: "BANISHED",
        banished_color: "#dc2626",
        blackhole_integration_enabled: true,
        announce_store_lxmf_delivery: true,
        announce_store_lxst_telephony: true,
        announce_store_nomadnetwork_node: true,
        announce_store_lxmf_propagation: true,
        announce_store_map_data: false,
        announce_max_stored_lxmf_delivery: 1000,
        announce_max_stored_nomadnetwork_node: 1000,
        announce_max_stored_lxmf_propagation: 1000,
        announce_max_stored_map_data: 1000,
        announce_fetch_limit_lxmf_delivery: 500,
        announce_fetch_limit_nomadnetwork_node: 500,
        announce_fetch_limit_lxmf_propagation: 500,
        announce_fetch_limit_map_data: 500,
        announce_search_max_fetch: 2000,
        discovered_interfaces_max_return: 500,
        message_font_size: 14,
        messages_sidebar_position: "left",
        messages_multi_pane_enabled: true,
        nomad_tabs_enabled: true,
        rrc_enabled: true,
        rrc_unread_badges_enabled: true,
        message_icon_size: 28,
        ui_transparency: 0,
        ui_glass_enabled: true,
        live_transport_mode: "auto",
        webtransport_sidecar_enabled: false,
        message_outbound_bubble_color: "#4f46e5",
        message_inbound_bubble_color: null,
        message_failed_bubble_color: "#ef4444",
        message_waiting_bubble_color: "#e5e7eb",
        telephone_tone_generator_enabled: true,
        telephone_tone_generator_volume: 50,
        location_source: "disabled",
        location_manual_lat: "0.0",
        location_manual_lon: "0.0",
        location_manual_alt: "0.0",
        map_default_lat: "0.0",
        map_default_lon: "0.0",
        map_default_zoom: 2,
        map_tile_server_url: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
        map_nominatim_api_url: "https://nominatim.openstreetmap.org",
        map_offline_enabled: true,
        map_tile_cache_enabled: true,
        map_coordinate_format: "wgs84",
        map_overlay_max_bytes: 8 * 1024 * 1024,
        map_overlay_max_features: 50000,
        map_overlay_max_kmz_uncompressed_bytes: 16 * 1024 * 1024,
        map_overlay_max_sources: 64,
        map_overlay_max_concurrent_jobs: 2,
        map_overlay_path_timeout_seconds: 30,
        map_overlay_transfer_timeout_seconds: 120,
        map_overlay_job_timeout_seconds: 300,
        map_overlay_max_retries: 3,
        map_overlay_retry_delay_seconds: 2,
        telemetry_enabled: false,
        gitea_base_url: "",
        csp_extra_connect_src: "",
        csp_extra_img_src: "",
        csp_extra_frame_src: "",
        csp_extra_script_src: "",
        csp_extra_style_src: "",
        nomad_render_markdown_enabled: true,
        nomad_render_html_enabled: true,
        nomad_render_plaintext_enabled: true,
        nomad_micron_wasm_enabled: true,
        nomad_micron_default_engine: "js",
        nomad_default_page_path: "/page/index.mu",
        local_message_auto_delete_enabled: false,
        local_message_auto_delete_value: 30,
        local_message_auto_delete_unit: "days",
        privacy_mode_enabled: false,
        multi_session_warning_enabled: true,
    };
}

export function createDefaultServerSecurity(): Record<string, any> {
    return {
        listen_host: null,
        listen_port: null,
        https_enabled: true,
        is_loopback_bind: true,
        web_ui_ip_allowlist: "",
        auth_enabled: false,
        landlock_requested: false,
        landlock_active: false,
        landlock_kernel_supported: false,
        landlock_auto_enabled: false,
        landlock_disabled_by_env: false,
        appcontainer_requested: false,
        appcontainer_active: false,
        appcontainer_supported: false,
        appcontainer_auto_enabled: false,
        appcontainer_disabled_by_env: false,
        seccomp_requested: false,
        seccomp_active: false,
        seccomp_kernel_supported: false,
        seccomp_auto_enabled: false,
        seccomp_disabled_by_env: false,
    };
}

export function createDefaultReticulumInstance(): Record<string, any> {
    return {
        share_instance: false,
        shared_instance_type: "",
        instance_name: "",
        respond_to_probes: false,
        enable_remote_management: false,
        remote_management_allowed: [],
        local_hops_delta: false,
        rpc_config_snippet: "",
        is_connected_to_shared_instance: false,
    };
}
