// SPDX-License-Identifier: 0BSD

export interface CommandEntry {
    id: string;
    title: string;
    description: string;
    icon: string;
    type: "navigation" | "action";
    route?: { name: string };
    action?: "sync" | "compose" | "show-tutorial" | "show-changelog" | string;
    pluginId?: string | null;
}

export const CORE_COMMAND_ENTRIES: CommandEntry[] = [
    {
        id: "nav-messages",
        title: "nav_messages",
        description: "nav_messages_desc",
        icon: "message-text",
        type: "navigation",
        route: { name: "messages" },
    },
    {
        id: "nav-call",
        title: "nav_call",
        description: "nav_call_desc",
        icon: "phone",
        type: "navigation",
        route: { name: "call" },
    },
    {
        id: "nav-nomad",
        title: "nav_nomad",
        description: "nav_nomad_desc",
        icon: "earth",
        type: "navigation",
        route: { name: "nomadnetwork" },
    },
    {
        id: "nav-map",
        title: "nav_map",
        description: "nav_map_desc",
        icon: "map",
        type: "navigation",
        route: { name: "map" },
    },
    {
        id: "nav-paper",
        title: "nav_paper",
        description: "nav_paper_desc",
        icon: "qrcode",
        type: "navigation",
        route: { name: "paper-message" },
    },
    {
        id: "nav-settings",
        title: "nav_settings",
        description: "nav_settings_desc",
        icon: "cog",
        type: "navigation",
        route: { name: "settings" },
    },
    {
        id: "nav-ping",
        title: "nav_ping",
        description: "nav_ping_desc",
        icon: "radar",
        type: "navigation",
        route: { name: "ping" },
    },
    {
        id: "nav-rnprobe",
        title: "nav_rnprobe",
        description: "nav_rnprobe_desc",
        icon: "radar",
        type: "navigation",
        route: { name: "rnprobe" },
    },
    {
        id: "nav-rncp",
        title: "nav_rncp",
        description: "nav_rncp_desc",
        icon: "swap-horizontal",
        type: "navigation",
        route: { name: "rncp" },
    },
    {
        id: "nav-rns-filesync",
        title: "nav_rns_filesync",
        description: "nav_rns_filesync_desc",
        icon: "folder-sync",
        type: "navigation",
        route: { name: "rns-filesync" },
    },
    {
        id: "nav-rnsh",
        title: "nav_rnsh",
        description: "nav_rnsh_desc",
        icon: "console-network-outline",
        type: "navigation",
        route: { name: "rnsh" },
    },
    {
        id: "nav-rnx",
        title: "nav_rnx",
        description: "nav_rnx_desc",
        icon: "console",
        type: "navigation",
        route: { name: "rnx" },
    },
    {
        id: "nav-rnstatus",
        title: "nav_rnstatus",
        description: "nav_rnstatus_desc",
        icon: "chart-line",
        type: "navigation",
        route: { name: "rnstatus" },
    },
    {
        id: "nav-rnpath",
        title: "nav_rnpath",
        description: "nav_rnpath_desc",
        icon: "route",
        type: "navigation",
        route: { name: "rnpath" },
    },
    {
        id: "nav-rnpath-trace",
        title: "nav_rnpath_trace",
        description: "nav_rnpath_trace_desc",
        icon: "map-marker-path",
        type: "navigation",
        route: { name: "rnpath-trace" },
    },
    {
        id: "nav-translator",
        title: "nav_translator",
        description: "nav_translator_desc",
        icon: "translate",
        type: "navigation",
        route: { name: "translator" },
    },
    {
        id: "nav-forwarder",
        title: "nav_forwarder",
        description: "nav_forwarder_desc",
        icon: "email-send-outline",
        type: "navigation",
        route: { name: "forwarder" },
    },
    {
        id: "nav-documentation",
        title: "nav_documentation",
        description: "nav_documentation_desc",
        icon: "book-open-variant",
        type: "navigation",
        route: { name: "documentation" },
    },
    {
        id: "nav-repository-server",
        title: "nav_repository_server",
        description: "nav_repository_server_desc",
        icon: "package-variant",
        type: "navigation",
        route: { name: "repository-server" },
    },
    {
        id: "nav-micron-editor",
        title: "nav_micron_editor",
        description: "nav_micron_editor_desc",
        icon: "code-tags",
        type: "navigation",
        route: { name: "micron-editor" },
    },
    {
        id: "nav-reticulum-config-editor",
        title: "nav_reticulum_config_editor",
        description: "nav_reticulum_config_editor_desc",
        icon: "file-cog",
        type: "navigation",
        route: { name: "reticulum-config-editor" },
    },
    {
        id: "nav-rnode-flasher",
        title: "nav_rnode_flasher",
        description: "nav_rnode_flasher_desc",
        icon: "flash",
        type: "navigation",
        route: { name: "rnode-flasher" },
    },
    {
        id: "nav-debug-logs",
        title: "nav_debug_logs",
        description: "nav_debug_logs_desc",
        icon: "console",
        type: "navigation",
        route: { name: "debug-logs" },
    },
    {
        id: "action-sync",
        title: "action_sync",
        description: "action_sync_desc",
        icon: "refresh",
        type: "action",
        action: "sync",
    },
    {
        id: "action-compose",
        title: "action_compose",
        description: "action_compose_desc",
        icon: "email-plus",
        type: "action",
        action: "compose",
    },
    {
        id: "action-getting-started",
        title: "action_getting_started",
        description: "action_getting_started_desc",
        icon: "help-circle",
        type: "action",
        action: "show-tutorial",
    },
    {
        id: "action-changelog",
        title: "action_changelog",
        description: "action_changelog_desc",
        icon: "history",
        type: "action",
        action: "show-changelog",
    },
];
