// SPDX-License-Identifier: 0BSD

/** @type {Record<string, string[]>} */
export const CORE_SETTINGS_SECTION_KEYWORDS = {
    telephony: ["Telephony", "Telephone", "LXST", "Enable Telephone", "voice", "calling", "call", "mesh network"],
    strangerProtection: [
        "Security",
        "app.stranger_protection",
        "app.stranger_protection_description",
        "app.block_stranger_attachments",
        "app.block_stranger_attachments_description",
        "app.block_all_from_strangers",
        "app.block_all_from_strangers_description",
        "app.show_unknown_contact_banner",
        "app.show_unknown_contact_banner_description",
        "app.warn_on_stranger_links",
        "app.warn_on_stranger_links_description",
        "stranger",
        "attachments",
        "trust",
        "block",
        "banner",
        "unknown",
        "contact",
        "links",
    ],
    visualiser: [
        "Visualiser",
        "Network Visualiser",
        "visualiser",
        "graph",
        "mesh",
        "visualiser.show_disabled_interfaces",
        "visualiser.show_discovered_interfaces",
        "offline",
        "discovered",
    ],
    banishment: [
        "Privacy",
        "app.privacy_eyebrow",
        "app.banishment",
        "app.banishment_description",
        "app.banished_effect_enabled",
        "app.banished_effect_description",
        "app.banished_text_label",
        "app.banished_text_description",
        "app.banished_color_label",
        "app.banished_color_description",
    ],
    stickers: [
        "Stickers",
        "stickers.settings_title",
        "stickers.settings_description",
        "stickers.export",
        "stickers.import",
        "stickers.replace_duplicates",
        "sticker_packs.section_title",
        "sticker_packs.create",
        "sticker_packs.install_from_file",
        "sticker_packs.open_editor",
    ],
    gifs: [
        "GIFs",
        "gifs.settings_title",
        "gifs.settings_description",
        "gifs.export",
        "gifs.import",
        "gifs.replace_duplicates",
    ],
    maintenance: [
        "Maintenance",
        "maintenance.title",
        "maintenance.description",
        "maintenance.clear_messages",
        "maintenance.clear_messages_desc",
        "maintenance.clear_announces",
        "maintenance.clear_announces_desc",
        "maintenance.clear_nomadnet_favs",
        "maintenance.clear_nomadnet_favs_desc",
        "maintenance.clear_lxmf_icons",
        "maintenance.clear_lxmf_icons_desc",
        "maintenance.clear_stickers",
        "maintenance.clear_stickers_desc",
        "maintenance.clear_gifs",
        "maintenance.clear_gifs_desc",
        "maintenance.clear_archives",
        "maintenance.clear_archives_desc",
        "maintenance.clear_reticulum_docs",
        "maintenance.clear_reticulum_docs_desc",
        "maintenance.clear_path_table",
        "maintenance.clear_path_table_desc",
        "maintenance.export_messages",
        "maintenance.export_messages_desc",
        "maintenance.import_messages",
        "maintenance.import_messages_desc",
        "maintenance.export_nomadnet_favourites",
        "maintenance.import_nomadnet_favourites",
        "Automatic Backup Limit",
        "Export Folders",
        "Import Folders",
    ],
    selftest: [
        "Self-Test",
        "System Self-Test",
        "diagnostic",
        "checks",
        "selftest.title",
        "selftest.description",
        "bot",
        "bots",
        "identity",
        "imports",
        "storage lock",
        "subprocess",
        "run-module",
        "lxmf",
    ],
    desktop: [
        "Desktop",
        "App Behaviour",
        "app.desktop_open_calls_in_separate_window",
        "app.desktop_open_calls_in_separate_window_description",
        "app.desktop_hardware_acceleration_enabled",
        "app.desktop_hardware_acceleration_enabled_description",
        "app.desktop_tray_enabled",
        "app.desktop_tray_enabled_description",
        "app.desktop_close_behavior",
        "app.desktop_close_behavior_description",
        "app.desktop_close_behavior_ask",
        "app.desktop_close_behavior_quit",
        "app.desktop_close_behavior_background",
        "app.desktop_close_behavior_background_no_tray",
        "tray",
        "close",
        "quit",
        "taskbar",
    ],
    android: [
        "Android",
        "APK",
        "Bluetooth",
        "Nearby Share",
        "settings.share_apk_heading",
        "settings.share_apk_desc",
        "settings.share_apk",
        "settings.share_apk_short_hint",
    ],
    archiver: ["Browsing", "Page Archiver", "archiver", "archive", "versions", "storage", "flush"],
    nomadRenderer: [
        "NomadNet",
        "NomadNet browser renderer",
        "micron-parser-go",
        "WASM",
        "SHASUMS",
        "micron wasm update",
        "browser",
        "renderer",
        "markdown",
        "HTML",
        "plaintext",
        "micron-parser",
        "=index.mu",
        "=index.html",
        "default page",
        "settings.nomad_micron_default_engine_title",
        "settings.nomad_micron_default_engine_desc",
    ],
    crawler: ["Discovery", "Smart Crawler", "crawler", "crawl", "retries", "delay", "concurrent"],
    csp: [
        "Security",
        "app.csp_settings",
        "app.csp_description",
        "app.csp_extra_connect_src",
        "app.csp_extra_img_src",
        "app.csp_extra_frame_src",
        "app.csp_extra_script_src",
        "app.csp_extra_style_src",
        "CSP",
        "Content Security Policy",
    ],
    appearance: [
        "Personalise",
        "app.appearance",
        "app.appearance_description",
        "app.theme",
        "app.light_theme",
        "app.dark_theme",
        "app.messages_sidebar_position",
        "app.messages_sidebar_position_left",
        "app.messages_sidebar_position_right",
        "app.messages_multi_pane_enabled",
        "app.messages_multi_pane_enabled_description",
        "app.nomad_tabs_enabled",
        "app.nomad_tabs_enabled_description",
        "app.ui_transparency",
        "app.ui_glass_enabled",
        "app.reset_appearance_defaults",
        "Message Font Size",
        "Icon Size",
        "Message Bubbles",
        "Waiting Color",
        "app.live_preview",
        "app.realtime",
    ],
    language: [
        "i18n",
        "app.language",
        "app.select_language",
        "English",
        "Deutsch",
        "Italiano",
        "Русский",
        "Nederlands",
        "Français",
        "Español",
        "中文",
    ],
    networkSecurity: [
        "RNS Security",
        "Network Security",
        "app.blackhole_integration_enabled",
        "app.blackhole_integration_description",
        "app.announce_limits",
        "app.announce_store_heading",
        "app.announce_store_lxmf",
        "app.announce_store_lxst",
        "app.announce_store_nomad",
        "app.announce_store_prop",
        "app.announce_limit_lxmf",
        "app.announce_limit_nomadnet",
        "app.announce_limit_prop",
        "app.announce_max_stored_heading",
        "app.announce_fetch_limit_heading",
        "app.announce_search_max_fetch",
        "app.discovered_interfaces_max_return",
    ],
    transport: [
        "Reticulum",
        "app.transport_mode",
        "app.transport_description",
        "app.enable_transport_mode",
        "app.transport_toggle_description",
        "app.share_reticulum_instance",
        "app.share_reticulum_instance_description",
        "app.respond_to_probes",
        "app.respond_to_probes_description",
        "app.enable_remote_management",
        "app.enable_remote_management_description",
        "app.shared_instance_type",
        "app.instance_name",
        "app.copy_rpc_config",
        "app.rpc_config",
        "share instance",
        "rpc",
        "hops",
        "obfuscate",
    ],
    interfaces: ["Adapters", "app.interfaces", "app.show_community_interfaces", "app.community_interfaces_description"],
    blocked: ["Privacy", "Banished", "Manage Banished users and nodes"],
    auth: ["Security", "Authentication", "password", "Protect your instance with a password"],
    webExposure: [
        "Security",
        "Network exposure",
        "app.web_exposure_title",
        "app.web_exposure_description",
        "app.web_listen_address",
        "app.web_ui_ip_allowlist",
        "app.web_exposure_warning_title",
        "app.landlock_status",
        "allowlist",
        "firewall",
        "VPN",
        "bind",
        "localhost",
    ],
    infrastructure: ["Infrastructure", "Sources & Mirroring", "gitea", "documentation", "download", "urls"],
    messages: [
        "app.lxmf_settings_eyebrow",
        "app.messages",
        "app.messages_description",
        "app.auto_resend_title",
        "app.auto_resend_description",
        "app.retry_attachments_title",
        "app.retry_attachments_description",
        "app.auto_fallback_title",
        "app.auto_fallback_description",
        "app.inbound_stamp_cost",
        "app.inbound_stamp_description",
        "app.inbound_stamps_required_title",
        "app.inbound_stamps_required_description",
        "app.flood_protection",
        "app.flood_protection_description",
        "app.flood_protection_enabled",
        "app.flood_threshold",
        "app.flood_max_stamp_cost",
        "app.flood_cooldown",
    ],
    notificationSounds: [
        "app.notifications",
        "app.notification_sound_settings",
        "app.notification_sound_settings_description",
        "app.enable_notification_sound",
        "app.enable_notification_sound_description",
        "app.notification_sound_volume",
        "app.notification_sound_default",
        "app.notification_sounds",
        "app.notification_sound_upload",
    ],
    propagation: [
        "LXMF",
        "app.incoming_message_size",
        "app.incoming_message_size_description",
        "app.propagation_nodes",
        "app.propagation_nodes_description",
        "app.browse_nodes",
        "app.run_local_node",
        "app.run_local_node_description",
        "app.auto_select_node",
        "app.auto_select_node_description",
        "app.auto_select_using_label",
        "app.auto_select_pending",
        "app.preferred_propagation_node",
        "app.auto_sync_interval",
        "app.propagation_stamp_cost",
        "app.propagation_stamp_description",
    ],
    location: [
        "app.location",
        "app.location_manage_desc",
        "app.location_source",
        "app.map_settings_title",
        "app.map_settings_desc",
        "app.map_overlay_limits_heading",
        "app.map_overlay_max_bytes",
        "app.map_overlay_max_features",
        "Map",
        "Location",
        "GPS",
        "overlay",
        "KMZ",
        "KML",
        "GeoJSON",
        "manual",
        "latitude",
        "longitude",
        "altitude",
    ],
    privacyData: [
        "app.privacy_data_title",
        "app.privacy_data_description",
        "app.privacy_mode_enabled",
        "app.privacy_mode_description",
        "app.obfuscate_hops",
        "app.obfuscate_hops_description",
        "app.local_message_auto_delete_title",
        "app.local_message_auto_delete_description",
        "app.local_message_auto_delete_age",
        "app.telemetry_enabled",
        "app.telemetry_description",
        "app.telemetry_trusted_peers",
        "ephemeral",
        "retention",
        "Privacy",
    ],
    shortcuts: ["Keyboard Shortcuts", "actions", "workflow"],
    plugins: [
        "Plugins",
        "plugins.settings.title",
        "plugins.settings.description",
        "extensions",
        "install",
        "enable",
        "disable",
    ],
};
