// Scenario orchestrator: drives N coordinated agents from one markdown spec.
//
// A scenario file is prose (shared brief every agent reads) plus one
// fenced ```agentic JSON block carrying the machine contract:
//
//   ```agentic
//   {
//     "pair": true,
//     "agents": {
//       "alice": { "url_key": "alice", "browser": "chromium" },
//       "bob":   { "url_key": "bob",   "browser": "firefox"  }
//     },
//     "markers": [
//       { "id": "alice.ready", "owner": "alice", "timeout_s": 60 },
//       { "id": "bob.reply",   "owner": "bob", "after": ["alice.sent"], "timeout_s": 300 }
//     ]
//   }
//   ```
//
// Each agent gets the full scenario text plus a generated footer naming
// its role, its marker files, and the markers it must wait on. Agents
// write markers as out/<scenario>/<marker>.done containing PASS or
// FAIL:<reason>. The orchestrator supervises markers with dependency
// and timeout tracking, writes a report, exits non-zero on failure.
//
// Usage:
//   node tests/agentic/orchestrate.cjs scenarios/<name>.md [--model X]
//        [--agent-model alice=X]

const fs = require("fs");
const path = require("path");
const { spawn, spawnSync } = require("child_process");

const HERE = __dirname;

function parseScenario(file) {
    const text = fs.readFileSync(file, "utf8");
    const m = text.match(/```agentic\s*\n([\s\S]*?)```/);
    if (!m) {
        throw new Error(`${file}: missing fenced \`\`\`agentic JSON block`);
    }
    const spec = JSON.parse(m[1]);
    if (!spec.agents || !spec.markers) {
        throw new Error(`${file}: agentic block needs "agents" and "markers"`);
    }
    const name = path.basename(file).replace(/\.md$/, "");
    return { name, spec, brief: text };
}

function markerPath(dir, id) {
    return path.join(dir, `${id}.done`);
}

function markerState(dir, id) {
    const p = markerPath(dir, id);
    if (!fs.existsSync(p)) {
        return null;
    }
    const body = fs.readFileSync(p, "utf8").trim();
    return body.toUpperCase().startsWith("PASS") ? "pass" : "fail";
}

function agentFooter(name, agentName, agent, spec, markerDir) {
    const mine = spec.markers.filter((x) => x.owner === agentName);
    const waits = spec.markers.filter((x) => x.owner !== agentName);
    const lines = [
        "",
        "---",
        "",
        `# Runtime contract (generated by orchestrate.cjs)`,
        "",
        `You are agent "${agentName}" in scenario "${name}".`,
        `Your app URL: ${agent.url || "see pairshare/pair.json"}.`,
        `Your browser tools live under the "${agent.tools}" MCP namespace.`,
        `Read out/pairshare/pair.json for peer addresses if present.`,
        "",
        `Marker directory: ${markerDir}`,
        "",
        "You MUST write each of your markers when done. Each marker file is",
        `one line: PASS or PASS note or FAIL: reason`,
        "",
        "Your markers:",
        ...mine.map((m) => `- ${m.id}`),
        "",
        "Markers owned by other agents you may wait on (poll by reading):",
        ...waits.map((m) => `- ${m.id}`),
        "",
        "If a marker you need is missing, wait ~5s and check again. Give up",
        "and FAIL your step after the timeout implied by the scenario.",
    ];
    return lines.join("\n");
}

async function main() {
    const scenarioFile = process.argv[2];
    if (!scenarioFile || process.argv.includes("--help")) {
        console.log("usage: node orchestrate.cjs scenarios/<name>.md [--model M] [--agent-model a=M]");
        process.exit(2);
    }
    const argv = process.argv.slice(3);
    const flagVal = (flag) => {
        const i = argv.indexOf(flag);
        return i >= 0 ? argv[i + 1] : null;
    };
    const defaultModel = flagVal("--model") || "opencode/deepseek-v4.1-flash";
    const agentModels = {};
    argv.forEach((a, i) => {
        if (a === "--agent-model" && argv[i + 1]) {
            const [n, m] = argv[i + 1].split("=");
            if (n && m) {
                agentModels[n] = m;
            }
        }
    });

    const { name, spec, brief } = parseScenario(scenarioFile);
    const markerDir = path.join(HERE, "out", "scenarios", name);
    fs.mkdirSync(markerDir, { recursive: true });
    for (const f of fs.readdirSync(markerDir)) {
        fs.rmSync(path.join(markerDir, f));
    }

    if (spec.pair) {
        console.log("[orch] bringing up pair...");
        const r = spawnSync("bash", [path.join(HERE, "pair-up.sh")], { stdio: "inherit" });
        if (r.status !== 0) {
            console.error("[orch] pair-up failed");
            process.exit(1);
        }
    }

    const procs = {};
    for (const [agentName, agent] of Object.entries(spec.agents)) {
        const model = agentModels[agentName] || agent.model || defaultModel;
        const agentCfg = agent.agent || `pair-${agent.browser || "chromium"}`;
        const prompt = brief + agentFooter(name, agentName, agent, spec, markerDir);
        const logPath = path.join(markerDir, `agent-${agentName}.log`);
        const log = fs.createWriteStream(logPath);
        const child = spawn(
            "opencode",
            ["run", "--model", model, "--agent", agentCfg, prompt],
            { cwd: HERE, stdio: ["ignore", log, log] },
        );
        procs[agentName] = { child, logPath, model };
        console.log(`[orch] ${agentName}: pid ${child.pid} model ${model} -> ${logPath}`);
    }

    // Supervise markers with dependencies and timeouts.
    const deadline = new Map();
    const pending = new Map(spec.markers.map((m) => [m.id, m]));
    const done = new Map();
    const failures = [];
    const started = Date.now();
    const globalTimeoutMs = (spec.global_timeout_s || 1800) * 1000;

    while (pending.size && Date.now() - started < globalTimeoutMs) {
        let progressed = false;
        for (const [id, m] of pending) {
            const state = markerState(markerDir, id);
            if (state) {
                done.set(id, state);
                pending.delete(id);
                progressed = true;
                console.log(`[orch] marker ${id}: ${state}`);
                if (state === "fail") {
                    failures.push(id);
                }
                continue;
            }
            const deps = m.after || [];
            const depsReady = deps.every((d) => done.get(d) === "pass");
            if (!depsReady) {
                continue;
            }
            if (!deadline.has(id)) {
                deadline.set(id, Date.now() + (m.timeout_s || 300) * 1000);
            }
            if (Date.now() > deadline.get(id)) {
                pending.delete(id);
                done.set(id, "timeout");
                failures.push(id);
                console.log(`[orch] marker ${id}: TIMEOUT`);
            }
        }
        if (!progressed) {
            await new Promise((r) => setTimeout(r, 2000));
        }
    }

    for (const [id] of pending) {
        done.set(id, "timeout");
        failures.push(id);
    }

    // Give agents a moment to flush their logs, then stop them.
    await new Promise((r) => setTimeout(r, 3000));
    for (const { child } of Object.values(procs)) {
        if (child.exitCode === null) {
            child.kill("SIGTERM");
        }
    }

    const report = {
        scenario: name,
        started: new Date(started).toISOString(),
        markers: Object.fromEntries(done),
        failures,
        agents: Object.fromEntries(
            Object.entries(procs).map(([n, p]) => [n, { model: p.model, log: p.logPath }]),
        ),
    };
    const reportPath = path.join(markerDir, "report.json");
    fs.writeFileSync(reportPath, JSON.stringify(report, null, 2));

    const passCount = [...done.values()].filter((s) => s === "pass").length;
    console.log(`\n[orch] ${name}: ${passCount}/${done.size} markers passed; report ${reportPath}`);
    process.exit(failures.length ? 1 : 0);
}

main().catch((e) => {
    console.error(e);
    process.exit(2);
});
