"""Extracted mixin for ReticulumMeshChat::apply_2.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""


class Apply2Mixin:
    def _apply_lxmf_sieve_banish_rule(
        self,
        peer_hash: str,
        context=None,
        *,
        message_title=None,
        message_content=None,
    ):
        m = self._evaluate_lxmf_sieve_for_peer(
            peer_hash,
            context=context,
            message_title=message_title,
            message_content=message_content,
        )
        if not m or m.get("action") != "banish":
            return
        self.banish_lxmf_peer(peer_hash, context=context)
