"""Extracted mixin for ReticulumMeshChat::apply.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

from meshchatx.src.backend.async_utils import AsyncUtils
from meshchatx.src.backend.lxmf_sieve import (
    first_matching_lxmf_sieve_rule,
    normalize_lxmf_sieve_filters,
    parse_lxmf_sieve_filters_json,
)
from meshchatx.src.backend.meshchat_utils import (
    cancel_inbound_deliveries,
    convert_db_favourite_to_dict,
    convert_propagation_node_state_to_string,
    hex_identifier_to_bytes,
    interval_action_due,
    message_fields_have_attachments,
    normalize_hex_identifier,
    normalize_identity_storage_hash,
    parse_bool_query_param,
    parse_lxmf_display_name,
    parse_lxmf_propagation_node_app_data,
    parse_lxmf_stamp_cost,
    parse_nomadnetwork_node_display_name,
    propagation_sync_idle_like,
    propagation_sync_is_terminal,
)
from meshchatx.src.backend.message_blocklist import (
    first_matching_blocklist_entry,
    normalize_message_blocklist,
    parse_import_document,
    parse_message_blocklist_json,
)
import RNS
import asyncio
import contextlib
import json
import logging
import time
from ..meshchat_shared import logger

class ApplyMixin:
    # automatically syncs propagation nodes based on user config
    async def announce_sync_propagation_nodes(self, session_id, context=None):
        ctx = context or self.current_context
        if not ctx:
            return

        router = ctx.message_router
        sync_start_time = None
        while self.running and ctx.running and ctx.session_id == session_id:
            auto_sync_interval_seconds = ctx.config.lxmf_preferred_propagation_node_auto_sync_interval_seconds.get()
            last_synced_at = (
                ctx.config.lxmf_preferred_propagation_node_last_synced_at.get()
            )
            outbound_node = router.get_outbound_propagation_node() if router else None
            should_sync = outbound_node is not None and interval_action_due(
                auto_sync_interval_seconds is not None
                and auto_sync_interval_seconds > 0,
                last_synced_at,
                auto_sync_interval_seconds,
                time.time(),
            )

            if should_sync and sync_start_time is None:
                started = await self.sync_propagation_nodes(context=ctx)
                if started:
                    sync_start_time = time.monotonic()

            if sync_start_time is not None and router:
                state = router.propagation_transfer_state
                elapsed = time.monotonic() - sync_start_time
                path_stuck = (
                    state == router.PR_PATH_REQUESTED
                    and outbound_node is not None
                    and not RNS.Transport.has_path(outbound_node)
                    and elapsed > 45.0
                )
                if propagation_sync_is_terminal(state):
                    if state != router.PR_IDLE:
                        self.stop_propagation_node_sync(context=ctx)
                        with contextlib.suppress(Exception):
                            router.propagation_transfer_state = router.PR_IDLE
                            router.propagation_transfer_progress = 0.0
                    ctx.config.lxmf_preferred_propagation_node_last_synced_at.set(
                        int(time.time()),
                    )
                    await self.send_config_to_websocket_clients(context=ctx)
                    sync_start_time = None
                elif path_stuck or elapsed > 120:
                    self.stop_propagation_node_sync(context=ctx)
                    with contextlib.suppress(Exception):
                        router.propagation_transfer_state = router.PR_IDLE
                    ctx.config.lxmf_preferred_propagation_node_last_synced_at.set(
                        int(time.time()),
                    )
                    await self.send_config_to_websocket_clients(context=ctx)
                    sync_start_time = None

            # wait 1 second before next loop
            await asyncio.sleep(1)

    async def crawler_loop(self, session_id, context=None):
        ctx = context or self.current_context
        if not ctx:
            return

        while self.running and ctx.running and ctx.session_id == session_id:
            try:
                if ctx.config.crawler_enabled.get():
                    crawler = getattr(ctx, "crawler_manager", None)
                    homepage = (
                        ctx.config.nomad_default_page_path.get() or "/page/index.mu"
                    )
                    # Sweep announced nodes. Policy decides whether to queue.
                    known_nodes = ctx.database.announces.get_announces(
                        aspect="nomadnetwork.node",
                    )
                    for node in known_nodes:
                        if (
                            not self.running
                            or not ctx.running
                            or ctx.session_id != session_id
                        ):
                            break
                        dest = node["destination_hash"]
                        if crawler:
                            crawler.queue_if_allowed(
                                dest,
                                homepage,
                                depth=0,
                                announced_recently=True,
                            )
                        else:
                            self.queue_crawler_task(dest, homepage, context=ctx)

                    max_retries = ctx.config.crawler_max_retries.get()
                    max_concurrent = max(
                        1,
                        min(2, int(ctx.config.crawler_max_concurrent.get() or 1)),
                    )
                    if crawler:
                        tasks = crawler.select_next_tasks(
                            max_retries=max_retries,
                            max_concurrent=max_concurrent,
                        )
                    else:
                        tasks = ctx.database.misc.get_pending_or_failed_crawl_tasks(
                            max_retries=max_retries,
                            max_concurrent=max_concurrent,
                        )

                    if tasks and self.running and ctx.running:
                        await asyncio.gather(
                            *[
                                self.process_crawler_task(task, context=ctx)
                                for task in tasks
                            ],
                        )

            except Exception as e:
                print(f"Error in crawler loop for {ctx.identity_hash}: {e}")

            # Wait 60s between policy sweeps (was 30s). Less mesh load.
            for _ in range(60):
                if not self.running or not ctx.running or ctx.session_id != session_id:
                    return
                await asyncio.sleep(1)

    # uses the provided destination hash as the active propagation node
    def set_active_propagation_node(self, destination_hash: str | None, context=None):
        ctx = context or self.current_context
        if not ctx or not ctx.message_router:
            return

        # Always cancel an in-flight sync before switching nodes so we don't
        # orphan a transfer or leave the router in a stuck state.
        self.stop_propagation_node_sync(context=ctx)

        # set outbound propagation node
        if destination_hash is not None and destination_hash != "":
            try:
                destination_hash_bytes = bytes.fromhex(destination_hash)
                ctx.message_router.set_outbound_propagation_node(
                    destination_hash_bytes,
                )
                with contextlib.suppress(Exception):
                    RNS.Transport.request_path(destination_hash_bytes)
            except Exception:
                # failed to set propagation node, clear it to ensure we don't use an old one by mistake
                self.remove_active_propagation_node(context=ctx)

        # stop using propagation node
        else:
            self.remove_active_propagation_node(context=ctx)

    # stops the in progress propagation node sync
    def stop_propagation_node_sync(self, context=None):
        ctx = context or self.current_context
        if not ctx or not ctx.message_router:
            return
        router = ctx.message_router
        with contextlib.suppress(Exception):
            router.cancel_propagation_node_requests()
        # cancel_propagation_node_requests resets via acknowledge_sync_completion,
        # but a blocked RNS.Identity.recall can leave the router in an active state.
        with contextlib.suppress(Exception):
            active_states = {
                router.PR_PATH_REQUESTED,
                router.PR_LINK_ESTABLISHING,
                router.PR_LINK_ESTABLISHED,
                router.PR_REQUEST_SENT,
                router.PR_RECEIVING,
                router.PR_RESPONSE_RECEIVED,
            }
            if router.propagation_transfer_state in active_states:
                router.propagation_transfer_state = router.PR_IDLE
                router.propagation_transfer_progress = 0.0

    async def _request_propagation_node_messages(self, context=None):
        ctx = context or self.current_context
        if not ctx or not ctx.message_router:
            return

        router = ctx.message_router

        def _request():
            try:
                router.request_messages_from_propagation_node(ctx.identity)
            except (EOFError, BrokenPipeError, ConnectionResetError, OSError):
                with contextlib.suppress(Exception):
                    router.propagation_transfer_state = router.PR_IDLE
                    router.propagation_transfer_progress = 0.0
            except Exception:
                logging.getLogger("meshchatx").exception(
                    "Propagation node message request failed",
                )

        await asyncio.to_thread(_request)
        await self.send_config_to_websocket_clients(context=ctx)

    # stops and removes the active propagation node
    def remove_active_propagation_node(self, context=None):
        ctx = context or self.current_context
        if not ctx:
            return
        self.stop_propagation_node_sync(context=ctx)
        if ctx.message_router:
            ctx.message_router.outbound_propagation_node = None
            # Force the transfer state back to idle so nothing remains stuck
            # after the outbound node is removed.
            with contextlib.suppress(Exception):
                ctx.message_router.propagation_transfer_state = (
                    ctx.message_router.PR_IDLE
                )

    # broadcasts config to all websocket clients
    async def send_config_to_websocket_clients(self, context=None, changed_keys=None):
        ctx = context or self.current_context
        if not ctx:
            return
        config_dict = self.get_config_dict(context=ctx)
        await self.websocket_broadcast(
            {
                "type": "config",
                "config": config_dict,
            },
        )
        keys = changed_keys
        if keys is None:
            keys = list(config_dict.keys()) if isinstance(config_dict, dict) else []
        await self.websocket_broadcast(
            {
                "type": "config.changed",
                "keys": keys,
            },
        )

    def _related_hashes_for_contact_lookup(self, source_hash: str, context=None):
        """Collect identity/LXMF/LXST hashes that may identify the same peer."""
        ctx = context or self.current_context
        related = []
        seen = set()

        def add(value):
            if not value or not isinstance(value, str):
                return
            normalized = normalize_hex_identifier(value)
            if not normalized or normalized in seen:
                return
            seen.add(normalized)
            related.append(normalized)

        add(source_hash)
        if not ctx or not ctx.database:
            return related

        try:
            announce = ctx.database.announces.get_announce_by_hash(source_hash)
            if announce:
                add(announce.get("identity_hash"))
                add(announce.get("destination_hash"))
                identity_hash = announce.get("identity_hash")
                if identity_hash:
                    for other in ctx.database.announces.get_announces_by_identity_hash(
                        identity_hash,
                    ):
                        add(other.get("destination_hash"))
                        add(other.get("identity_hash"))
            else:
                for other in ctx.database.announces.get_announces_by_identity_hash(
                    source_hash,
                ):
                    add(other.get("destination_hash"))
                    add(other.get("identity_hash"))
        except Exception:
            pass

        try:
            lxmf_hash = self.get_lxmf_destination_hash_for_identity_hash(source_hash)
            add(lxmf_hash)
        except Exception:
            pass

        try:
            lxst_hash = self.get_lxst_telephony_hash_for_identity_hash(source_hash)
            add(lxst_hash)
        except Exception:
            pass

        return related

    def _resolve_contact_for_hash(self, source_hash: str, context=None):
        """Resolve a contact for an identity or destination hash.

        Contacts are often saved with an LXMF destination hash as
        remote_identity_hash (from chat UI). Incoming calls provide the
        caller's identity hash. Bridge those forms via announces and derived
        destination hashes so contacts-only call policy works.
        """
        ctx = context or self.current_context
        if not ctx or not ctx.database or not source_hash:
            return None
        try:
            related = self._related_hashes_for_contact_lookup(source_hash, context=ctx)
            return ctx.database.contacts.get_contact_by_identity_hash(
                source_hash,
                related_hashes=related,
            )
        except Exception:
            return None

    def _collect_blocked_identity_hashes(self, context=None) -> list:
        """Identity-hash bytes for LXST set_blocked from the block list."""
        ctx = context or self.current_context
        out = []
        seen = set()
        if not ctx or not ctx.database:
            return out
        try:
            blocked = ctx.database.misc.get_blocked_destinations()
        except Exception:
            return out

        for row in blocked or []:
            dest_hex = row.get("destination_hash") if isinstance(row, dict) else None
            if not dest_hex:
                continue
            candidates = [dest_hex]
            try:
                announce = ctx.database.announces.get_announce_by_hash(dest_hex)
                if announce and announce.get("identity_hash"):
                    candidates.append(announce["identity_hash"])
            except Exception:
                pass
            for candidate in candidates:
                try:
                    raw = bytes.fromhex(str(candidate))
                except Exception:
                    continue
                if len(raw) != RNS.Reticulum.TRUNCATED_HASHLENGTH // 8:
                    continue
                if raw in seen:
                    continue
                seen.add(raw)
                out.append(raw)
        return out

    def sync_telephone_call_policy(self, context=None):
        """Push contacts-only / DND / block policy into LXST Telephone.set_allowed.

        This rejects unauthorized callers before RINGING instead of relying only
        on a delayed hangup after the ringing callback.
        """
        ctx = context or self.current_context
        if not ctx or not getattr(ctx, "telephone_manager", None):
            return

        def allowed(identity_hash: bytes, policy_ctx=ctx) -> bool:
            if not isinstance(identity_hash, (bytes, bytearray)):
                return False
            caller_hex = bytes(identity_hash).hex()
            try:
                if policy_ctx.config.do_not_disturb_enabled.get():
                    return False
                if self.is_destination_blocked(caller_hex, context=policy_ctx):
                    return False
                if (
                    policy_ctx.config.telephone_allow_calls_from_contacts_only.get()
                    or policy_ctx.config.block_all_from_strangers.get()
                ) and not self._is_contact(caller_hex, context=policy_ctx):
                    return False
                return True
            except Exception as e:
                print(f"sync_telephone_call_policy allowed() error: {e}")
                return False

        try:
            ctx.telephone_manager.set_call_policy(
                allowed_fn=allowed,
                blocked_identity_hashes=self._collect_blocked_identity_hashes(
                    context=ctx,
                ),
            )
        except Exception as e:
            print(f"sync_telephone_call_policy failed: {e}")

    def incoming_call_is_policy_filtered(self, caller_hex, context=None) -> bool:
        """True when an inbound ring must not surface in the local UI.

        Covers DND, banishment, contacts-only, and block-strangers. Missing
        caller identity is treated as filtered when a contact gate is on.
        Unexpected errors fail closed.
        """
        ctx = context or self.current_context
        if not ctx or not getattr(ctx, "config", None):
            return True
        try:
            if ctx.config.do_not_disturb_enabled.get():
                return True
            if caller_hex and self.is_destination_blocked(caller_hex, context=ctx):
                return True
            if (
                ctx.config.telephone_allow_calls_from_contacts_only.get()
                or ctx.config.block_all_from_strangers.get()
            ) and (not caller_hex or not self._is_contact(caller_hex, context=ctx)):
                return True
            return False
        except Exception as e:
            print(f"incoming_call_is_policy_filtered: {e}")
            return True

    def is_destination_blocked(self, destination_hash: str, context=None) -> bool:
        """Return whether destination_hash is in the block list.

        Accepts either a destination hash or an identity hash. A block on the
        identity matches every known destination of that identity, and a block
        on any destination matches the identity. Unexpected database errors
        fail closed so inbound LXMF and LXST do not treat a broken ACL as open.
        """
        ctx = context or self.current_context
        if not ctx or not ctx.database:
            return False
        try:
            related = self._related_hashes_for_contact_lookup(
                destination_hash,
                context=ctx,
            )
            if destination_hash and destination_hash not in related:
                related = [destination_hash, *related]
            for peer_hash in related:
                if ctx.database.misc.is_destination_blocked(peer_hash):
                    return True
            return False
        except Exception:
            return True

    def _lxmf_reticulum_enforce_block(
        self,
        destination_hash: str,
        context=None,
    ) -> None:
        """Apply Reticulum blackhole or drop_path after a peer was added to the block list."""
        ctx = context or self.current_context
        try:
            if not hasattr(self, "reticulum") or not self.reticulum:
                return
            db = getattr(ctx, "database", None) if ctx is not None else None
            if db is None:
                db = self.database
            identity_hash = None
            if db is not None:
                announce = db.announces.get_announce_by_hash(destination_hash)
                if announce and announce.get("identity_hash"):
                    identity_hash = announce["identity_hash"]
                else:
                    by_ident = db.announces.get_announces_by_identity_hash(
                        destination_hash,
                    )
                    try:
                        by_ident = list(by_ident or [])
                    except TypeError:
                        by_ident = []
                    if by_ident:
                        identity_hash = destination_hash
            target_hash = identity_hash or destination_hash
            dest_bytes = bytes.fromhex(target_hash)
            use_blackhole = True
            cfg = getattr(ctx, "config", None) if ctx is not None else None
            if cfg is None:
                cfg = self.config
            if cfg is not None:
                try:
                    use_blackhole = bool(cfg.blackhole_integration_enabled.get())
                except Exception:
                    use_blackhole = True
            if use_blackhole and hasattr(self.reticulum, "blackhole_identity"):
                reason = (
                    f"Blocked in MeshChatX (from {destination_hash})"
                    if identity_hash
                    else "Blocked in MeshChatX"
                )
                self.reticulum.blackhole_identity(dest_bytes, reason=reason)
            else:
                self.reticulum.drop_path(dest_bytes)
        except Exception as e:
            print(f"_lxmf_reticulum_enforce_block: failed: {e}")

    def _delete_contact_and_stamp_ticket(
        self,
        destination_hash: str,
        context=None,
    ) -> None:
        """Remove contact and stamp/ticket state for a blocked destination."""
        ctx = context or self.current_context
        if not ctx or not ctx.database:
            return
        try:
            contact = self._resolve_contact_for_hash(destination_hash, context=ctx)
            if contact and contact.get("id"):
                ctx.database.contacts.delete_contact(contact["id"])
        except Exception as e:
            print(f"_delete_contact_and_stamp_ticket: contact delete failed: {e}")

        try:
            # Remove stamp costs and tickets from LXMRouter
            if ctx.message_router:
                dest_bytes = bytes.fromhex(destination_hash)
                # Remove outbound stamp cost
                if hasattr(ctx.message_router, "outbound_stamp_costs"):
                    ctx.message_router.outbound_stamp_costs.pop(dest_bytes, None)
                # Remove tickets
                if hasattr(ctx.message_router, "available_tickets"):
                    ctx.message_router.available_tickets["outbound"].pop(
                        dest_bytes,
                        None,
                    )
                    ctx.message_router.available_tickets["inbound"].pop(
                        dest_bytes,
                        None,
                    )
                    ctx.message_router.available_tickets["last_deliveries"].pop(
                        dest_bytes,
                        None,
                    )
                # Persist changes
                if hasattr(ctx.message_router, "save_outbound_stamp_costs"):
                    ctx.message_router.save_outbound_stamp_costs()
                if hasattr(ctx.message_router, "save_available_tickets"):
                    ctx.message_router.save_available_tickets()
        except Exception as e:
            print(f"_delete_contact_and_stamp_ticket: stamp/ticket cleanup failed: {e}")

    def banish_lxmf_peer(self, destination_hash: str, context=None) -> None:
        """Banish a peer by identity: persist every known dest, blackhole, wipe history."""
        ctx = context or self.current_context
        if not ctx or not ctx.database:
            return
        destination_hash = normalize_hex_identifier(destination_hash)
        if not destination_hash or len(destination_hash) != 32:
            return
        hashes = self._peer_hashes_for_banishment(destination_hash, context=ctx)
        try:
            for peer_hash in hashes:
                ctx.database.misc.add_blocked_destination(peer_hash)
                self._delete_contact_and_stamp_ticket(peer_hash, context=ctx)
        except Exception as e:
            print(f"banish_lxmf_peer: failed: {e}")
            return
        if ctx.announce_manager:
            ctx.announce_manager.invalidate_peer_sets()
        self._lxmf_reticulum_enforce_block(destination_hash, context=ctx)
        handler = getattr(ctx, "message_handler", None)
        local_dest = getattr(ctx, "local_lxmf_destination", None)
        if handler is not None and local_dest is not None:
            try:
                local_hash = local_dest.hash.hex()
                for peer_hash in hashes:
                    handler.delete_conversation(local_hash, peer_hash)
            except Exception as e:
                print(f"banish_lxmf_peer: conversation delete failed: {e}")
        AsyncUtils.run_async(self._broadcast_blocked_destinations())
        self.sync_telephone_call_policy(context=ctx)

    def lift_lxmf_peer_banishment(self, destination_hash: str, context=None) -> None:
        """Lift banishment for an identity and every known destination hash."""
        ctx = context or self.current_context
        if not ctx or not ctx.database:
            return
        destination_hash = normalize_hex_identifier(destination_hash)
        if not destination_hash or len(destination_hash) != 32:
            return
        hashes = self._peer_hashes_for_banishment(destination_hash, context=ctx)
        for peer_hash in hashes:
            try:
                ctx.database.misc.delete_blocked_destination(peer_hash)
            except Exception as e:
                print(f"lift_lxmf_peer_banishment: delete {peer_hash} failed: {e}")
        if ctx.announce_manager:
            ctx.announce_manager.invalidate_peer_sets()
        try:
            if (
                hasattr(self, "reticulum")
                and self.reticulum
                and hasattr(self.reticulum, "unblackhole_identity")
            ):
                seen = set()
                for peer_hash in hashes:
                    raw = hex_identifier_to_bytes(peer_hash)
                    if not raw or raw in seen:
                        continue
                    seen.add(raw)
                    try:
                        self.reticulum.unblackhole_identity(raw)
                    except Exception:
                        pass
        except Exception as e:
            print(f"Failed to unblackhole identity in Reticulum: {e}")
        AsyncUtils.run_async(self._broadcast_blocked_destinations())
        self.sync_telephone_call_policy(context=ctx)

    def _collect_lxmf_sieve_peer_haystack(
        self,
        peer_hash: str,
        context=None,
        contact=None,
    ) -> str:
        ctx = context or self.current_context
        if not ctx or not ctx.database:
            return ""
        parts: list[str] = []
        nm = self.get_lxmf_conversation_name(peer_hash, default_name="")
        if nm:
            parts.append(str(nm))
        custom = self.get_custom_destination_display_name(peer_hash)
        if custom:
            parts.append(str(custom))
        if contact is None:
            contact = ctx.database.contacts.get_contact_by_identity_hash(peer_hash)
        if contact:
            if contact.get("name"):
                parts.append(str(contact["name"]))
            if contact.get("lxmf_address"):
                parts.append(str(contact["lxmf_address"]))
        return " ".join(parts)

    def _evaluate_lxmf_sieve_for_peer(
        self,
        peer_hash: str,
        context=None,
        *,
        message_title=None,
        message_content=None,
    ):
        ctx = context or self.current_context
        if not ctx or not ctx.config:
            return None
        raw = ctx.config.lxmf_sieve_filters_json.get()
        rules = parse_lxmf_sieve_filters_json(raw)
        contact = ctx.database.contacts.get_contact_by_identity_hash(peer_hash)
        is_contact = bool(contact)
        haystack = self._collect_lxmf_sieve_peer_haystack(
            peer_hash,
            context=ctx,
            contact=contact,
        )
        msg_hs = self._lxmf_sieve_message_haystack(message_title, message_content)
        return first_matching_lxmf_sieve_rule(
            rules,
            haystack,
            is_contact=is_contact,
            message_haystack=msg_hs,
        )

    def _apply_lxmf_sieve_folder_rule(
        self,
        peer_hash: str,
        context=None,
        *,
        message_title=None,
        message_content=None,
    ):
        m = self._evaluate_lxmf_sieve_for_peer(
            peer_hash,
            context=context,
            message_title=message_title,
            message_content=message_content,
        )
        if not m or m.get("action") != "folder":
            return
        fid = m.get("folder_id")
        if fid is None:
            return
        try:
            fid_int = int(fid)
        except (TypeError, ValueError):
            return
        ctx = context or self.current_context
        if not ctx or not ctx.database:
            return
        try:
            ctx.database.messages.move_conversation_to_folder(peer_hash, fid_int)
        except Exception:
            pass

    def _apply_message_blocklist_banish_rule(
        self,
        peer_hash: str,
        context=None,
        *,
        message_title=None,
        message_content=None,
    ):
        ctx = context or self.current_context
        if not ctx or not ctx.config:
            return
        if not ctx.config.message_blocklist_enabled.get():
            return
        raw = ctx.config.message_blocklist_json.get()
        blocklist = parse_message_blocklist_json(raw)
        contact = None
        is_contact = False
        if ctx.database:
            contact = ctx.database.contacts.get_contact_by_identity_hash(peer_hash)
            is_contact = bool(contact)
        haystack = self._collect_lxmf_sieve_peer_haystack(
            peer_hash,
            context=ctx,
            contact=contact,
        )
        msg_hs = self._lxmf_sieve_message_haystack(message_title, message_content)
        match = first_matching_blocklist_entry(
            blocklist,
            haystack,
            is_contact=is_contact,
            message_haystack=msg_hs,
        )
        if not match:
            return
        print(
            f"Message blocklist matched entry {match.get('entry_id')} for {peer_hash}; banishing",
        )
        self.banish_lxmf_peer(peer_hash, context=ctx)

    def on_rrc_hub_announce_received(
        self,
        aspect,
        destination_hash,
        announced_identity,
        app_data,
        announce_packet_hash,
        context=None,
    ):
        """Handle Relay Chat rrc.hub announces for hub discovery."""
        ctx = context or self.current_context
        if not ctx or not ctx.running or not ctx.announce_manager or not ctx.database:
            return
        if ctx.config and not ctx.config.rrc_enabled.get():
            return

        identity_hash = announced_identity.hash.hex()
        verdict = ctx.announce_manager.classify_announce(
            destination_hash,
            identity_hash,
        )
        if verdict == "blocked":
            logger.debug(
                "Dropping rrc.hub announce from blocked source: %s",
                identity_hash,
            )
            if hasattr(self, "reticulum") and self.reticulum:
                self.reticulum.drop_path(destination_hash)
            return

        if not ctx.announce_manager.is_storing_announce_for_aspect(aspect):
            return

        logger.debug(
            "Received an announce from %s for [rrc.hub]",
            RNS.prettyhexrep(destination_hash),
        )

        self._note_announce_timestamp()

        if verdict == "background":
            ctx.announce_manager.upsert_announce(
                self.reticulum,
                announced_identity,
                destination_hash,
                aspect,
                app_data,
                announce_packet_hash,
                defer=True,
            )
            self._broadcast_announce_event(
                self.build_pending_announce_dict(
                    aspect,
                    destination_hash,
                    announced_identity,
                    app_data,
                    announce_packet_hash,
                ),
            )
            return

        ctx.announce_manager.upsert_announce(
            self.reticulum,
            announced_identity,
            destination_hash,
            aspect,
            app_data,
            announce_packet_hash,
        )

        announce = ctx.database.announces.get_announce_by_hash(destination_hash.hex())
        if not announce:
            return

        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "announce",
                        "announce": self.convert_db_announce_to_dict(announce),
                    },
                ),
            ),
        )

    def on_nomadnet_node_announce_received(
        self,
        aspect,
        destination_hash,
        announced_identity,
        app_data,
        announce_packet_hash,
        context=None,
    ):
        """Handle nomadnetwork.node announces (synchronous Reticulum callback)."""
        ctx = context or self.current_context
        if not ctx or not ctx.running or not ctx.announce_manager or not ctx.database:
            return

        # check if source is blocked - drop announce and path if blocked
        identity_hash = announced_identity.hash.hex()
        verdict = ctx.announce_manager.classify_announce(
            destination_hash,
            identity_hash,
        )
        if verdict == "blocked":
            logger.debug(
                "Dropping announce from blocked source: %s",
                identity_hash,
            )
            if hasattr(self, "reticulum") and self.reticulum:
                self.reticulum.drop_path(destination_hash)
            return

        if not ctx.announce_manager.is_storing_announce_for_aspect(aspect):
            return

        logger.debug(
            "Received an announce from %s for [nomadnetwork.node]",
            RNS.prettyhexrep(destination_hash),
        )

        # track announce timestamp
        self._note_announce_timestamp()

        if verdict == "background":
            ctx.announce_manager.upsert_announce(
                self.reticulum,
                announced_identity,
                destination_hash,
                aspect,
                app_data,
                announce_packet_hash,
                defer=True,
            )
            self._broadcast_announce_event(
                self.build_pending_announce_dict(
                    aspect,
                    destination_hash,
                    announced_identity,
                    app_data,
                    announce_packet_hash,
                ),
            )
            self.queue_crawler_task(
                destination_hash.hex(),
                self.config.nomad_default_page_path.get() or "/page/index.mu",
            )
            return

        # upsert announce to database
        ctx.announce_manager.upsert_announce(
            self.reticulum,
            announced_identity,
            destination_hash,
            aspect,
            app_data,
            announce_packet_hash,
        )

        # find announce from database
        announce = ctx.database.announces.get_announce_by_hash(destination_hash.hex())
        if not announce:
            return

        # send database announce to all websocket clients
        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "announce",
                        "announce": self.convert_db_announce_to_dict(announce),
                    },
                ),
            ),
        )

        self.queue_crawler_task(
            destination_hash.hex(),
            self.config.nomad_default_page_path.get() or "/page/index.mu",
        )

    # queues a crawler task for the provided destination and path
    def queue_crawler_task(
        self,
        destination_hash: str,
        page_path: str,
        context=None,
        force: bool = False,
    ):
        ctx = context or self.current_context
        if not ctx:
            return
        crawler = getattr(ctx, "crawler_manager", None)
        if crawler and not force and not ctx.config.crawler_enabled.get():
            return
        if crawler:
            crawler.queue_if_allowed(
                destination_hash,
                page_path,
                depth=0,
                announced_recently=True,
                force=force,
            )
            return
        ctx.database.misc.upsert_crawl_task(destination_hash, page_path)
