"""Extracted mixin for ReticulumMeshChat::build.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""


class BuildMixin:
    def build_user_guidance_messages(self):
        from meshchatx.src.backend.lifecycle.user_guidance import (
            build_user_guidance_messages,
        )

        return build_user_guidance_messages(self)
