"""Extracted mixin for ReticulumMeshChat::check.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""


class CheckMixin:
    def _check_bot_lifecycle(self) -> tuple[bool, str]:
        """Create, start, stop, and delete an Echo bot subprocess.

        Uses an isolated identity + Reticulum config under storage so the check
        does not touch user bots or ~/.reticulum.
        """
        from meshchatx.src.backend.lifecycle.bot_lifecycle import check_bot_lifecycle

        return check_bot_lifecycle(self)

    def run_self_test(self) -> dict:
        from meshchatx.src.backend.lifecycle.self_test import (
            run_self_test as _run_self_test,
        )

        return _run_self_test(self)
