"""Extracted mixin for ReticulumMeshChat::coerce.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""


class CoerceMixin:
    # helper to parse boolean from possible string or bool
    @staticmethod
    def _parse_bool(value):
        if value is None:
            return False
        if isinstance(value, str):
            return value.lower() == "true"
        return bool(value)

    # Coerce untrusted config input to int. Returns None when the value
    # cannot be converted so update_config can skip or fall back instead of
    # raising on None/strings/lists received via the websocket API.
    @staticmethod
    def _coerce_int(value):
        try:
            return int(value)
        except (TypeError, ValueError):
            return None

    @staticmethod
    def _normalize_optional_hex_color(value):
        if value is None or value == "":
            return None
        if isinstance(value, str):
            trimmed = value.strip()
            if len(trimmed) == 7 and trimmed.startswith("#"):
                try:
                    int(trimmed[1:], 16)
                    return trimmed
                except ValueError:
                    return None
        return None

    async def update_config(self, data):
        from meshchatx.src.backend.lifecycle.config_update import apply_config_update

        return await apply_config_update(self, data)
