"""Extracted mixin for ReticulumMeshChat::convert.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""


class ConvertMixin:
    def _is_contact(self, source_hash: str, context=None) -> bool:
        return self._resolve_contact_for_hash(source_hash, context=context) is not None

    def _encode_pcm_wav_to_ogg_opus(self, wav_bytes: bytes) -> bytes | None:
        """Encode a WAV/PCM payload into an OGG/Opus byte string.

        Thin compatibility wrapper around
        meshchatx.src.backend.audio_codec.encode_audio_bytes_to_ogg_opus
        kept for the existing test surface.
        """
        try:
            from meshchatx.src.backend import audio_codec

            return audio_codec.encode_audio_bytes_to_ogg_opus(wav_bytes)
        except Exception as e:
            print(f"PCM->OGG/Opus encoding via LXST failed: {e}")
            return None

    def _convert_webm_opus_to_ogg(self, audio_bytes: bytes) -> bytes:
        """Convert browser-recorded audio into LXMF-compatible OGG/Opus.

        Routes everything through
        meshchatx.src.backend.audio_codec, which decodes the input
        with miniaudio (WAV/MP3/FLAC/OGG-Vorbis) or LXST (OGG/Opus) and
        re-encodes it with LXST's voice-friendly Opus profile. If decoding
        fails the original bytes are returned unchanged so the caller can
        still try to send the message.
        """
        if audio_bytes[:4] == b"OggS":
            return audio_bytes
        try:
            from meshchatx.src.backend import audio_codec

            encoded = audio_codec.encode_audio_bytes_to_ogg_opus(audio_bytes)
        except Exception as e:
            print(f"audio conversion failed: {e}")
            return audio_bytes
        if encoded is None:
            return audio_bytes
        return encoded
