"""Extracted mixin for ReticulumMeshChat::define.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

from aiohttp import WSCloseCode, WSMessage, WSMsgType, web
from meshchatx.src.backend.appcontainer_sandbox import (
    appcontainer_auto_enabled,
    appcontainer_disabled_by_env,
    appcontainer_requested,
    appcontainer_supported,
    apply_windows_process_mitigations,
    is_appcontainer_child,
)
from meshchatx.src.backend.landlock_sandbox import (
    apply_landlock_sandbox,
    extra_read_roots_from_app,
    landlock_abi_version,
    landlock_auto_enabled,
    landlock_disabled_by_env,
    landlock_kernel_supported,
    landlock_requested,
)
from meshchatx.src.backend.seccomp_sandbox import (
    apply_seccomp_sandbox,
    seccomp_auto_enabled,
    seccomp_disabled_by_env,
    seccomp_kernel_supported,
    seccomp_requested,
)

class DefineMixin:
    def _landlock_status_dict(self) -> dict:
        return {
            "landlock_kernel_supported": landlock_kernel_supported(),
            "landlock_abi": landlock_abi_version(),
            "landlock_requested": landlock_requested(),
            "landlock_auto_enabled": landlock_auto_enabled(),
            "landlock_disabled_by_env": landlock_disabled_by_env(),
            "landlock_active": self.landlock_active,
            "appcontainer_supported": appcontainer_supported(),
            "appcontainer_requested": appcontainer_requested(),
            "appcontainer_auto_enabled": appcontainer_auto_enabled(),
            "appcontainer_disabled_by_env": appcontainer_disabled_by_env(),
            "appcontainer_active": self.appcontainer_active,
            "fs_sandbox_active": bool(self.landlock_active or self.appcontainer_active),
            "seccomp_kernel_supported": seccomp_kernel_supported(),
            "seccomp_requested": seccomp_requested(),
            "seccomp_auto_enabled": seccomp_auto_enabled(),
            "seccomp_disabled_by_env": seccomp_disabled_by_env(),
            "seccomp_active": self.seccomp_active,
        }

    @property
    def fs_sandbox_active(self) -> bool:
        return bool(self.landlock_active or self.appcontainer_active)

    def get_routes(self):
        routes = web.RouteTableDef()
        self._define_routes(routes)
        return routes

    def _define_routes(self, routes):
        from meshchatx.src.backend.http.register import register_all_routes

        (
            bad_request_middleware,
            sqlite_unavailable_middleware,
            auth_middleware,
            mime_type_middleware,
            security_middleware,
            csrf_middleware,
            ip_allowlist_middleware,
            demo_mode_middleware,
        ) = register_all_routes(routes, self)

        return (
            bad_request_middleware,
            sqlite_unavailable_middleware,
            auth_middleware,
            mime_type_middleware,
            security_middleware,
            csrf_middleware,
            ip_allowlist_middleware,
            demo_mode_middleware,
        )
