"""Extracted mixin for ReticulumMeshChat::disable.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

from meshchatx.android_push_bridge import (
    _get_android_external_files_dir,
    _is_chaquopy_android,
)

class DisableMixin:
    @staticmethod
    def _disable_rnode_interfaces_on_android(config_path: str) -> bool:
        """Disable enabled RNode* interfaces in Reticulum config (Android recovery helper)."""
        if not _is_chaquopy_android():
            return False
        from meshchatx.src.backend.rnode_support import (
            disable_rnode_interfaces_in_config,
        )

        return disable_rnode_interfaces_in_config(config_path, is_android=True)
