"""Extracted mixin for ReticulumMeshChat::exit.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

import sys

class ExitMixin:
    def exit_app(self, code=0):
        sys.exit(code)
