"""Extracted mixin for ReticulumMeshChat::force.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

import contextlib
import os
import socket

class ForceMixin:
    def _force_close_listener(self, listener):
        """Aggressively close a multiprocessing.connection.Listener.

        Calls Listener.close() and additionally drills through the inner
        SocketListener wrapper to close the underlying socket file descriptor.
        Necessary because the rpc_loop thread can retain references to the
        listener that prevent the kernel from releasing abstract AF_UNIX
        addresses on plain close().
        """
        try:
            if hasattr(listener, "close"):
                with contextlib.suppress(Exception):
                    listener.close()
        finally:
            socket_type = getattr(socket, "SocketType", None)
            wrappers = [listener]

            listener_inner = getattr(listener, "_listener", None)
            if listener_inner is not None:
                wrappers.append(listener_inner)

            for wrapper in list(wrappers):
                inner_socket = getattr(wrapper, "_socket", None)
                if inner_socket is not None:
                    wrappers.append(inner_socket)
                plain_socket = getattr(wrapper, "socket", None)
                if plain_socket is not None:
                    wrappers.append(plain_socket)

            for obj in wrappers:
                if socket_type is None or not isinstance(obj, socket_type):
                    continue
                fileno = -1
                try:
                    fileno = obj.fileno()
                except Exception:
                    pass
                with contextlib.suppress(Exception):
                    obj.close()
                if fileno != -1:
                    try:
                        os.close(fileno)
                    except OSError:
                        pass

            for wrapper in wrappers:
                with contextlib.suppress(Exception):
                    if hasattr(wrapper, "_socket"):
                        wrapper._socket = None
                with contextlib.suppress(Exception):
                    if hasattr(wrapper, "socket"):
                        wrapper.socket = None
            with contextlib.suppress(Exception):
                if hasattr(listener, "_listener"):
                    listener._listener = None
