"""Extracted mixin for ReticulumMeshChat::get.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

from aiohttp import WSCloseCode, WSMessage, WSMsgType, web
from aiohttp_session import get_session
from datetime import UTC, datetime
from meshchatx.src.backend import (
    gif_utils,
    i2p_support,
    reticulum_pathfinding,
    sticker_pack_utils,
)
from meshchatx.src.backend.app_security_settings import (
    get_trusted_proxy_cidrs,
    get_web_ui_ip_allowlist,
    load_app_security_settings,
    save_app_security_settings,
)
from meshchatx.src.backend.database.access_attempts import (
    LOGIN_PATH,
    MAX_FAILED_BEFORE_LOCKOUT,
    MAX_TRUSTED_LOGIN_PER_WINDOW,
    MAX_UNTRUSTED_LOGIN_PER_WINDOW,
    SETUP_PATH,
    WINDOW_LOCKOUT_S,
    WINDOW_RATE_TRUSTED_S,
    WINDOW_RATE_UNTRUSTED_S,
    user_agent_hash,
)
from meshchatx.src.backend.demo_mode import (
    auth_bypass_from_env,
    demo_auth_password_from_env,
)
from meshchatx.src.backend.interface_editor import InterfaceEditor
from meshchatx.src.backend.meshchat_utils import (
    cancel_inbound_deliveries,
    convert_db_favourite_to_dict,
    convert_propagation_node_state_to_string,
    hex_identifier_to_bytes,
    interval_action_due,
    message_fields_have_attachments,
    normalize_hex_identifier,
    normalize_identity_storage_hash,
    parse_bool_query_param,
    parse_lxmf_display_name,
    parse_lxmf_propagation_node_app_data,
    parse_lxmf_stamp_cost,
    parse_nomadnetwork_node_display_name,
    propagation_sync_idle_like,
    propagation_sync_is_terminal,
)
from meshchatx.src.backend.privacy_mode import (
    OutboundHttpBlockedError,
    ensure_outbound_http_allowed,
    privacy_mode_enabled,
)
from meshchatx.src.path_utils import (
    get_file_path,
    is_loopback_bind_host,
    is_path_within_dir,
    resolve_log_dir,
    resolve_meshchat_data_roots,
    safe_path_under_dir,
)
from meshchatx.src.path_utils import (
    request_client_ip as _request_client_ip,
)
from meshchatx.src.version import __version__ as app_version
import RNS
import contextlib
import copy
import gc
import importlib.metadata
import os
import psutil
import time

class GetMixin:
    @property
    def auth_enabled(self):
        if auth_bypass_from_env():
            return False
        if self.config:
            return self.config.auth_enabled.get() or self._oidc_ready()
        return self.auth_enabled_initial or self._oidc_ready()

    def _oidc_settings(self):
        from meshchatx.src.backend.oidc import load_oidc_settings

        return load_oidc_settings(self.config)

    def _oidc_ready(self) -> bool:
        from meshchatx.src.backend.oidc import oidc_ready

        return oidc_ready(self._oidc_settings())

    @staticmethod
    def _normalize_reticulum_config_dir(config_candidate: str | None) -> str:
        """Normalize Reticulum config candidate to a config directory path."""
        candidate = config_candidate
        if not candidate:
            candidate = (
                getattr(RNS.Reticulum, "configdir", None)
                or os.path.dirname(getattr(RNS.Reticulum, "configpath", "") or "")
                or os.path.expanduser("~/.reticulum")
            )

        candidate = os.path.expanduser(str(candidate))
        # Reticulum's config file is plaintext named "config" (no extension).
        # If a file path is provided, convert it to its parent directory.
        if os.path.basename(candidate) == "config" and not os.path.isdir(candidate):
            return os.path.dirname(candidate) or os.path.expanduser("~/.reticulum")
        return candidate

    def _reticulum_config_file_path(self) -> str:
        return os.path.join(
            self._normalize_reticulum_config_dir(self.reticulum_config_dir),
            "config",
        )

    @staticmethod
    def _write_rns_reticulum_default_config_file(config_path: str) -> str:
        """Write RNS stock default config to config_path; return on-disk text.

        Uses the same template and ConfigObj path as Reticulum.__create_default_config.
        """
        from RNS.vendor.configobj import ConfigObj

        rns_reticulum_mod = importlib.import_module("RNS.Reticulum")
        default_spec = rns_reticulum_mod.__default_rns_config__
        config_dir = os.path.dirname(config_path) or os.path.abspath(".")
        if not os.path.isdir(config_dir):
            os.makedirs(config_dir, exist_ok=True)
        cfg = ConfigObj(default_spec)
        cfg.filename = config_path
        cfg.write()
        with open(config_path) as f:
            return f.read()

    def backup_database(self, backup_path=None):
        if not self.database:
            raise RuntimeError("Database not initialized")
        return self.database.backup_database(self.storage_path, backup_path)

    def list_database_backups(self):
        if not self.database:
            raise RuntimeError("Database not initialized")
        return self.database.list_auto_backups(self.storage_path)

    def export_database_backup(self, name: str, dest_path: str):
        if not self.database:
            raise RuntimeError("Database not initialized")
        return self.database.copy_auto_backup(self.storage_path, name, dest_path)

    def auto_recover_database(self, *, relaunch: bool = True) -> dict:
        from meshchatx.src.backend.database.auto_recover import (
            run_auto_database_recover,
        )
        from meshchatx.src.backend.database.schema import DatabaseSchema

        storage = self.storage_path
        if not storage:
            msg = "Storage path is unknown"
            raise RuntimeError(msg)

        def restore_fn(path: str) -> dict:
            return self.restore_database(path, relaunch=relaunch)

        def sqlite_recover_fn() -> dict:
            path = self.database_path
            if not path:
                msg = "Database path is unknown"
                raise RuntimeError(msg)
            from meshchatx.src.backend.database import Database

            db = Database(path)
            return db.run_database_recovery()

        return run_auto_database_recover(
            storage,
            self.database_path,
            DatabaseSchema.LATEST_VERSION,
            restore_fn,
            sqlite_recover_fn=sqlite_recover_fn,
        )

    def _resolve_database_restore_path(self, path: str) -> str | None:
        """Resolve a restore zip under identity snapshots or database-backups only."""
        if not isinstance(path, str) or not path or "\x00" in path:
            return None
        storage = self.storage_path
        if not storage:
            return None
        allowed_roots = [
            os.path.join(storage, "snapshots"),
            os.path.join(storage, "database-backups"),
        ]
        candidates: list[str] = []
        if os.path.isabs(path):
            candidates.append(path)
        else:
            for root in allowed_roots:
                candidates.append(os.path.join(root, path))
                if not path.endswith(".zip"):
                    candidates.append(os.path.join(root, path + ".zip"))
        for candidate in candidates:
            real = os.path.realpath(candidate)
            if not os.path.isfile(real):
                continue
            if any(is_path_within_dir(real, root) for root in allowed_roots):
                return real
        return None

    def _checkpoint_and_close(self):
        # delegated to database instance
        self.database._checkpoint_and_close()

    def _get_identity_bytes(self) -> bytes:
        return self.identity_manager.get_identity_bytes(self.identity)

    def cleanup_rns_state_for_identity(self, identity_hash):
        if not identity_hash:
            return

        if isinstance(identity_hash, str):
            identity_hash_bytes = bytes.fromhex(identity_hash)
            identity_hash_hex = identity_hash
        else:
            identity_hash_bytes = identity_hash
            identity_hash_hex = identity_hash.hex()

        print(f"Aggressively cleaning up RNS state for identity {identity_hash_hex}")

        # 1. Deregister destinations
        try:
            # We iterate over a copy of the list because we are modifying it
            for destination in list(RNS.Transport.destinations):
                match = False
                # check identity hash
                if hasattr(destination, "identity") and destination.identity:
                    if destination.identity.hash == identity_hash_bytes:
                        match = True

                if match:
                    print(
                        f"Deregistering RNS destination {destination} ({RNS.prettyhexrep(destination.hash)})",
                    )
                    RNS.Transport.deregister_destination(destination)
        except Exception as e:
            print(f"Error while cleaning up RNS destinations: {e}")

        # 2. Teardown active links
        try:
            for link in list(RNS.Transport.active_links):
                match = False
                # check if local identity or destination matches
                if hasattr(link, "destination") and link.destination:
                    if (
                        hasattr(link.destination, "identity")
                        and link.destination.identity
                    ):
                        if link.destination.identity.hash == identity_hash_bytes:
                            match = True

                if match:
                    print(f"Tearing down RNS link {link}")
                    try:
                        link.teardown()
                    except Exception:
                        pass
        except Exception as e:
            print(f"Error while cleaning up RNS links: {e}")

    def _force_close_abstract_unix_addr(self, addr) -> bool:
        """Close every socket FD in the current process bound to addr.

        Returns True if any FD was closed. addr is expected to be a string
        starting with a NUL byte (abstract AF_UNIX namespace).
        """
        if not (isinstance(addr, str) and addr.startswith("\0")):
            return False

        target_bytes = addr.encode("utf-8", errors="replace")
        target_no_nul = target_bytes[1:]
        closed_any = False

        try:
            current_process = psutil.Process()
            for conn in current_process.net_connections(kind="unix"):
                try:
                    laddr = getattr(conn, "laddr", None)
                    fd = getattr(conn, "fd", -1)
                    if not laddr or fd in (-1, None):
                        continue

                    if isinstance(laddr, str):
                        laddr_bytes = laddr.encode("utf-8", errors="replace")
                    elif isinstance(laddr, bytes):
                        laddr_bytes = laddr
                    else:
                        continue

                    laddr_no_nul = (
                        laddr_bytes[1:]
                        if laddr_bytes.startswith(b"\0")
                        else laddr_bytes
                    )

                    if (
                        laddr_bytes in (target_bytes, target_no_nul)
                        or laddr_no_nul == target_no_nul
                    ):
                        try:
                            os.close(fd)
                            closed_any = True
                            print(
                                f"Force closed lingering abstract UNIX FD {fd} for {addr[1:]}",
                            )
                        except OSError as fd_err:
                            print(
                                f"Failed to close FD {fd} for {addr[1:]}: {fd_err}",
                            )
                except Exception:
                    pass
        except Exception as e:
            print(f"Error scanning process for abstract UNIX FDs: {e}")

        if closed_any:
            gc.collect()
            time.sleep(0.2)

        return closed_any

    @staticmethod
    def _reset_transport_globals_for_reload() -> None:
        """Clear RNS Transport globals so a new Reticulum can start cleanly.

        Reticulum.exit_handler sets Transport._should_run = False. Upstream
        Transport.start never flips it back, so hot reload must restore it or
        the new jobloop exits immediately and path/link tools stay dead while
        interface RX/TX counters still update.
        """
        RNS.Transport._should_run = True
        if hasattr(RNS.Transport, "jobs_running"):
            RNS.Transport.jobs_running = False
        RNS.Transport.interfaces = []
        RNS.Transport.local_client_interfaces = []
        RNS.Transport.destinations = []
        if hasattr(RNS.Transport, "destinations_map"):
            RNS.Transport.destinations_map = {}
        RNS.Transport.active_links = []
        RNS.Transport.pending_links = []
        RNS.Transport.announce_handlers = []
        RNS.Transport.announce_table = {}
        RNS.Transport.path_table = {}
        RNS.Transport.reverse_table = {}
        RNS.Transport.link_table = {}
        RNS.Transport.held_announces = {}
        RNS.Transport.tunnels = {}
        RNS.Transport.path_requests = {}
        RNS.Transport.path_states = {}
        RNS.Transport.announce_rate_table = {}
        RNS.Transport.control_destinations = []
        RNS.Transport.control_hashes = []
        RNS.Transport.mgmt_destinations = []
        RNS.Transport.mgmt_hashes = []

    async def reload_reticulum(self):
        from meshchatx.src.backend.lifecycle.reticulum_reload import (
            reload_reticulum_instance,
        )

        async with self._reticulum_reload_lock:
            return await reload_reticulum_instance(self)

    async def hotswap_identity(self, identity_hash, keep_alive=False):
        async with self._identity_hotswap_lock:
            return await self._hotswap_identity_locked(
                identity_hash,
                keep_alive=keep_alive,
            )

    def backup_identity(self):
        return self.identity_manager.backup_identity(self.identity)

    def backup_identity_base32(self) -> str:
        return self.identity_manager.backup_identity_base32(self.identity)

    def list_identities(self):
        return self.identity_manager.list_identities(
            self.identity.hash.hex()
            if hasattr(self, "identity") and self.identity
            else None,
        )

    def create_identity(self, display_name=None):
        return self.identity_manager.create_identity(display_name)

    def _evict_cached_identity_context(self, identity_hash: str) -> None:
        canonical = normalize_identity_storage_hash(identity_hash)
        if not canonical:
            return
        ctx = self.contexts.pop(canonical, None)
        if ctx is not None:
            with contextlib.suppress(Exception):
                ctx.teardown()
        self._propagation_sync_metrics.pop(canonical, None)
        self._drop_auto_resend_locks(canonical)

    def delete_identity(self, identity_hash):
        current_hash = (
            self.identity.hash.hex()
            if hasattr(self, "identity") and self.identity
            else None
        )
        deleted = self.identity_manager.delete_identity(identity_hash, current_hash)
        if deleted:
            self._evict_cached_identity_context(identity_hash)
        return deleted

    def restore_identity_from_bytes(
        self,
        identity_bytes: bytes,
        display_name: str | None = None,
    ):
        return self.identity_manager.restore_identity_from_bytes(
            identity_bytes,
            display_name=display_name,
        )

    def restore_identity_from_base32(
        self,
        base32_value: str,
        display_name: str | None = None,
    ):
        return self.identity_manager.restore_identity_from_base32(
            base32_value,
            display_name=display_name,
        )

    def update_identity_metadata_cache(self):
        if not hasattr(self, "identity") or not self.identity:
            return

        identity_hash = self.identity.hash.hex()
        metadata = {
            "display_name": self.config.display_name.get(),
            "icon_name": self.config.lxmf_user_icon_name.get(),
            "icon_foreground_colour": self.config.lxmf_user_icon_foreground_colour.get(),
            "icon_background_colour": self.config.lxmf_user_icon_background_colour.get(),
            "lxmf_address": self.config.lxmf_address_hash.get(),
            "lxst_address": self.config.lxst_address_hash.get(),
        }
        self.identity_manager.update_metadata_cache(identity_hash, metadata)

    def _run_startup_auto_recovery(self):
        try:
            self.database.initialize()
            print("Attempting SQLite auto recovery on startup...")
            actions = []
            actions.append(
                {
                    "step": "wal_checkpoint",
                    "result": self.database.provider.checkpoint(),
                },
            )
            actions.append(
                {
                    "step": "integrity_check",
                    "result": self.database.provider.integrity_check(),
                },
            )
            self.database.provider.vacuum()
            self.database._tune_sqlite_pragmas()
            actions.append(
                {
                    "step": "quick_check_after",
                    "result": self.database.provider.quick_check(),
                },
            )
            print(f"Auto recovery completed: {actions}")
        finally:
            try:
                self.database.close_all()
            except Exception as e:
                print(f"Failed to close database during recovery: {e}")

    # gets app version from the synchronized Python version helper
    @staticmethod
    def get_app_version() -> str:
        return app_version

    @staticmethod
    def get_build_meta() -> dict:
        """Baked git commit / channel from meshchatx.src.build_meta."""
        try:
            from meshchatx.src import build_meta as _build_meta

            return dict(_build_meta.as_dict(app_version))
        except Exception:
            return {
                "git_commit": "",
                "git_commit_short": "",
                "build_channel": "local",
                "is_dev_build": False,
                "display_version": app_version,
            }

    def _default_announce_fetch_limit(self, aspect):
        ctx = self.current_context
        if not ctx or not ctx.config:
            return 2500
        keys = {
            "lxmf.delivery": ctx.config.announce_fetch_limit_lxmf_delivery,
            "nomadnetwork.node": ctx.config.announce_fetch_limit_nomadnetwork_node,
            "lxmf.propagation": ctx.config.announce_fetch_limit_lxmf_propagation,
            "lxst.telephony": ctx.config.announce_fetch_limit_lxmf_delivery,
        }
        cfg = keys.get(aspect)
        if cfg is None:
            return 2500
        v = cfg.get()
        if v is None or v < 1:
            return 2500
        return min(int(v), 100_000)

    def _get_propagation_sync_metrics(self, context=None):
        ctx = context or self.current_context
        if not ctx:
            return None

        key = ctx.identity_hash
        if key not in self._propagation_sync_metrics:
            self._propagation_sync_metrics[key] = {
                "started_at": None,
                "baseline_total_messages": 0,
                "baseline_delivered_messages": 0,
                "messages_stored": 0,
                "delivery_confirmations": 0,
                "messages_hidden": 0,
            }

        return self._propagation_sync_metrics[key]

    def _begin_propagation_sync_metrics(self, context=None):
        ctx = context or self.current_context
        if not ctx or not ctx.database:
            return

        metrics = self._get_propagation_sync_metrics(context=ctx)
        if metrics is None:
            return

        metrics["started_at"] = datetime.now(UTC).isoformat()
        metrics["baseline_total_messages"] = ctx.database.messages.count_lxmf_messages()
        metrics["baseline_delivered_messages"] = (
            ctx.database.messages.count_lxmf_messages_by_state("delivered")
        )
        metrics["messages_stored"] = 0
        metrics["delivery_confirmations"] = 0
        metrics["messages_hidden"] = 0

    def _collect_propagation_sync_metrics(self, context=None):
        ctx = context or self.current_context
        if not ctx or not ctx.database:
            return {
                "messages_stored": 0,
                "delivery_confirmations": 0,
                "messages_hidden": 0,
            }

        metrics = self._get_propagation_sync_metrics(context=ctx)
        if metrics is None:
            return {
                "messages_stored": 0,
                "delivery_confirmations": 0,
                "messages_hidden": 0,
            }
        if metrics["started_at"] is None:
            return {
                "messages_stored": 0,
                "delivery_confirmations": 0,
                "messages_hidden": 0,
            }

        if not ctx.message_router:
            return {
                "messages_stored": 0,
                "delivery_confirmations": 0,
                "messages_hidden": 0,
            }

        messages_received = ctx.message_router.propagation_transfer_last_result or 0
        current_total_messages = ctx.database.messages.count_lxmf_messages()
        current_delivered_messages = ctx.database.messages.count_lxmf_messages_by_state(
            "delivered",
        )

        messages_stored = max(
            current_total_messages - metrics["baseline_total_messages"],
            0,
        )
        delivery_confirmations = max(
            current_delivered_messages - metrics["baseline_delivered_messages"],
            0,
        )
        messages_hidden = max(
            messages_received - messages_stored - delivery_confirmations,
            0,
        )

        metrics["messages_stored"] = messages_stored
        metrics["delivery_confirmations"] = delivery_confirmations
        metrics["messages_hidden"] = messages_hidden

        return {
            "messages_stored": messages_stored,
            "delivery_confirmations": delivery_confirmations,
            "messages_hidden": messages_hidden,
        }

    def _get_reticulum_section(self):
        try:
            if hasattr(self, "reticulum") and self.reticulum:
                reticulum_config = self.reticulum.config["reticulum"]
            else:
                return {}
        except Exception:
            reticulum_config = None

        if not isinstance(reticulum_config, dict):
            reticulum_config = {}
            if hasattr(self, "reticulum") and self.reticulum:
                self.reticulum.config["reticulum"] = reticulum_config

        return reticulum_config

    def _get_interfaces_section(self):
        try:
            if hasattr(self, "reticulum") and self.reticulum:
                interfaces = self.reticulum.config["interfaces"]
            else:
                return {}
        except Exception:
            interfaces = None

        if not isinstance(interfaces, dict):
            interfaces = {}
            if hasattr(self, "reticulum") and self.reticulum:
                self.reticulum.config["interfaces"] = interfaces

        return interfaces

    @staticmethod
    def _copy_interface_section(details):
        try:
            return copy.deepcopy(dict(details))
        except Exception:
            try:
                return copy.deepcopy(details)
            except Exception:
                return {}

    def _disk_interface_sections(self) -> dict:
        """Parse [[interface]] sections from the on-disk Reticulum config file.

        The Interfaces page reads reticulum.config in memory. The raw config
        editor reads the file. Those two can diverge after a raw save, a
        failed write, or an external edit, which hides a configured interface
        from the tiles.
        """
        try:
            path = self._reticulum_config_file_path()
        except Exception:
            path = None
        if not path or not os.path.isfile(path):
            return {}
        try:
            from RNS.vendor.configobj import ConfigObj

            cfg = ConfigObj(path)
        except Exception:
            return {}
        interfaces = cfg.get("interfaces")
        if not isinstance(interfaces, dict):
            return {}
        copied = {}
        for name, details in interfaces.items():
            if not isinstance(details, dict):
                continue
            copied[str(name)] = self._copy_interface_section(details)
        return copied

    def _sync_interfaces_from_disk(self, *, replace: bool = False) -> None:
        """Align the live interfaces map with the on-disk config file.

        replace False adds disk-only sections so tiles and delete/enable can
        see them. replace True makes the live map match the file (raw editor
        save or restore).
        """
        disk = self._disk_interface_sections()
        mem = self._get_interfaces_section()
        if replace:
            for name in list(mem.keys()):
                if name not in disk:
                    del mem[name]
        for name, details in disk.items():
            if replace or name not in mem:
                mem[name] = details

    def _get_interfaces_snapshot(self):
        snapshot = {}
        interfaces = self._get_interfaces_section()
        for name, interface in interfaces.items():
            try:
                snapshot[name] = copy.deepcopy(dict(interface))
            except Exception:
                try:
                    snapshot[name] = copy.deepcopy(interface)
                except Exception:
                    snapshot[name] = {}
        return snapshot

    def _sanitize_interfaces_section_names(self) -> None:
        """Rewrite interface section keys so ConfigObj can reload the config file."""
        interfaces = self._get_interfaces_section()
        if not isinstance(interfaces, dict) or not interfaces:
            return
        renamed: dict = {}
        changed = False
        for name, details in list(interfaces.items()):
            safe = InterfaceEditor.sanitize_interface_section_name(name)
            if not safe:
                safe = "Interface"
            if safe != name:
                changed = True
            # Avoid collisions after sanitizing two distinct names to the same key.
            final = safe
            suffix = 2
            while final in renamed:
                final = f"{safe} ({suffix})"
                suffix += 1
            if final != name:
                changed = True
            renamed[final] = details
        if changed:
            if hasattr(self, "reticulum") and self.reticulum:
                self.reticulum.config["interfaces"] = renamed

    def _write_reticulum_config(self, *, rollback_interfaces=None):
        try:
            if hasattr(self, "reticulum") and self.reticulum:
                self._sanitize_interfaces_section_names()
                try:
                    i2p_support.repair_interfaces_dict(
                        self._get_interfaces_section(),
                        self._get_reticulum_section(),
                    )
                except Exception as i2p_exc:
                    print(f"I2P config repair before write failed: {i2p_exc}")
                self.reticulum.config.write()
                self._verify_reticulum_config_reloadable()
                return True
            return False
        except Exception as e:
            print(f"Failed to write Reticulum config: {e}")
            if (
                rollback_interfaces is not None
                and hasattr(self, "reticulum")
                and self.reticulum
            ):
                try:
                    self.reticulum.config["interfaces"] = rollback_interfaces
                except Exception as restore_exc:
                    print(
                        "Failed to restore Reticulum interfaces after write error: "
                        f"{restore_exc}",
                    )
            return False

    def _detect_failed_autointerfaces(self):
        """Return AutoInterface section names enabled in config but not running."""
        enabled_names = []
        try:
            interfaces = self._get_interfaces_section()
        except Exception:
            return []

        if not isinstance(interfaces, dict) or not interfaces:
            return []

        for name, section in interfaces.items():
            if not isinstance(section, dict):
                continue
            if str(section.get("type", "")).strip() != "AutoInterface":
                continue
            enabled_raw = (
                str(
                    section.get("enabled") or section.get("interface_enabled") or "",
                )
                .strip()
                .lower()
            )
            if enabled_raw in ("yes", "true", "1"):
                enabled_names.append(name)

        if not enabled_names:
            return []

        try:
            live = getattr(RNS.Transport, "interfaces", None) or []
            for iface in live:
                if iface.__class__.__name__ == "AutoInterface":
                    return []
        except Exception:
            return []

        return enabled_names

    # returns the latest message for the provided destination hash
    def get_conversation_latest_message(self, destination_hash: str):
        local_hash = self.identity.hash.hex()
        messages = self.message_handler.get_conversation_messages(
            local_hash,
            destination_hash,
            limit=1,
        )
        return messages[0] if messages else None

    # returns true if the conversation with the provided destination hash has any attachments
    def conversation_has_attachments(self, destination_hash: str):
        local_hash = self.identity.hash.hex()
        messages = self.message_handler.get_conversation_messages(
            local_hash,
            destination_hash,
        )
        for message in messages:
            if message_fields_have_attachments(message["fields"]):
                return True
        return False

    def _require_outbound_http(self, feature: str) -> None:
        if self.config:
            ensure_outbound_http_allowed(self.config, feature=feature)

    def _enforce_login_access(self, request, path: str):
        if not self.database:
            return None
        ip = _request_client_ip(request, get_trusted_proxy_cidrs(self.storage_dir))
        ua = request.headers.get("User-Agent", "") or ""
        ua_h = user_agent_hash(ua)
        id_hash = self.identity.hash.hex()
        dao = self.database.access_attempts
        trusted = dao.is_trusted(id_hash, ip, ua_h)
        now = time.time()
        if trusted:
            if (
                dao.count_login_attempts_ip_ua(
                    ip,
                    ua_h,
                    path,
                    now - WINDOW_RATE_TRUSTED_S,
                )
                >= MAX_TRUSTED_LOGIN_PER_WINDOW
            ):
                dao.insert(
                    id_hash,
                    ip,
                    ua,
                    path,
                    request.method,
                    "rate_limited",
                    "trusted_window",
                )
                return web.json_response(
                    {"error": "Too many requests. Try again later."},
                    status=429,
                )
        else:
            if (
                dao.count_login_attempts_ip(ip, path, now - WINDOW_RATE_UNTRUSTED_S)
                >= MAX_UNTRUSTED_LOGIN_PER_WINDOW
            ):
                dao.insert(
                    id_hash,
                    ip,
                    ua,
                    path,
                    request.method,
                    "rate_limited",
                    "ip_window",
                )
                return web.json_response(
                    {"error": "Too many requests. Try again later."},
                    status=429,
                )
            if (
                dao.count_lockout_failures(id_hash, ip, now - WINDOW_LOCKOUT_S)
                >= MAX_FAILED_BEFORE_LOCKOUT
            ):
                dao.insert(
                    id_hash,
                    ip,
                    ua,
                    path,
                    request.method,
                    "lockout",
                    "failures",
                )
                return web.json_response(
                    {
                        "error": "Too many failed login attempts from this address. Try again later.",
                    },
                    status=429,
                )
        return None

    def archive_page(
        self,
        destination_hash: str,
        page_path: str,
        content: str,
        is_manual: bool = False,
        context=None,
    ):
        ctx = context or self.current_context
        if not ctx:
            return None
        return ctx.nomadnet_manager.archive_page(
            destination_hash,
            page_path,
            content,
            is_manual,
        )

    async def _websocket_session_authorized(self, client) -> bool:
        if not self.auth_enabled:
            return True
        request = getattr(client, "_meshchatx_request", None)
        if request is None:
            request = getattr(client, "request", None)
        if request is None:
            return False
        try:
            session = await get_session(request)
        except Exception:
            return False
        identity_hash = self.identity.hash.hex() if self.identity else None
        return bool(
            session.get("authenticated", False)
            and identity_hash
            and session.get("identity_hash") == identity_hash,
        )

    # convert database lxmf message to a dictionary
    # updates the lxmf user icon for the provided destination hash
    def update_lxmf_user_icon(
        self,
        destination_hash: str,
        icon_name: str,
        foreground_colour: str,
        background_colour: str,
        context=None,
    ):
        ctx = context or self.current_context
        if not ctx:
            return

        # ensure we're not storing the user's own icon with a peer's hash
        # only store icons for remote peers, not for the local user
        if (
            ctx.local_lxmf_destination
            and destination_hash == ctx.local_lxmf_destination.hexhash
        ):
            print(f"skipping icon update for local user's own hash: {destination_hash}")
            return

        # log
        print(
            f"updating lxmf user icon for {destination_hash} to icon_name={icon_name}, foreground_colour={foreground_colour}, background_colour={background_colour}",
        )

        ctx.database.misc.update_lxmf_user_icon(
            destination_hash,
            icon_name,
            foreground_colour,
            background_colour,
        )

    def _lxmf_path_wait_seconds(self):
        return reticulum_pathfinding.lxmf_path_wait_cap_seconds()

    async def _await_transport_path(self, destination_hash_bytes: bytes):
        r = self.reticulum if hasattr(self, "reticulum") else None
        return await reticulum_pathfinding.await_transport_path_for_outbound_lxmf(
            r,
            destination_hash_bytes,
        )
