"""Extracted mixin for ReticulumMeshChat::get_3.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""


class Get3Mixin:
    def get_local_propagation_node_stats(self, context=None):
        from meshchatx.src.backend.lifecycle.propagation_stats import (
            get_local_propagation_node_stats,
        )

        return get_local_propagation_node_stats(self, context)
