"""Extracted mixin for ReticulumMeshChat::get_2.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

import LXST
import importlib.metadata
import math

class Get2Mixin:
    @staticmethod
    def get_package_version(package_name: str, default: str = "unknown") -> str:
        """Resolve an installed distribution version for About /app/info.

        cx_Freeze and similar bundles often omit .dist-info; fall back to module
        attributes and known submodule layouts (e.g. websockets.version).
        """
        try:
            from packaging.utils import canonicalize_name as _canonicalize_name
        except Exception:

            def _canonicalize_name(name: str) -> str:
                return str(name).strip().lower().replace("_", "-")

        def _from_metadata(dist_name: str) -> str | None:
            for candidate in dict.fromkeys((dist_name, _canonicalize_name(dist_name))):
                try:
                    v = importlib.metadata.version(candidate)
                    if v:
                        return str(v)
                except Exception:
                    pass
                try:
                    v = importlib.metadata.distribution(candidate).version
                    if v:
                        return str(v)
                except Exception:
                    pass
            return None

        resolved = _from_metadata(package_name)
        if resolved:
            return resolved

        module_name = package_name.replace("-", "_")
        top_level = module_name.split(".")[0]

        try:
            for dist_name in importlib.metadata.packages_distributions().get(
                top_level,
                (),
            ):
                resolved = _from_metadata(dist_name)
                if resolved:
                    return resolved
        except Exception:
            pass

        try:
            module = importlib.import_module(module_name)
            ver = getattr(module, "__version__", None)
            if ver:
                return str(ver)
        except Exception:
            pass

        if top_level == "websockets":
            try:
                from websockets.version import version as websockets_semver

                if websockets_semver:
                    return str(websockets_semver)
            except Exception:
                pass

        if top_level == "lxmfy":
            try:
                vmod = importlib.import_module("lxmfy.__version__")
                ver = getattr(vmod, "__version__", None)
                if ver:
                    return str(ver)
            except Exception:
                pass

        if top_level == "rns_filesync":
            try:
                module = importlib.import_module("rns_filesync")
                ver = getattr(module, "__version__", None)
                if ver:
                    return str(ver)
            except Exception:
                pass

        embedded_specs: dict[str, tuple[str, str]] = {
            "aiohttp": ("aiohttp", "__version__"),
            "aiohttp-session": ("aiohttp_session", "__version__"),
            "cryptography": ("cryptography", "__version__"),
            "psutil": ("psutil", "__version__"),
            "websockets": ("websockets", "__version__"),
            "bcrypt": ("bcrypt", "__version__"),
            "ply": ("ply", "__version__"),
            "lxmfy": ("lxmfy", "__version__"),
            "rns-filesync": ("rns_filesync", "__version__"),
            "rns_filesync": ("rns_filesync", "__version__"),
        }
        if package_name in embedded_specs:
            mod_name, attr = embedded_specs[package_name]
            try:
                module = importlib.import_module(mod_name)
                ver = getattr(module, attr, None)
                if ver:
                    return str(ver)
            except Exception:
                pass
            if package_name == "ply":
                try:
                    lex = importlib.import_module("ply.lex")
                    ver = getattr(lex, "VERSION", None)
                    if ver:
                        return str(ver)
                except Exception:
                    pass

        return default

    @staticmethod
    def parse_discovery_patterns(value):
        if value is None:
            return []
        if isinstance(value, str):
            value = value.replace("\n", ",")
            return [part.strip() for part in value.split(",") if part.strip()]
        if isinstance(value, (list, tuple)):
            return [str(part).strip() for part in value if str(part).strip()]
        text_value = str(value).strip()
        return [text_value] if text_value else []

    @staticmethod
    def _reticulum_yes_no_preference(value, *, default):
        if value is None or value == "":
            return default
        if isinstance(value, bool):
            return value
        s = str(value).strip().lower()
        if s in ("false", "no", "0", "n", "off"):
            return False
        if s in ("true", "yes", "1", "y", "on"):
            return True
        return default

    @staticmethod
    def _bootstrap_only_request_yes_no(value):
        if value is None or value == "":
            return None
        if isinstance(value, bool):
            return "yes" if value else "no"
        s = str(value).strip().lower()
        if s in ("true", "yes", "1", "y", "on"):
            return "yes"
        if s in ("false", "no", "0", "n", "off"):
            return "no"
        return None

    @staticmethod
    def discovery_filter_candidates(interface):
        if not isinstance(interface, dict):
            return [str(interface)]
        candidates = []
        for key in (
            "name",
            "type",
            "reachable_on",
            "target_host",
            "remote",
            "listen_ip",
            "port",
            "target_port",
            "listen_port",
            "discovery_hash",
            "transport_id",
            "network_id",
            "network_name",
            "ifac_netname",
        ):
            value = interface.get(key)
            if value is not None and value != "":
                candidates.append(str(value))

        host = (
            interface.get("reachable_on")
            or interface.get("target_host")
            or interface.get("remote")
            or interface.get("listen_ip")
        )
        port = (
            interface.get("port")
            or interface.get("target_port")
            or interface.get("listen_port")
        )
        if host and port:
            candidates.append(f"{host}:{port}")
        return candidates

    @staticmethod
    def normalize_discovered_ifac_fields(interfaces):
        """Surface IFAC fields from discovery announces in a frontend-friendly shape.

        RNS publishes IFAC values in discovered interface dicts as
        ifac_netname and ifac_netkey (when the publishing interface
        sets publish_ifac = yes). The Reticulum config file uses
        network_name / passphrase instead. This helper keeps the raw
        RNS keys for backwards compatibility but also exposes the canonical
        config-style aliases (network_name and passphrase) and ensures
        the optional config_entry blob is always a string when present.

        Returns the list with new keys added; missing values become None
        so the frontend can render placeholders consistently.
        """
        if not isinstance(interfaces, list):
            return interfaces
        normalized = []
        for entry in interfaces:
            if not isinstance(entry, dict):
                normalized.append(entry)
                continue
            updated = dict(entry)

            netname = updated.get("ifac_netname")
            netkey = updated.get("ifac_netkey")
            config_entry = updated.get("config_entry")

            if isinstance(netname, bytes):
                try:
                    netname = netname.decode("utf-8")
                except Exception:
                    netname = netname.hex()
            if isinstance(netkey, bytes):
                try:
                    netkey = netkey.decode("utf-8")
                except Exception:
                    netkey = netkey.hex()
            if isinstance(config_entry, bytes):
                try:
                    config_entry = config_entry.decode("utf-8")
                except Exception:
                    config_entry = None

            updated["ifac_netname"] = netname or None
            updated["ifac_netkey"] = netkey or None
            updated["config_entry"] = config_entry or None
            updated["network_name"] = updated["ifac_netname"]
            updated["passphrase"] = updated["ifac_netkey"]
            updated["publish_ifac"] = bool(
                updated["ifac_netname"] or updated["ifac_netkey"],
            )

            # Discovery announces are untrusted mesh data; reject non-finite
            # or out-of-range coordinates before they reach map clients.
            lat = updated.get("latitude")
            lon = updated.get("longitude")
            if lat is not None or lon is not None:
                valid = (
                    isinstance(lat, (int, float))
                    and isinstance(lon, (int, float))
                    and not isinstance(lat, bool)
                    and not isinstance(lon, bool)
                    and math.isfinite(lat)
                    and math.isfinite(lon)
                    and -90.0 <= lat <= 90.0
                    and -180.0 <= lon <= 180.0
                )
                if not valid:
                    updated["latitude"] = None
                    updated["longitude"] = None
            normalized.append(updated)
        return normalized

    def get_lxst_version(self) -> str:
        return self.get_package_version("lxst", getattr(LXST, "__version__", "unknown"))
