"""Extracted mixin for ReticulumMeshChat::handle.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

import asyncio

class HandleMixin:
    # handle data received from websocket client
    async def on_websocket_data_received(self, client, data):
        from meshchatx.src.backend.http.ws.dispatch import dispatch_websocket_data

        await dispatch_websocket_data(self, client, data)

    def _track_rns_link_task(self, client, task: asyncio.Task) -> None:
        bucket = self._rns_link_tasks.get(client)
        if bucket is None:
            bucket = set()
            self._rns_link_tasks[client] = bucket
        bucket.add(task)
        task.add_done_callback(lambda t, c=client: self._untrack_rns_link_task(c, t))

    def _untrack_rns_link_task(self, client, task: asyncio.Task) -> None:
        bucket = self._rns_link_tasks.get(client)
        if not bucket:
            return
        bucket.discard(task)
        if not bucket:
            self._rns_link_tasks.pop(client, None)

    def _cancel_rns_link_tasks_for_client(self, client) -> None:
        bucket = self._rns_link_tasks.pop(client, None)
        if bucket:
            for task in bucket:
                if not task.done():
                    task.cancel()
        stale_keys = [k for k in self._rns_request_receipts if k[0] is client]
        for key in stale_keys:
            self._rns_request_receipts.pop(key, None)

    @staticmethod
    def _rns_link_parse_dest_aspect(data):
        from meshchatx.src.backend.rns_link_manager import _rns_link_parse_dest_aspect

        return _rns_link_parse_dest_aspect(data)

    @staticmethod
    async def _rns_link_send(client, payload):
        from meshchatx.src.backend.rns_link_manager import _rns_link_send

        return await _rns_link_send(client, payload)

    async def _handle_rns_link_open(self, client, data):
        from meshchatx.src.backend.rns_link_manager import _handle_rns_link_open

        return await _handle_rns_link_open(self, client, data)

    async def _handle_rns_link_identify(self, client, data):
        from meshchatx.src.backend.rns_link_manager import _handle_rns_link_identify

        return await _handle_rns_link_identify(self, client, data)

    async def _handle_rns_link_request(self, client, data):
        from meshchatx.src.backend.lifecycle.rns_link_request import (
            handle_rns_link_request,
        )

        return await handle_rns_link_request(self, client, data)

    async def _handle_rns_link_send(self, client, data):
        from meshchatx.src.backend.rns_link_manager import _handle_rns_link_send

        return await _handle_rns_link_send(self, client, data)

    async def _handle_rns_link_close(self, client, data):
        from meshchatx.src.backend.rns_link_manager import _handle_rns_link_close

        return await _handle_rns_link_close(self, client, data)

    async def on_websocket_binary_received(self, client, data: bytes):
        """Optional binary rns.link frames (msgpack). JSON path remains default."""
        if not getattr(client, "_meshchatx_binary_rns_link", False):
            return
        if not data or len(data) < 2:
            return
        try:
            import msgpack
        except ImportError:
            return
        try:
            decoded = msgpack.unpackb(data, raw=False)
        except Exception:
            from meshchatx.src.backend.websocket_runtime import send_ws_error

            await send_ws_error(
                client,
                message="Invalid binary frame",
                code="invalid_binary",
            )
            return
        if isinstance(decoded, dict):
            await self.on_websocket_data_received(client, decoded)

    def _detach_active_session(self, websocket_response) -> bool:
        session_id = getattr(websocket_response, "_meshchatx_session_id", None)
        if not session_id:
            return False
        try:
            delattr(websocket_response, "_meshchatx_session_id")
        except Exception:
            pass
        return self.active_sessions.remove(session_id)
