"""Extracted mixin for ReticulumMeshChat::lxmf_2.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""


class Lxmf2Mixin:
    def _lxmf_sieve_suppresses_notifications(
        self,
        peer_hash: str,
        context=None,
        *,
        message_title=None,
        message_content=None,
    ) -> bool:
        m = self._evaluate_lxmf_sieve_for_peer(
            peer_hash,
            context=context,
            message_title=message_title,
            message_content=message_content,
        )
        if not m:
            return False
        return m.get("action") in ("hide", "ignore", "banish")

    def _lxmf_sieve_hides_peer(
        self,
        peer_hash: str,
        context=None,
        *,
        message_title=None,
        message_content=None,
    ) -> bool:
        m = self._evaluate_lxmf_sieve_for_peer(
            peer_hash,
            context=context,
            message_title=message_title,
            message_content=message_content,
        )
        return bool(m and m.get("action") == "hide")
