"""Extracted mixin for ReticulumMeshChat::lxmf.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""


class LxmfMixin:
    def _lxmf_sieve_message_haystack(
        self,
        message_title: str | bytes | None,
        message_content: str | bytes | None,
    ) -> str | None:
        if message_title is None and message_content is None:
            return None

        def norm(x):
            if x is None:
                return ""
            if isinstance(x, bytes):
                return x.decode("utf-8", errors="replace")
            return str(x)

        t = norm(message_title).strip()
        c = norm(message_content).strip()
        if not t and not c:
            return ""
        return f"{t} {c}".strip()
