"""Extracted mixin for ReticulumMeshChat::mark.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

from aiohttp import WSCloseCode, WSMessage, WSMsgType, web
from aiohttp_session import setup as setup_session
from aiohttp_session.cookie_storage import EncryptedCookieStorage
from meshchatx.src.backend.async_utils import AsyncUtils
from meshchatx.src.backend.demo_mode import (
    auth_bypass_from_env,
    demo_auth_password_from_env,
)
from meshchatx.src.backend.identity_context import IdentityContext
from meshchatx.src.backend.nomadnet_downloader import (
    NomadnetFileDownloader,
    NomadnetPageDownloader,
    clear_all_nomadnet_cached_links,
    drop_cached_link,
    get_cached_active_link,
    nomad_link_identity_kwargs,
)
from meshchatx.src.backend.persistent_log_handler import memory_log_handler
from meshchatx.src.backend.recovery import (
    CrashRecovery,
    HealthMonitor,
    evaluate_startup_memory,
    format_memory_log_line,
)
from meshchatx.src.backend.rns_link_manager import (
    RnsLinkManager,
    clear_all_cached_links,
)
from meshchatx.src.backend.web_audio_bridge import WebAudioBridge
from meshchatx.src.path_utils import (
    get_file_path,
    is_loopback_bind_host,
    is_path_within_dir,
    resolve_log_dir,
    resolve_meshchat_data_roots,
    safe_path_under_dir,
)
from meshchatx.src.ssl_self_signed import generate_ssl_certificate
import RNS
import asyncio
import base64
import bcrypt
import contextlib
import gc
import hashlib
import json
import os
import secrets
import shutil
import ssl
import sys
import threading
import time
import webbrowser
from ..meshchat_shared import _create_reticulum_instance, _resolve_rns_loglevel, _restore_rns_console_logging_after_reticulum_init

class MarkMixin:
    @property
    def storage_path(self):
        return (
            self.current_context.storage_path
            if self.current_context
            else self.storage_dir
        )

    @storage_path.setter
    def storage_path(self, value):
        if self.current_context:
            self.current_context.storage_path = value

    def get_public_path(self, filename=""):
        if self.public_dir_override:
            return os.path.join(self.public_dir_override, filename)
        return get_file_path(os.path.join("public", filename))

    def prepare_for_database_restore(self) -> str | None:
        db_path = self.database_path
        self._teardown_all_contexts_for_reload()
        from meshchatx.src.backend.database.provider import DatabaseProvider

        if DatabaseProvider._instance is not None:
            DatabaseProvider._instance.close_all()
            DatabaseProvider._instance = None
        return db_path

    @staticmethod
    def _schedule_process_restart(delay: float = 1.0) -> None:
        def restart():
            time.sleep(delay)
            try:
                os.execv(sys.executable, [sys.executable, *sys.argv])  # nosec: BAN-B606  # noqa: S606
            except Exception as e:
                print(f"Failed to restart: {e}")
                os._exit(0)

        threading.Thread(target=restart, daemon=True).start()

    def restore_database(self, backup_path, *, relaunch: bool = False):
        # Two concurrent restores would interleave aside/staging moves and
        # corrupt the live database; serialize them.
        with self._restore_lock:
            return self._restore_database_locked(backup_path, relaunch=relaunch)

    def _restore_database_locked(self, backup_path, *, relaunch: bool = False):
        db_path = self.prepare_for_database_restore()
        if not db_path:
            raise RuntimeError("Database path is unknown")
        try:
            from meshchatx.src.backend.database import Database

            db = Database(db_path)
            try:
                result = db.restore_database(backup_path)
            finally:
                db.close_all()
            identity_storage_file = os.path.join(os.path.dirname(db_path), "identity")
            main_identity_file = self.identity_file_path or os.path.join(
                self.storage_dir,
                "identity",
            )
            restored_identity_hash = None
            if os.path.isfile(identity_storage_file):
                try:
                    restored_identity = RNS.Identity.from_file(identity_storage_file)
                    restored_identity_hash = restored_identity.hash.hex()
                except Exception as exc:
                    print(
                        "Restored identity file is invalid; keeping the current "
                        f"identity key: {exc}",
                    )
                else:
                    os.makedirs(os.path.dirname(main_identity_file), exist_ok=True)
                    shutil.copy2(identity_storage_file, main_identity_file)
            final_db_path = db_path
            if restored_identity_hash:
                final_db_path = self._relocate_restored_identity_dir(
                    db_path,
                    restored_identity_hash,
                )
            self._rebaseline_integrity_after_restore(
                final_db_path,
                restored_identity_hash,
            )
        except Exception:
            # Contexts were torn down before the backup was validated. Without
            # re-setup the app stays contextless and every request 503s until
            # a manual restart.
            try:
                if self.identity:
                    self.running = True
                    self.setup_identity(self.identity)
            except Exception as rec_exc:
                print(f"Recovery after failed database restore failed: {rec_exc}")
            raise
        if relaunch:
            self._schedule_process_restart()
        return result

    def _relocate_restored_identity_dir(self, db_path, restored_identity_hash):
        """Move a restored tree into the slot matching its identity.

        Identity storage is keyed by identity hash. A backup zip carries its
        own identity file, so restoring a different identity's backup leaves
        the tree under the old hash while the next launch looks under
        identities/<restored hash> and finds nothing. Relocate the restored
        tree so the restored identity actually finds its data.
        """
        identity_dir = os.path.dirname(db_path)
        db_name = os.path.basename(db_path)
        identities_root = os.path.join(self.storage_dir, "identities")
        if not is_path_within_dir(identity_dir, identities_root):
            return os.path.join(identity_dir, db_name)
        if os.path.basename(identity_dir) == restored_identity_hash:
            return os.path.join(identity_dir, db_name)
        target_dir = os.path.join(identities_root, restored_identity_hash)
        try:
            if os.path.exists(target_dir):
                aside = f"{target_dir}.prerestore-{int(time.time())}"
                os.rename(target_dir, aside)
                print(f"Existing identity dir moved aside to {aside}")
            os.rename(identity_dir, target_dir)
            print(f"Restored tree moved to identity slot {restored_identity_hash}")
            return os.path.join(target_dir, db_name)
        except OSError as exc:
            print(f"Failed to relocate restored identity dir: {exc}")
            return os.path.join(identity_dir, db_name)

    def _mark_network_ready(self) -> None:
        self._network_ready = True
        self._network_degraded = False
        self._ui_ready = True
        self._startup_stage = "ready"
        self._startup_error = None
        self._rns_recovery_actions = []
        self._network_ready_event.set()
        self._schedule_reticulum_signal_handlers()

    def _mark_network_degraded(self, error: str) -> None:
        """Keep HTTP/UI alive when the mesh stack cannot start."""
        self._network_ready = False
        self._network_degraded = True
        self._ui_ready = True
        self._startup_stage = "failed"
        self._startup_error = error
        print(f"Network degraded: {error}", flush=True)

    def _ensure_sideband_telemetry_loop(self) -> None:
        config = self.sideband_plugin_loader.get_config()
        should_run = bool(config.get("service_plugins_enabled"))
        if should_run and not self._sideband_telemetry_running:
            self._sideband_telemetry_running = True

            def telemetry_job():
                while self._sideband_telemetry_running:
                    try:
                        self.sideband_plugin_loader.update_telemetry()
                    except Exception:
                        pass
                    time.sleep(60)

            self._sideband_telemetry_thread = threading.Thread(
                target=telemetry_job,
                daemon=True,
                name="sideband-plugin-telemetry",
            )
            self._sideband_telemetry_thread.start()
        elif not should_run:
            self._sideband_telemetry_running = False

    def _startup_status_payload(self) -> dict:
        demo_fields = {
            "demo_mode": self.demo_mode,
            "auth_page_hint": self.auth_page_hint,
        }
        if self._startup_stage == "failed" or self._startup_error:
            payload = {
                "status": "failed",
                "stage": "failed",
                "network_ready": False,
                "network_degraded": True,
                "ui_ready": True,
                "listen_host": self.listen_host,
                "listen_port": self.listen_port,
                "https_enabled": self.use_https,
                "is_loopback_bind": is_loopback_bind_host(self.listen_host),
                "plugins_enabled": self.plugins_enabled,
                **demo_fields,
                **self._landlock_status_dict(),
                "webtransport": self._webtransport_status_dict(),
            }
            if self._startup_error:
                payload["error"] = self._startup_error
            if self._rns_recovery_actions:
                payload["recovery_actions"] = list(self._rns_recovery_actions)
            return payload
        ready = bool(self._network_ready) and bool(
            self.current_context and self.current_context.running,
        )
        stage = "ready" if ready else (self._startup_stage or "starting")
        return {
            "status": "ok" if ready else "starting",
            "stage": stage,
            "network_ready": ready,
            "network_degraded": False,
            "ui_ready": True if ready else bool(self._ui_ready),
            "listen_host": self.listen_host,
            "listen_port": self.listen_port,
            "https_enabled": self.use_https,
            "is_loopback_bind": is_loopback_bind_host(self.listen_host),
            "plugins_enabled": self.plugins_enabled,
            **demo_fields,
            **self._landlock_status_dict(),
            "webtransport": self._webtransport_status_dict(),
        }

    def wait_until_network_ready(self, timeout: float | None = None) -> bool:
        if (
            self._network_ready
            and self.current_context
            and self.current_context.running
        ):
            return True
        return self._network_ready_event.wait(timeout)

    def start_network_setup_in_background(
        self,
        identity: RNS.Identity | None = None,
    ) -> None:
        pending = identity if identity is not None else self._pending_identity
        if pending is None:
            raise RuntimeError("No identity available for network setup")
        self._pending_identity = pending
        if (
            self._network_ready
            and self.current_context
            and self.current_context.running
        ):
            return
        with self._network_setup_lock:
            if self._network_setup_thread and self._network_setup_thread.is_alive():
                return
            self._set_startup_stage("starting")
            thread = threading.Thread(
                target=self._run_network_setup,
                name="meshchatx-network-setup",
                daemon=True,
            )
            self._network_setup_thread = thread
            thread.start()

    def setup_identity(self, identity: RNS.Identity):
        identity_hash = identity.hash.hex()

        self.running = True

        # Check if we already have a context for this identity
        if identity_hash in self.contexts:
            identity_storage_dir = os.path.join(
                self.storage_dir,
                "identities",
                identity_hash,
            )
            if not os.path.isdir(identity_storage_dir):
                stale = self.contexts.pop(identity_hash)
                with contextlib.suppress(Exception):
                    stale.teardown()
            else:
                self.current_context = self.contexts[identity_hash]
                if not self.current_context.running:
                    self.current_context.setup()
                # Rebind app-level log sinks: keep-alive switches skip the
                # new-context path below, which would leave these pointed at
                # the previously selected identity's database.
                memory_log_handler.set_database(self.current_context.database)
                if hasattr(self, "_crash_recovery") and self._crash_recovery:
                    self._crash_recovery.set_database(self.current_context.database)
                    self._crash_recovery.log_handler = memory_log_handler
                self.web_audio_bridge = WebAudioBridge(
                    self.current_context.telephone_manager,
                    self.current_context.config,
                    force_enabled=self.web_audio_required(),
                )
                if self._network_ready:
                    self._finish_deferred_startup_services()
                self._apply_demo_mode_runtime()
                return

        # Initialize Reticulum if not already done
        if not hasattr(self, "reticulum"):
            self._set_startup_stage("rns")
            self._ensure_reticulum_config()
            rns_loglevel = _resolve_rns_loglevel(self._rns_loglevel_cli)
            self.reticulum = _create_reticulum_instance(
                self.reticulum_config_dir,
                loglevel=rns_loglevel,
            )
            _restore_rns_console_logging_after_reticulum_init(self)
            self.page_node_manager.load_nodes()
            self.plugin_manager.set_app(self)

        # Create new context
        self._set_startup_stage("identity")
        context = IdentityContext(identity, self)
        self.contexts[identity_hash] = context
        self.current_context = context
        context.setup()
        self.web_audio_bridge = WebAudioBridge(
            context.telephone_manager,
            context.config,
            force_enabled=self.web_audio_required(),
        )

        for node in self.page_node_manager.nodes.values():
            if node.running and node.destination:
                self._register_local_page_node_announce(node)

        # Link database to memory log handler
        memory_log_handler.set_database(context.database)

        # Wire crash recovery with DB + log handler for adaptive diagnostics
        if hasattr(self, "_crash_recovery") and self._crash_recovery:
            self._crash_recovery.set_database(context.database)
            self._crash_recovery.log_handler = memory_log_handler

        # Start health monitor if not already running
        if not hasattr(self, "_health_monitor") or self._health_monitor is None:
            self._health_monitor = HealthMonitor(
                log_handler=memory_log_handler,
                app=self,
            )
            self._health_monitor.start()

        if self._network_ready:
            self._finish_deferred_startup_services()

        self._apply_demo_mode_runtime()

    def _apply_demo_mode_runtime(self) -> None:
        if not self.demo_mode:
            return
        ctx = self.current_context
        if not ctx or not ctx.config:
            return
        self.plugins_enabled = False
        ctx.config.privacy_mode_enabled.set(True)
        ctx.config.auto_announce_enabled.set(False)
        if self.auth_enabled_initial:
            ctx.config.auth_enabled.set(True)
        if self.auth_enabled and ctx.config.auth_password_hash.get() is None:
            password = demo_auth_password_from_env()
            password_hash = bcrypt.hashpw(
                password.encode("utf-8"),
                bcrypt.gensalt(),
            ).decode("utf-8")
            ctx.config.auth_password_hash.set(password_hash)

    def _finish_deferred_startup_services(self) -> None:
        """Start non-critical services after network_ready is published."""
        context = self.current_context
        if context is not None:
            try:
                context.setup_deferred_services()
            except Exception as exc:
                print(f"Deferred identity services failed: {exc}", flush=True)
        self._start_deferred_reticulum_services()

    def _start_deferred_reticulum_services(self) -> None:
        if self._reticulum_secondary_started:
            return
        if not hasattr(self, "reticulum"):
            return
        # Mark started only after the attempts run: setting the flag first
        # would leave a mid-run failure permanently unretried.
        try:
            self.page_node_manager.start_all()
            for node in self.page_node_manager.nodes.values():
                if node.running and node.destination:
                    self._register_local_page_node_announce(node)
        except Exception as exc:
            print(f"Deferred page node start failed: {exc}", flush=True)
        if self.plugins_enabled:
            try:
                self.plugin_manager.install_bundled_examples()
            except Exception as exc:
                print(f"Bundled plugin sync failed: {exc}", flush=True)
            try:
                self.plugin_manager.restore_enabled_hooks()
            except Exception as exc:
                print(f"Plugin hook restore failed: {exc}", flush=True)
        try:
            self.sideband_plugin_loader.reload()
            self._ensure_sideband_telemetry_loop()
        except Exception as exc:
            print(f"Sideband plugin loader init failed: {exc}")
        self._reticulum_secondary_started = True

    def _clear_mesh_link_caches(self):
        """Drop process-global mesh links so identity switch cannot reuse sessions."""
        clear_all_cached_links()
        clear_all_nomadnet_cached_links()

    def teardown_identity(self):
        if self.current_context:
            # Do not clear self.running here: per-context loops already exit on
            # ctx.running/session_id, and an app-wide stop would kill loops for
            # other kept-alive contexts whose ctx.running stays True.
            identity_hash = self.current_context.identity_hash
            self.current_context.teardown()
            if identity_hash in self.contexts:
                del self.contexts[identity_hash]
            self.current_context = None
            # The context DB is closed; drop the stale handle so later log
            # emits buffer in memory instead of hitting a dead SQLite file.
            memory_log_handler.set_database(None)
            # Drop Nomad and RNS links that may have identified as the prior identity.
            self._clear_mesh_link_caches()
            self._drop_auto_resend_locks(identity_hash)
            gc.collect()

    def _teardown_all_contexts_for_reload(self):
        # Stop per-identity long-running services before tearing down contexts.
        for identity_hash in list(self.contexts.keys()):
            ctx = self.contexts.get(identity_hash)
            if ctx is None:
                continue
            bot_handler = getattr(ctx, "bot_handler", None)
            if bot_handler is not None:
                with contextlib.suppress(Exception):
                    bot_handler.stop_all()
            with contextlib.suppress(Exception):
                self.stop_local_propagation_node(context=ctx)

        # Stop page node mesh servers before resetting transport state.
        if hasattr(self, "page_node_manager"):
            with contextlib.suppress(Exception):
                self.page_node_manager.teardown()

        for identity_hash in list(self.contexts.keys()):
            ctx = self.contexts.get(identity_hash)
            if ctx is None:
                continue
            with contextlib.suppress(Exception):
                ctx.teardown()

        dropped_identity_hashes = list(self.contexts.keys())
        self.contexts.clear()
        self.current_context = None
        self.running = False
        # Context DBs are closed; stop the log handler from writing to a
        # stale handle during the reload gap.
        memory_log_handler.set_database(None)
        # Same drop as teardown_identity. Reload and zip restore must not keep
        # Nomad or RNS Link sessions from the torn-down identities.
        self._clear_mesh_link_caches()
        for identity_hash in dropped_identity_hashes:
            self._drop_auto_resend_locks(identity_hash)
        gc.collect()

    async def _memory_diag_snapshot_loop(self):
        if not self._mem_diag:
            return
        while self.running and self._mem_diag.enabled:
            try:
                await asyncio.to_thread(self._mem_diag.snapshot)
                n = self._mem_diag.total_snapshots
                if n % 12 == 0:
                    report = await asyncio.to_thread(
                        self._mem_diag.diff_snapshots,
                        top_n=10,
                    )
                    if report:
                        growth = sum(r["size_mib"] for r in report)
                        print(
                            f"[mem_diag] Snapshot #{n}: +{growth:.2f} MiB "
                            f"growth in top {len(report)} sites",
                        )
            except Exception as exc:
                print(f"[mem_diag] Snapshot error: {exc}")
            await asyncio.sleep(300)  # every 5 minutes

    # enables or disables the local lxmf propagation node
    def enable_local_propagation_node(self, enabled: bool = True, context=None):
        ctx = context or self.current_context
        if not ctx or not ctx.message_router:
            return
        try:
            if enabled:
                ctx.message_router.enable_propagation()
            else:
                ctx.message_router.disable_propagation()
        except Exception:
            print(
                f"failed to enable or disable propagation node for {ctx.identity_hash}",
            )

    def stop_local_propagation_node(self, context=None):
        ctx = context or self.current_context
        if not ctx:
            return
        self.enable_local_propagation_node(False, context=ctx)

    def restart_local_propagation_node(self, context=None):
        ctx = context or self.current_context
        if not ctx:
            return
        self.stop_local_propagation_node(context=ctx)
        self.enable_local_propagation_node(True, context=ctx)

    def search_destination_hashes_by_message(self, search_term: str):
        if search_term is None or search_term.strip() == "":
            return set()

        local_hash = self.local_lxmf_destination.hexhash
        search_term = search_term.strip()
        matches = set()

        query_results = self.message_handler.search_messages(local_hash, search_term)

        for message in query_results:
            if message["source_hash"] == local_hash:
                matches.add(message["destination_hash"])
            else:
                matches.add(message["source_hash"])

        # also check custom display names
        custom_names = (
            self.database.announces.get_announces()
        )  # Or more specific if needed
        for announce in custom_names:
            custom_name = self.database.announces.get_custom_display_name(
                announce["destination_hash"],
            )
            if custom_name and search_term.lower() in custom_name.lower():
                matches.add(announce["destination_hash"])

        return matches

    # web server has shutdown, likely ctrl+c, but if we don't do the following, the script never exits
    async def shutdown(self, app):
        # Always flush SQLite first. Signal handlers may have already done this.
        with contextlib.suppress(Exception):
            from meshchatx.src.backend.lifecycle.signal_shutdown import (
                durable_flush_all_databases,
            )

            durable_flush_all_databases(self)

        for identity_hash in list(self.contexts.keys()):
            ctx = self.contexts.get(identity_hash)
            if ctx is None:
                continue
            bh = getattr(ctx, "bot_handler", None)
            if bh is not None:
                with contextlib.suppress(Exception):
                    bh.stop_all()

        if hasattr(self, "page_node_manager"):
            self.page_node_manager.teardown()

        for identity_hash in list(self.contexts.keys()):
            ctx = self.contexts.get(identity_hash)
            if ctx is None:
                continue
            try:
                ctx.teardown()
            except Exception:
                pass
        self.contexts.clear()
        self.current_context = None

        if hasattr(self, "_health_monitor") and self._health_monitor is not None:
            with contextlib.suppress(Exception):
                self._health_monitor.stop()

        if self._mem_diag is not None:
            with contextlib.suppress(Exception):
                self._mem_diag.stop()

        # force close websocket clients (copy: close() may touch the client list)
        for websocket_client in list(self.websocket_clients):
            try:
                await websocket_client.close(code=WSCloseCode.GOING_AWAY)
            except Exception:
                pass

        # stop reticulum
        try:
            RNS.Transport.detach_interfaces()
        except Exception:
            pass

        if hasattr(self, "reticulum") and self.reticulum:
            try:
                self.reticulum.exit_handler()
            except Exception:
                pass

        try:
            RNS.exit()
        except Exception:
            pass

    def _require_identity_context_ready(self):
        """Return an HTTP 503 response when identity/DB is not ready yet."""
        if not self.current_context or not getattr(
            self.current_context,
            "running",
            False,
        ):
            return web.json_response(
                {
                    "message": "Identity context is still starting. Retry shortly.",
                    "stage": self._startup_stage,
                    "network_ready": bool(self._network_ready),
                },
                status=503,
            )
        if self.database is None or self.message_handler is None:
            return web.json_response(
                {
                    "message": "Database is still starting. Retry shortly.",
                    "stage": self._startup_stage,
                    "network_ready": bool(self._network_ready),
                },
                status=503,
            )
        if self.local_lxmf_destination is None:
            return web.json_response(
                {
                    "message": "Local LXMF destination is still starting. Retry shortly.",
                    "stage": self._startup_stage,
                    "network_ready": bool(self._network_ready),
                },
                status=503,
            )
        return None

    def _require_rns_tool_handler(self, handler, tool_name: str):
        """Return 503 when an RNS tool handler is unavailable (e.g. mid-reload)."""
        if handler is None:
            return web.json_response(
                {
                    "message": f"{tool_name} is unavailable while the RNS stack is reloading.",
                    "stage": self._startup_stage,
                    "network_ready": bool(self._network_ready),
                },
                status=503,
            )
        reticulum = getattr(handler, "reticulum", None)
        if reticulum is None and not hasattr(self, "reticulum"):
            return web.json_response(
                {
                    "message": f"{tool_name} is unavailable while the RNS stack is reloading.",
                    "stage": self._startup_stage,
                    "network_ready": bool(self._network_ready),
                },
                status=503,
            )
        return None

    def _encrypted_cookie_storage(self, use_https: bool) -> EncryptedCookieStorage:
        try:
            secret_key_bytes = base64.urlsafe_b64decode(self.session_secret_key + "===")
            if len(secret_key_bytes) < 32:
                secret_key_bytes = secret_key_bytes.ljust(32, b"\0")
            elif len(secret_key_bytes) > 32:
                secret_key_bytes = secret_key_bytes[:32]
        except Exception:
            secret_key_bytes = hashlib.sha256(
                self.session_secret_key.encode("utf-8"),
            ).digest()
        return EncryptedCookieStorage(
            secret_key_bytes,
            secure=use_https,
            httponly=True,
            samesite="Lax",
        )

    def run(self, host, port, launch_browser: bool, enable_https: bool = True):
        # create route table
        routes = web.RouteTableDef()
        (
            bad_request_middleware,
            sqlite_unavailable_middleware,
            auth_middleware,
            mime_type_middleware,
            security_middleware,
            csrf_middleware,
            ip_allowlist_middleware,
            demo_mode_middleware,
        ) = self._define_routes(routes)

        ssl_context = None
        use_https = enable_https
        self.listen_host = host
        self.listen_port = port
        self.use_https = use_https
        if enable_https:
            custom_ssl = bool(self.ssl_cert_path and self.ssl_key_path)
            if custom_ssl:
                cert_path = os.path.abspath(self.ssl_cert_path)
                key_path = os.path.abspath(self.ssl_key_path)
            else:
                cert_dir = os.path.join(self.storage_path, "ssl")
                cert_path = os.path.join(cert_dir, "cert.pem")
                key_path = os.path.join(cert_dir, "key.pem")

            try:
                if custom_ssl:
                    if not os.path.isfile(cert_path) or not os.path.isfile(key_path):
                        msg = f"Custom SSL files not found (cert={cert_path!r}, key={key_path!r})"
                        raise FileNotFoundError(msg)
                    ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
                    ssl_context.load_cert_chain(cert_path, key_path)
                    print(
                        f"HTTPS enabled with custom certificate at {cert_path}",
                        flush=True,
                    )
                else:
                    generate_ssl_certificate(cert_path, key_path)
                    ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
                    ssl_context.load_cert_chain(cert_path, key_path)
                    print(f"HTTPS enabled with certificate at {cert_path}", flush=True)
            except Exception as e:
                if custom_ssl:
                    print(f"Failed to load custom SSL certificate: {e}")
                else:
                    print(f"Failed to generate SSL certificate: {e}")
                print("Falling back to HTTP")
                use_https = False

        # session secret for encrypted cookies (generate once and store in shared storage)
        session_secret_path = os.path.join(self.storage_dir, "session_secret")
        self.session_secret_key = None

        if os.path.exists(session_secret_path):
            try:
                with open(session_secret_path) as f:
                    self.session_secret_key = f.read().strip()
            except Exception as e:
                print(f"Failed to read session secret from {session_secret_path}: {e}")

        if not self.session_secret_key:
            # try to migrate from current identity config if available
            if self.config is not None:
                self.session_secret_key = self.config.auth_session_secret.get()
            if not self.session_secret_key:
                self.session_secret_key = secrets.token_urlsafe(32)

            try:
                with open(session_secret_path, "w") as f:
                    f.write(self.session_secret_key)
            except Exception as e:
                print(f"Failed to write session secret to {session_secret_path}: {e}")

        # ensure it's also in the current config for consistency when identity is ready
        if self.config is not None:
            self.config.auth_session_secret.set(self.session_secret_key)

        # called when web app has started
        async def on_startup(app):
            # remember main event loop
            AsyncUtils.set_main_loop(asyncio.get_event_loop())

            if not self._network_ready:
                self.start_network_setup_in_background()

            # auto launch web browser
            if launch_browser:
                try:
                    protocol = "https" if use_https else "http"
                    webbrowser.open(f"{protocol}://127.0.0.1:{port}")
                except Exception:
                    print("could not open the system web browser")

            # start memory diagnostics periodic snapshot task
            if self._mem_diag and self._mem_diag.enabled:
                self._mem_diag_task = asyncio.create_task(
                    self._memory_diag_snapshot_loop()
                )

            try:
                from meshchatx.src.backend.webtransport_sidecar import (
                    try_start_webtransport_sidecar,
                )

                await try_start_webtransport_sidecar(self)
            except Exception:
                print("webtransport sidecar startup failed (non-fatal)")

        # create and run web app
        app = web.Application(
            client_max_size=1024 * 1024 * 256,
        )  # allow large message exports with embedded attachments

        # setup session storage
        # aiohttp_session.setup must be called before other middlewares that use sessions
        setup_session(
            app,
            self._encrypted_cookie_storage(use_https),
        )

        # add other middlewares
        app.middlewares.extend(
            [
                bad_request_middleware,
                sqlite_unavailable_middleware,
                auth_middleware,
                mime_type_middleware,
                security_middleware,
                csrf_middleware,
                ip_allowlist_middleware,
                demo_mode_middleware,
            ],
        )

        app.add_routes(routes)

        async def robots_txt_handler(_request):
            return web.Response(
                text="User-agent: *\nDisallow: /\n",
                content_type="text/plain; charset=utf-8",
            )

        app.router.add_get("/robots.txt", robots_txt_handler)

        # serve anything else from public folder
        # we use add_static here as it's more robust for serving directories
        public_dir = self.get_public_path()

        # Serve Reticulum docs from user-uploaded storage with a fallback to the
        # bundled offline copy shipped under <public>/reticulum-docs-bundled/current.
        # No remote network fallback exists, so users supply replacements via upload.
        async def reticulum_docs_handler(request):
            dm = self.docs_manager
            if dm is None:
                return web.json_response(
                    {"error": "Documentation unavailable"},
                    status=503,
                )
            path = request.match_info.get("filename", "manual/index.html")
            if not path:
                path = "manual/index.html"
            if path.endswith("/"):
                path += "index.html"

            resolved = dm.find_docs_file(path)
            if resolved is None:
                return web.json_response(
                    {"error": "Documentation not found"},
                    status=404,
                )
            return web.FileResponse(resolved)

        app.router.add_get("/reticulum-docs/{filename:.*}", reticulum_docs_handler)

        dm = self.docs_manager
        if (
            dm
            and dm.meshchatx_docs_dir
            and os.path.exists(dm.meshchatx_docs_dir)
            and not dm.meshchatx_docs_dir.startswith(public_dir)
        ):
            app.router.add_static(
                "/meshchatx-docs/",
                dm.meshchatx_docs_dir,
                name="meshchatx_docs_storage",
                follow_symlinks=True,
            )

        if os.path.exists(public_dir):
            app.router.add_static("/", public_dir, name="static", follow_symlinks=True)
        else:
            print(f"Warning: Static files directory not found at {public_dir}")

        app.on_shutdown.append(
            self.shutdown,
        )  # need to force close websockets and stop reticulum now
        app.on_startup.append(on_startup)

        protocol = "https" if use_https else "http"
        print(f"Starting web server on {protocol}://{host}:{port}", flush=True)

        # Start memory diagnostics if enabled
        if self._memory_diag_enabled:
            from meshchatx.src.backend.diagnostics import MemoryDiagnostics

            self._mem_diag = MemoryDiagnostics()
            self._mem_diag.start()
            print(
                "[mem_diag] Memory diagnostics enabled — "
                "see /api/v1/diagnostics/memory for reports",
            )

        if use_https and ssl_context:
            web.run_app(app, host=host, port=port, ssl_context=ssl_context)
        else:
            web.run_app(app, host=host, port=port)

    def _register_local_page_node_announce(self, node):
        """Insert a synthetic announce for a local page node into the database.

        Ensures the node appears in the NomadNet announce list without RNS loopback.
        """
        ctx = self.current_context
        if not ctx or not ctx.running or not ctx.announce_manager or not ctx.database:
            return
        if not node.destination or not node.identity:
            return
        destination_hash = node.destination.hash
        aspect = "nomadnetwork.node"
        app_data = node.name.encode("utf-8")
        ctx.announce_manager.upsert_announce(
            self.reticulum,
            node.identity,
            destination_hash,
            aspect,
            app_data,
            None,
            force_store=True,
        )
        announce = ctx.database.announces.get_announce_by_hash(destination_hash.hex())
        if announce:
            AsyncUtils.run_async(
                self.websocket_broadcast(
                    json.dumps(
                        {
                            "type": "announce",
                            "announce": self.convert_db_announce_to_dict(announce),
                        },
                    ),
                ),
            )
