"""Extracted mixin for ReticulumMeshChat::on.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

from meshchatx.src.backend.async_utils import AsyncUtils
from meshchatx.src.backend.lxmf_message_fields import (
    LxmfAudioField,
    LxmfFileAttachment,
    LxmfFileAttachmentsField,
    LxmfImageField,
)
from meshchatx.src.backend.memory_pressure import (
    MemoryPressureManager,
    cache_stats,
    prune_announce_timestamps,
    prune_lxmf_incoming_timestamps,
)
from meshchatx.src.backend.meshchat_utils import (
    cancel_inbound_deliveries,
    convert_db_favourite_to_dict,
    convert_propagation_node_state_to_string,
    hex_identifier_to_bytes,
    interval_action_due,
    message_fields_have_attachments,
    normalize_hex_identifier,
    normalize_identity_storage_hash,
    parse_bool_query_param,
    parse_lxmf_display_name,
    parse_lxmf_propagation_node_app_data,
    parse_lxmf_stamp_cost,
    parse_nomadnetwork_node_display_name,
    propagation_sync_idle_like,
    propagation_sync_is_terminal,
)
from meshchatx.src.backend.rrc import protocol as rrc_protocol
from meshchatx.src.backend.sideband_commands import SidebandCommands
from meshchatx.src.backend.telemetry_utils import Telemeter
import LXMF
import RNS
import asyncio
import contextlib
import gc
import hashlib
import json
import sys
import time
from ..meshchat_shared import logger

class OnMixin:
    # Proxy properties for backward compatibility
    @property
    def identity(self):
        return self.current_context.identity if self.current_context else None

    @identity.setter
    def identity(self, value):
        if self.current_context:
            self.current_context.identity = value

    @property
    def database(self):
        return self.current_context.database if self.current_context else None

    @database.setter
    def database(self, value):
        if self.current_context:
            self.current_context.database = value

    @property
    def db(self):
        return self.database

    @db.setter
    def db(self, value):
        self.database = value

    @property
    def config(self):
        return self.current_context.config if self.current_context else None

    @config.setter
    def config(self, value):
        if self.current_context:
            self.current_context.config = value

    @property
    def message_handler(self):
        return self.current_context.message_handler if self.current_context else None

    @message_handler.setter
    def message_handler(self, value):
        if self.current_context:
            self.current_context.message_handler = value

    @property
    def announce_manager(self):
        return self.current_context.announce_manager if self.current_context else None

    @announce_manager.setter
    def announce_manager(self, value):
        if self.current_context:
            self.current_context.announce_manager = value

    @property
    def archiver_manager(self):
        return self.current_context.archiver_manager if self.current_context else None

    @archiver_manager.setter
    def archiver_manager(self, value):
        if self.current_context:
            self.current_context.archiver_manager = value

    @property
    def map_manager(self):
        return self.current_context.map_manager if self.current_context else None

    @map_manager.setter
    def map_manager(self, value):
        if self.current_context:
            self.current_context.map_manager = value

    @property
    def map_overlay_manager(self):
        return (
            self.current_context.map_overlay_manager if self.current_context else None
        )

    @map_overlay_manager.setter
    def map_overlay_manager(self, value):
        if self.current_context:
            self.current_context.map_overlay_manager = value

    @property
    def map_data_manager(self):
        return self.current_context.map_data_manager if self.current_context else None

    @map_data_manager.setter
    def map_data_manager(self, value):
        if self.current_context:
            self.current_context.map_data_manager = value

    @property
    def docs_manager(self):
        return self.current_context.docs_manager if self.current_context else None

    @docs_manager.setter
    def docs_manager(self, value):
        if self.current_context:
            self.current_context.docs_manager = value

    @property
    def repository_server_manager(self):
        return (
            self.current_context.repository_server_manager
            if self.current_context
            else None
        )

    @repository_server_manager.setter
    def repository_server_manager(self, value):
        if self.current_context:
            self.current_context.repository_server_manager = value

    @property
    def nomadnet_manager(self):
        return self.current_context.nomadnet_manager if self.current_context else None

    @nomadnet_manager.setter
    def nomadnet_manager(self, value):
        if self.current_context:
            self.current_context.nomadnet_manager = value

    @property
    def message_router(self):
        return self.current_context.message_router if self.current_context else None

    @message_router.setter
    def message_router(self, value):
        if self.current_context:
            self.current_context.message_router = value

    @property
    def telephone_manager(self):
        return self.current_context.telephone_manager if self.current_context else None

    @telephone_manager.setter
    def telephone_manager(self, value):
        if self.current_context:
            self.current_context.telephone_manager = value

    @property
    def voicemail_manager(self):
        return self.current_context.voicemail_manager if self.current_context else None

    @voicemail_manager.setter
    def voicemail_manager(self, value):
        if self.current_context:
            self.current_context.voicemail_manager = value

    @property
    def ringtone_manager(self):
        return self.current_context.ringtone_manager if self.current_context else None

    @ringtone_manager.setter
    def ringtone_manager(self, value):
        if self.current_context:
            self.current_context.ringtone_manager = value

    @property
    def notification_sound_manager(self):
        return (
            self.current_context.notification_sound_manager
            if self.current_context
            else None
        )

    @notification_sound_manager.setter
    def notification_sound_manager(self, value):
        if self.current_context:
            self.current_context.notification_sound_manager = value

    @property
    def rncp_handler(self):
        return self.current_context.rncp_handler if self.current_context else None

    @rncp_handler.setter
    def rncp_handler(self, value):
        if self.current_context:
            self.current_context.rncp_handler = value

    @property
    def rns_filesync_handler(self):
        return (
            self.current_context.rns_filesync_handler if self.current_context else None
        )

    @rns_filesync_handler.setter
    def rns_filesync_handler(self, value):
        if self.current_context:
            self.current_context.rns_filesync_handler = value

    @property
    def rnsh_manager(self):
        return self.current_context.rnsh_manager if self.current_context else None

    @rnsh_manager.setter
    def rnsh_manager(self, value):
        if self.current_context:
            self.current_context.rnsh_manager = value

    @property
    def rnx_manager(self):
        return self.current_context.rnx_manager if self.current_context else None

    @rnx_manager.setter
    def rnx_manager(self, value):
        if self.current_context:
            self.current_context.rnx_manager = value

    @property
    def rnstatus_handler(self):
        return self.current_context.rnstatus_handler if self.current_context else None

    @rnstatus_handler.setter
    def rnstatus_handler(self, value):
        if self.current_context:
            self.current_context.rnstatus_handler = value

    @property
    def rnpath_handler(self):
        return self.current_context.rnpath_handler if self.current_context else None

    @rnpath_handler.setter
    def rnpath_handler(self, value):
        if self.current_context:
            self.current_context.rnpath_handler = value

    @property
    def rnpath_trace_handler(self):
        return (
            self.current_context.rnpath_trace_handler if self.current_context else None
        )

    @rnpath_trace_handler.setter
    def rnpath_trace_handler(self, value):
        if self.current_context:
            self.current_context.rnpath_trace_handler = value

    @property
    def rnprobe_handler(self):
        return self.current_context.rnprobe_handler if self.current_context else None

    @rnprobe_handler.setter
    def rnprobe_handler(self, value):
        if self.current_context:
            self.current_context.rnprobe_handler = value

    @property
    def bot_handler(self):
        return self.current_context.bot_handler if self.current_context else None

    @bot_handler.setter
    def bot_handler(self, value):
        if self.current_context:
            self.current_context.bot_handler = value

    @property
    def forwarding_manager(self):
        return self.current_context.forwarding_manager if self.current_context else None

    @forwarding_manager.setter
    def forwarding_manager(self, value):
        if self.current_context:
            self.current_context.forwarding_manager = value

    @property
    def rrc_manager(self):
        return self.current_context.rrc_manager if self.current_context else None

    @rrc_manager.setter
    def rrc_manager(self, value):
        if self.current_context:
            self.current_context.rrc_manager = value

    @property
    def rrc_server_manager(self):
        return self.current_context.rrc_server_manager if self.current_context else None

    @rrc_server_manager.setter
    def rrc_server_manager(self, value):
        if self.current_context:
            self.current_context.rrc_server_manager = value

    @property
    def community_interfaces_manager(self):
        return (
            self.current_context.community_interfaces_manager
            if self.current_context
            else None
        )

    @community_interfaces_manager.setter
    def community_interfaces_manager(self, value):
        if self.current_context:
            self.current_context.community_interfaces_manager = value

    @property
    def local_lxmf_destination(self):
        return (
            self.current_context.local_lxmf_destination
            if self.current_context
            else None
        )

    @local_lxmf_destination.setter
    def local_lxmf_destination(self, value):
        if self.current_context:
            self.current_context.local_lxmf_destination = value

    @property
    def database_path(self):
        return self.current_context.database_path if self.current_context else None

    @property
    def _identity_session_id(self):
        return self.current_context.session_id if self.current_context else 0

    @_identity_session_id.setter
    def _identity_session_id(self, value):
        if self.current_context:
            self.current_context.session_id = value

    def reset_password(self):
        """Clear the stored password hash so a new password can be set via the web UI."""
        if self.config.auth_password_hash.get() is not None:
            self.config.auth_password_hash.set(None)
            return True
        return False

    async def _send_rns_reload_status(
        self,
        stage: str,
        message: str,
        *,
        level: str = "info",
        in_progress: bool = True,
    ):
        with contextlib.suppress(Exception):
            await self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "reticulum_reload_status",
                        "stage": stage,
                        "message": message,
                        "level": level,
                        "in_progress": in_progress,
                    },
                ),
            )

    async def announce_loop(self, session_id, context=None):
        ctx = context or self.current_context
        if not ctx:
            return

        gc_counter = 0

        while self.running and ctx.running and ctx.session_id == session_id:
            now = time.time()
            should_announce = interval_action_due(
                ctx.config.auto_announce_enabled.get(),
                ctx.config.last_announced_at.get(),
                ctx.config.auto_announce_interval_seconds.get(),
                now,
            )

            # announce
            if should_announce:
                await self.announce(context=ctx)

                # also announce forwarding aliases if any
                if ctx.forwarding_manager:
                    await asyncio.to_thread(ctx.forwarding_manager.announce_aliases)

            gc_counter += 1
            if gc_counter >= 300:
                gc_counter = 0
                try:
                    await asyncio.to_thread(self.memory_pressure.run_periodic_cleanup)
                except Exception as exc:
                    print(f"[memory_pressure] periodic cleanup error: {exc}")
                # Python 3.14+ incremental GC: with threshold[2]==0 full gen2
                # collections are never scheduled automatically, so force one.
                if sys.version_info >= (3, 14) and gc.get_threshold()[2] == 0:
                    gc.collect(2)
                else:
                    gc.collect()

            await asyncio.sleep(1)

    def on_new_voicemail_received(
        self,
        remote_hash,
        remote_name,
        duration,
        context=None,
    ):
        ctx = context or self.current_context
        if not ctx:
            return
        # Add system notification
        self.database.misc.add_notification(
            notification_type="telephone_voicemail",
            remote_hash=remote_hash,
            title="New Voicemail",
            content=f"New voicemail from {remote_name or remote_hash} ({duration}s)",
        )

        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "new_voicemail",
                        "remote_identity_hash": remote_hash,
                        "remote_identity_name": remote_name,
                        "duration": duration,
                        "timestamp": time.time(),
                    },
                ),
            ),
        )

    def on_telephone_call_established(
        self,
        caller_identity: RNS.Identity,
        context=None,
    ):
        ctx = context or self.current_context
        if not ctx:
            return
        print(f"on_telephone_call_established: {caller_identity.hash.hex()}")
        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "telephone_call_established",
                    },
                ),
            ),
        )

    def on_telephone_initiation_status(self, status, target_hash, context=None):
        ctx = context or self.current_context
        if not ctx:
            return

        target_name = None
        if target_hash:
            try:
                contact = ctx.database.contacts.get_contact_by_identity_hash(
                    target_hash,
                )
                if contact:
                    target_name = contact.name
            except Exception:
                pass

        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "telephone_initiation_status",
                        "status": status,
                        "target_hash": target_hash,
                        "target_name": target_name,
                    },
                ),
            ),
        )

    def on_rrc_change(self, hub, context=None):
        """Broadcast an RRC hub state change to connected clients."""
        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "rrc.change",
                        "hub_hash": hub.hub_hash.hex() if hub is not None else None,
                    },
                ),
            ),
        )

    def _rrc_mention_remote_hash(self, hub_hash_hex, room):

        return f"{hub_hash_hex}:{rrc_protocol.normalize_room(room)}"

    def _maybe_add_rrc_mention_notification(self, hub, msg, context=None):
        if hub is None or not getattr(msg, "mention", False):
            return
        if msg.kind not in ("msg", "action"):
            return
        if not msg.room:
            return
        ctx = context or self.current_context
        if ctx is None:
            return

        room = rrc_protocol.normalize_room(msg.room)
        hub_hash = hub.hub_hash.hex()
        remote_hash = self._rrc_mention_remote_hash(hub_hash, room)
        hub_label = (
            hub.get_display_name()
            if hasattr(hub, "get_display_name")
            else (hub.name or hub_hash[:12])
        )
        nick = msg.nick if isinstance(msg.nick, str) and msg.nick else None
        if not nick and isinstance(msg.src, (bytes, bytearray)):
            nick = msg.src.hex()[:12]
        nick = nick or "Someone"
        preview = (msg.text or "").strip()
        if len(preview) > 180:
            preview = preview[:177] + "..."
        title = f"#{room} · {hub_label}"
        content = f"{nick}: {preview}" if preview else f"{nick} mentioned you"
        ctx.database.misc.dismiss_unviewed_notifications(
            notification_type="rrc_mention",
            remote_hash=remote_hash,
        )
        ctx.database.misc.add_notification(
            "rrc_mention",
            remote_hash,
            title,
            content,
        )

    def _mark_rrc_mention_notifications_viewed(self, hub_hash_hex, room, context=None):
        ctx = context or self.current_context
        if ctx is None or not room:
            return
        with contextlib.suppress(ValueError):
            ctx.database.misc.dismiss_unviewed_notifications(
                notification_type="rrc_mention",
                remote_hash=self._rrc_mention_remote_hash(hub_hash_hex, room),
            )

    def on_rrc_message(self, hub, msg, context=None):
        """Broadcast a new RRC message to connected clients."""
        with contextlib.suppress(Exception):
            self._maybe_add_rrc_mention_notification(hub, msg, context=context)
        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "rrc.message",
                        "hub_hash": hub.hub_hash.hex() if hub is not None else None,
                        "room": msg.room,
                        "message": msg.to_dict(),
                        "mention": bool(getattr(msg, "mention", False)),
                    },
                ),
            ),
        )

    def on_rrc_server_change(self, hub, context=None):
        """Broadcast a hosted RRC hub state change to connected clients."""
        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "rrc.server.change",
                        "hub_id": hub.hub_id if hub is not None else None,
                    },
                ),
            ),
        )

    def on_rnsh_change(self, session, context=None):
        """Broadcast an RNSh session state change to connected clients."""
        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "rnsh.session.change",
                        "session_id": session.session_id
                        if session is not None
                        else None,
                    },
                ),
            ),
        )

    def on_rnsh_output(self, session, chunk, context=None):
        """Broadcast RNSh output chunks to connected clients."""
        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "rnsh.output",
                        "session_id": session.session_id
                        if session is not None
                        else None,
                        "chunk": chunk,
                    },
                ),
            ),
        )

    def on_rnx_change(self, session, context=None):
        """Broadcast an RNX session state change to connected clients."""
        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "rnx.session.change",
                        "session_id": session.session_id
                        if session is not None
                        else None,
                    },
                ),
            ),
        )

    def on_rnx_output(self, session, chunk, context=None):
        """Broadcast RNX output chunks to connected clients."""
        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "rnx.output",
                        "session_id": session.session_id
                        if session is not None
                        else None,
                        "chunk": chunk,
                    },
                ),
            ),
        )

    # auto backup loop
    async def auto_backup_loop(self, session_id, context=None):
        ctx = context or self.current_context
        if not ctx:
            return

        # wait 5 minutes before first backup
        await asyncio.sleep(300)

        while self.running and ctx.running and ctx.session_id == session_id:
            try:
                if not self.emergency:
                    logger.info(
                        "Performing scheduled auto-backup for %s...",
                        ctx.identity_hash,
                    )
                    max_count = ctx.config.backup_max_count.get()
                    ctx.database.backup_database(ctx.storage_path, max_count=max_count)
            except Exception:
                logger.exception("Auto-backup failed")

            # Sleep for 12 hours
            await asyncio.sleep(12 * 3600)

    async def local_message_retention_loop(self, session_id, context=None):
        from meshchatx.src.backend import local_message_retention as lmr

        ctx = context or self.current_context
        if not ctx:
            return
        await asyncio.sleep(lmr.LOCAL_RETENTION_STARTUP_GRACE_SECONDS)
        while self.running and ctx.running and ctx.session_id == session_id:
            try:
                if not ctx.config.local_message_auto_delete_enabled.get():
                    await asyncio.sleep(300)
                    continue
                now = time.time()
                if not interval_action_due(
                    True,
                    ctx.config.local_message_auto_delete_last_run_at.get(),
                    lmr.RETENTION_CHECK_INTERVAL_SECONDS,
                    now,
                ):
                    await asyncio.sleep(60)
                    continue
                v = ctx.config.local_message_auto_delete_value.get() or 30
                u = ctx.config.local_message_auto_delete_unit.get() or "days"
                if ctx.message_router is not None:

                    def _cancel(h):
                        try:
                            ctx.message_router.cancel_outbound(h)
                        except Exception:
                            pass

                else:
                    _cancel = None
                lmr.apply_local_message_retention(
                    ctx.database.messages,
                    _cancel,
                    value=int(v),
                    unit=str(u),
                    now=now,
                )
                ctx.config.local_message_auto_delete_last_run_at.set(int(now))
            except Exception as e:
                print(f"local_message_retention_loop failed: {e}")
            await asyncio.sleep(60)

    async def telemetry_tracking_loop(self, session_id, context=None):
        ctx = context or self.current_context
        if not ctx:
            return

        while self.running and ctx.running and ctx.session_id == session_id:
            try:
                # Only run if telemetry is enabled globally
                if not ctx.config.telemetry_enabled.get():
                    await asyncio.sleep(60)
                    continue

                # Get all tracked peers
                tracked_peers = ctx.database.telemetry.get_tracked_peers()
                now = time.time()

                for peer in tracked_peers:
                    dest_hash = peer["destination_hash"]
                    interval = peer.get("interval_seconds", 60)
                    last_req = peer.get("last_request_at")

                    if last_req is None or now - last_req >= interval:
                        print(f"Sending telemetry request to tracked peer: {dest_hash}")
                        # Send telemetry request
                        await self.send_message(
                            destination_hash=dest_hash,
                            content="",
                            commands=[{SidebandCommands.TELEMETRY_REQUEST: 0}],
                            delivery_method="opportunistic",
                            no_display=False,
                            context=ctx,
                        )
                        # Update last request time
                        ctx.database.telemetry.update_last_request_at(dest_hash, now)

            except Exception as e:
                print(f"Telemetry tracking loop error: {e}")

            # Check every 10 seconds
            await asyncio.sleep(10)

    # handle announcing
    async def announce(self, context=None):
        if self.demo_mode:
            return
        ctx = context or self.current_context
        if not ctx:
            return

        # update last announced at timestamp
        ctx.config.last_announced_at.set(int(time.time()))

        # send announce for lxmf (ensuring name is updated before announcing)
        ctx.local_lxmf_destination.display_name = ctx.config.display_name.get()
        ctx.message_router.announce(destination_hash=ctx.local_lxmf_destination.hash)

        # send announce for local propagation node (if enabled)
        if ctx.config.lxmf_local_propagation_node_enabled.get():
            ctx.message_router.announce_propagation_node()

        # send announce for telephone (can be disabled to reduce unsolicited
        # incoming telephony link attempts from public lxst.telephony announces)
        if ctx.config.telephone_announce_enabled.get():
            ctx.telephone_manager.announce(display_name=ctx.config.display_name.get())

        # tell websocket clients we just announced
        await self.send_announced_to_websocket_clients(context=ctx)

    def _broadcast_to_websocket_clients(self, payload: dict) -> None:
        """Thread-safe fire-and-forget broadcast from RNS callback threads."""
        try:
            AsyncUtils.run_async(self.websocket_broadcast(json.dumps(payload)))
        except Exception as e:
            print(f"websocket broadcast failed: {e}")

    async def _websocket_broadcast_coalesced(self, payload: dict) -> None:
        await self.websocket_broadcast(payload, _skip_coalesce=True)

    async def websocket_broadcast(self, data, *, _skip_coalesce: bool = False):
        from meshchatx.src.backend import websocket_runtime

        return await websocket_runtime.broadcast_to_websocket_clients(
            self,
            data,
            _skip_coalesce=_skip_coalesce,
        )

    async def send_active_sessions_to_websocket_clients(self):
        payload = self.get_active_sessions_payload()
        payload["type"] = "app.sessions.updated"
        await self.websocket_broadcast(json.dumps(payload))

    # broadcasts to all websocket clients that we just announced
    async def send_announced_to_websocket_clients(self, context=None):
        ctx = context or self.current_context
        if not ctx:
            return
        await self.websocket_broadcast(
            json.dumps(
                {
                    "type": "announced",
                    "identity_hash": ctx.identity_hash,
                    "last_announced_at": ctx.config.last_announced_at.get(),
                },
            ),
        )

    async def _broadcast_blocked_destinations(self):
        try:
            blocked = self.database.misc.get_blocked_destinations()
            blocked_list = [
                {
                    "destination_hash": b["destination_hash"],
                    "created_at": b["created_at"],
                }
                for b in blocked
            ]
            await self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "blocked_destinations",
                        "blocked_destinations": blocked_list,
                    },
                ),
            )
        except Exception as e:
            print(f"_broadcast_blocked_destinations: failed: {e}")

    def _broadcast_announce_event(self, announce_dict):
        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "announce",
                        "announce": announce_dict,
                    },
                ),
            ),
        )

    def check_spam_keywords(self, title: str, content: str, context=None) -> bool:
        """Return whether title/content match configured spam keywords."""
        ctx = context or self.current_context
        if not ctx or not ctx.database:
            return False
        try:
            return ctx.database.misc.check_spam_keywords(title, content)
        except Exception:
            return False

    def _apply_lxmf_flood_stamp_cost(self, cost: int, context=None) -> None:
        """Apply the given inbound stamp cost for flood protection and re-announce."""
        ctx = context or self.current_context
        if not ctx or not ctx.message_router or not ctx.local_lxmf_destination:
            return
        cost = max(0, min(254, cost))
        if cost < 1:
            cost = 0
        ctx.config.lxmf_inbound_stamp_cost.set(cost)
        ctx.message_router.set_inbound_stamp_cost(
            ctx.local_lxmf_destination.hash,
            cost,
        )
        if cost > 0:
            ctx.message_router.enforce_stamps()
        elif hasattr(ctx.message_router, "ignore_stamps"):
            ctx.message_router.ignore_stamps()
        try:
            ctx.local_lxmf_destination.display_name = ctx.config.display_name.get()
            ctx.message_router.announce(
                destination_hash=ctx.local_lxmf_destination.hash,
            )
        except Exception as e:
            print(f"_apply_lxmf_flood_stamp_cost: re-announce failed: {e}")

    def _check_lxmf_flood_protection(self, context=None) -> None:
        """Check incoming LXMF message rate and auto-adjust stamp cost if flooding."""
        ctx = context or self.current_context
        if not ctx or not ctx.config:
            return
        if not ctx.config.lxmf_flood_protection_enabled.get():
            return
        # Do not interfere when block strangers is active (it uses max stamp)
        if ctx.config.block_all_from_strangers.get():
            return

        with self._lxmf_flood_lock:
            now = time.time()
            self._lxmf_incoming_timestamps = prune_lxmf_incoming_timestamps(
                self._lxmf_incoming_timestamps,
                now=now,
            )
            msgs_per_minute = len(
                [t for t in self._lxmf_incoming_timestamps if now - t <= 60.0],
            )

            threshold = ctx.config.lxmf_flood_threshold_per_minute.get()
            max_cost = ctx.config.lxmf_flood_max_stamp_cost.get()
            current_cost = ctx.config.lxmf_inbound_stamp_cost.get()
            current_cost = max(current_cost, 0)

            # Determine base cost (the normal non-flood cost)
            if self._flood_protection_current_cost is not None:
                base_cost = self._flood_protection_current_cost
            else:
                base_cost = current_cost

            if msgs_per_minute > threshold:
                # Flood detected: bump stamp cost
                new_cost = min(current_cost + 2, max_cost)
                if new_cost != current_cost:
                    print(
                        f"LXMF flood detected: {msgs_per_minute} msg/min "
                        f"(threshold {threshold}). Raising stamp cost from "
                        f"{current_cost} to {new_cost}.",
                    )
                    if self._flood_protection_current_cost is None:
                        self._flood_protection_current_cost = base_cost
                    self._flood_protection_last_bump_time = now
                    self._apply_lxmf_flood_stamp_cost(new_cost, context=ctx)
            elif current_cost > base_cost:
                cooldown = ctx.config.lxmf_flood_cooldown_seconds.get()
                if now - self._flood_protection_last_bump_time > cooldown:
                    # Step down by 1 toward base cost
                    new_cost = max(current_cost - 1, base_cost)
                    if new_cost != current_cost:
                        print(
                            f"LXMF flood subsided: {msgs_per_minute} msg/min. "
                            f"Lowering stamp cost from {current_cost} to {new_cost}.",
                        )
                        self._apply_lxmf_flood_stamp_cost(new_cost, context=ctx)
                    if new_cost == base_cost:
                        self._flood_protection_current_cost = None
                        self._flood_protection_last_bump_time = 0

    async def lxmf_flood_protection_cooldown_loop(self, session_id, context=None):
        """Background loop to step down flood protection stamp cost during quiet periods."""
        ctx = context or self.current_context
        if not ctx:
            return
        await asyncio.sleep(60)
        while self.running and ctx.running and ctx.session_id == session_id:
            try:
                self._check_lxmf_flood_protection(context=ctx)
            except Exception as e:
                print(f"lxmf_flood_protection_cooldown_loop error: {e}")
            await asyncio.sleep(30)

    # upserts the provided announce to the database
    # handle sending an lxmf message to reticulum
    async def send_message(
        self,
        destination_hash: str,
        content: str,
        image_field: LxmfImageField = None,
        audio_field: LxmfAudioField = None,
        file_attachments_field: LxmfFileAttachmentsField = None,
        telemetry_data: bytes | None = None,
        commands: list | None = None,
        delivery_method: str | None = None,
        title: str = "",
        sender_identity_hash: str | None = None,
        reply_to_hash: str | None = None,
        reply_quoted_content: str | None = None,
        reaction_to_hash: str | None = None,
        reaction_emoji: str | None = None,
        app_extensions: dict | None = None,
        no_display: bool = False,
        context=None,
    ) -> LXMF.LXMessage:
        from meshchatx.src.backend.lifecycle.lxmf_send import send_lxmf_message

        return await send_lxmf_message(
            self,
            destination_hash,
            content,
            image_field,
            audio_field,
            file_attachments_field,
            telemetry_data,
            commands,
            delivery_method,
            title,
            sender_identity_hash,
            reply_to_hash,
            reply_quoted_content,
            reaction_to_hash,
            reaction_emoji,
            app_extensions,
            no_display,
            context,
        )

    async def send_reaction(
        self,
        destination_hash: str,
        target_message_hash: str,
        emoji: str,
        context=None,
    ) -> LXMF.LXMessage:
        ctx = context or self.current_context
        if not ctx:
            raise RuntimeError("No identity context available for sending reaction")
        return await self.send_message(
            destination_hash=destination_hash,
            content="",
            delivery_method="opportunistic",
            reaction_to_hash=target_message_hash,
            reaction_emoji=emoji,
            context=context,
        )

    # get hash of current icon appearance configuration
    def get_current_icon_hash(self, context=None):
        ctx = context or self.current_context
        if not ctx:
            return None

        name = ctx.config.lxmf_user_icon_name.get()
        fg = ctx.config.lxmf_user_icon_foreground_colour.get()
        bg = ctx.config.lxmf_user_icon_background_colour.get()

        if not all([name, fg, bg]):
            return None

        data = f"{name}|{fg}|{bg}"
        return hashlib.sha256(data.encode()).hexdigest()

    def _resolve_location_for_telemetry(self):
        """Return coords for mesh telemetry auto-reply, or (None, None).

        Only explicit manual coordinates may be answered over LXMF. Browser
        geolocation is client-side only. Map default center must never be
        shipped as if it were the operator's location.
        """
        location_source = self.config.location_source.get()
        if location_source == "manual":
            lat = self.config.location_manual_lat.get()
            lon = self.config.location_manual_lon.get()
            return lat, lon
        return None, None

    def handle_telemetry_request(self, to_addr_hash: str):
        lat, lon = self._resolve_location_for_telemetry()

        if lat is None or lon is None:
            print(
                f"Cannot respond to telemetry request from {to_addr_hash}: No location set",
            )
            return

        try:
            location = {
                "latitude": float(lat),
                "longitude": float(lon),
                "altitude": 0,
                "speed": 0,
                "bearing": 0,
                "accuracy": 0,
                "last_update": int(time.time()),
            }

            telemetry_data = Telemeter.pack(location=location)

            AsyncUtils.run_async(
                self.send_message(
                    destination_hash=to_addr_hash,
                    content="",
                    telemetry_data=telemetry_data,
                    delivery_method="opportunistic",
                    no_display=False,
                ),
            )
        except Exception as e:
            print(f"Failed to respond to telemetry request: {e}")
