"""Extracted mixin for ReticulumMeshChat::on_2.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

import RNS

class On2Mixin:
    # handle receiving a new audio call
    def on_incoming_telephone_call(self, caller_identity: RNS.Identity, context=None):
        from meshchatx.src.backend.lifecycle.telephone_call_events import (
            on_incoming_telephone_call,
        )

        return on_incoming_telephone_call(self, caller_identity, context)
