"""Extracted mixin for ReticulumMeshChat::on_3.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

import RNS

class On3Mixin:
    def on_telephone_call_ended(self, caller_identity: RNS.Identity, context=None):
        from meshchatx.src.backend.lifecycle.telephone_call_events import (
            on_telephone_call_ended,
        )

        return on_telephone_call_ended(self, caller_identity, context)
