"""Extracted mixin for ReticulumMeshChat::on_4.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""


class On4Mixin:
    def _on_rns_link_broadcast(self, payload: dict) -> None:
        from meshchatx.src.backend.rns_link_manager import _on_rns_link_broadcast

        return _on_rns_link_broadcast(self, payload)
