"""Extracted mixin for ReticulumMeshChat::on_5.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

from meshchatx.src.backend.async_utils import AsyncUtils
from meshchatx.src.backend.lxmf_utils import (
    compute_lxmf_conversation_unread_from_latest_row,
    convert_db_lxmf_message_to_dict,
    convert_lxmf_message_to_dict,
    convert_lxmf_method_to_string,
    convert_lxmf_state_to_string,
    is_lxmf_outbound_progress_terminal,
    is_user_facing_lxmf_payload,
    lxmf_sidebar_preview_for_conversation_latest_row,
)
from meshchatx.src.backend.memory_pressure import (
    MemoryPressureManager,
    cache_stats,
    prune_announce_timestamps,
    prune_lxmf_incoming_timestamps,
)
from meshchatx.src.backend.meshchat_utils import (
    cancel_inbound_deliveries,
    convert_db_favourite_to_dict,
    convert_propagation_node_state_to_string,
    hex_identifier_to_bytes,
    interval_action_due,
    message_fields_have_attachments,
    normalize_hex_identifier,
    normalize_identity_storage_hash,
    parse_bool_query_param,
    parse_lxmf_display_name,
    parse_lxmf_propagation_node_app_data,
    parse_lxmf_stamp_cost,
    parse_nomadnetwork_node_display_name,
    propagation_sync_idle_like,
    propagation_sync_is_terminal,
)
from meshchatx.src.backend.telemetry_utils import Telemeter
import LXMF
import RNS
import asyncio
import base64
import contextlib
import json
import time
from ..meshchat_shared import logger

class On5Mixin:
    # returns a dictionary of config
    def get_config_dict(self, context=None):
        from meshchatx.src.backend.lifecycle.config_dict import build_config_dict

        return build_config_dict(self, context=None)

    def get_name_for_identity_hash(self, identity_hash: str):
        id_norm = normalize_hex_identifier(identity_hash) if identity_hash else ""
        # 1. try recall identity and calculate lxmf destination hash
        identity = self.recall_identity(identity_hash)
        if identity is not None:
            # get lxmf.delivery destination hash
            lxmf_destination_hash = RNS.Destination.hash(
                identity,
                "lxmf",
                "delivery",
            ).hex()

            # use custom name if available
            custom_name = self.database.announces.get_custom_display_name(
                lxmf_destination_hash,
            )
            if custom_name is not None:
                return custom_name

            # use lxmf name if available
            lxmf_name = self.get_lxmf_conversation_name(
                lxmf_destination_hash,
                default_name=None,
            )
            if lxmf_name is not None:
                return lxmf_name

        # 2. if identity recall failed, or we couldn't find a name for the calculated hash
        # try to look up an lxmf.delivery announce with this identity_hash in the database
        lookup_hash = id_norm or identity_hash
        announces = self.database.announces.get_filtered_announces(
            aspect="lxmf.delivery",
            identity_hash=lookup_hash,
            limit=5,
        )
        if announces:
            for announce in announces:
                ann_id = announce.get("identity_hash") or ""
                if ann_id and normalize_hex_identifier(ann_id) == id_norm:
                    lxmf_destination_hash = announce["destination_hash"]

                    # check custom name for this hash
                    custom_name = self.database.announces.get_custom_display_name(
                        lxmf_destination_hash,
                    )
                    if custom_name is not None:
                        return custom_name

                    # check lxmf name from app_data
                    if announce["app_data"] is not None:
                        lxmf_name = parse_lxmf_display_name(
                            app_data_base64=announce["app_data"],
                            default_value=None,
                        )
                        if lxmf_name is not None:
                            return lxmf_name

        # couldn't find a name for this identity
        return None

    # recall identity from reticulum or database
    def get_lxmf_destination_hash_for_identity_hash(self, identity_hash: str):
        id_norm = normalize_hex_identifier(identity_hash) if identity_hash else ""
        identity = self.recall_identity(identity_hash)
        if identity is not None:
            try:
                return RNS.Destination.hash(identity, "lxmf", "delivery").hex()
            except Exception:
                pass

        if self.database is None:
            return None

        # fallback to announces
        lookup_hash = id_norm or identity_hash
        announces = self.database.announces.get_filtered_announces(
            aspect="lxmf.delivery",
            identity_hash=lookup_hash,
            limit=5,
        )
        if announces:
            for announce in announces:
                ann_id = announce.get("identity_hash") or ""
                if ann_id and normalize_hex_identifier(ann_id) == id_norm:
                    return announce["destination_hash"]
        return None

    def get_lxst_telephony_hash_for_identity_hash(self, identity_hash: str):
        id_norm = normalize_hex_identifier(identity_hash) if identity_hash else ""
        lookup_hash = id_norm or identity_hash

        if self.database is not None:
            announces = self.database.announces.get_filtered_announces(
                aspect="lxst.telephony",
                identity_hash=lookup_hash,
                limit=5,
            )
            if announces:
                for announce in announces:
                    ann_id = announce.get("identity_hash") or ""
                    if ann_id and normalize_hex_identifier(ann_id) == id_norm:
                        return announce.get("destination_hash")

        # Fallback: derive from identity if available (same identity, different aspect)
        identity = self.recall_identity(identity_hash)
        if identity is not None:
            try:
                return RNS.Destination.hash(identity, "lxst", "telephony").hex()
            except Exception:
                return None
        return None

    def recall_identity(self, hash_hex: str) -> RNS.Identity | None:
        try:
            if not hash_hex or not isinstance(hash_hex, str):
                return None

            stripped = hash_hex.strip()
            canonical = normalize_hex_identifier(stripped)

            # 1. try reticulum recall (works for both identity and destination hashes)
            hash_bytes = hex_identifier_to_bytes(stripped)
            if hash_bytes:
                identity = RNS.Identity.recall(hash_bytes)
                if identity:
                    return identity

            # 2. try database lookup
            # lookup by destination hash first
            announce = self.database.announces.get_announce_by_hash(stripped)
            if not announce and canonical:
                announce = self.database.announces.get_announce_by_hash(canonical)
            if announce:
                announce = dict(announce)

            if not announce:
                # lookup by identity hash
                search_term = canonical if len(canonical) >= 8 else stripped
                results = self.database.announces.get_filtered_announces(
                    search_term=search_term,
                )
                if results:
                    # find first one with a public key
                    for res in results:
                        res_dict = dict(res)
                        if res_dict.get("identity_public_key"):
                            announce = res_dict
                            break

            if announce and announce.get("identity_public_key"):
                public_key = base64.b64decode(announce["identity_public_key"])
                identity = self._identity_from_public_key_bytes(public_key)
                if identity is not None:
                    return identity

        except Exception as e:
            print(f"Error recalling identity for {hash_hex}: {type(e).__name__}: {e!r}")

        return None

    @staticmethod
    def _identity_from_public_key_bytes(public_key: bytes) -> RNS.Identity | None:
        """Load an RNS Identity from raw public-key bytes.

        Identity.load_public_key is documented as returning True/False, but
        current RNS releases return None on both success and failure. Treat
        a non-None identity.pub (and a computed hash) as success.
        """
        if not public_key:
            return None
        identity = RNS.Identity(create_keys=False)
        try:
            identity.load_public_key(public_key)
        except Exception:
            return None
        if getattr(identity, "pub", None) is None:
            return None
        if not getattr(identity, "hash", None):
            return None
        return identity

    # convert database announce to a dictionary
    def _batch_convert_announces_to_api_dicts(
        self,
        results,
        aspect=None,
        include_hops=True,
    ):
        """Batch-convert announce rows using prefetched icons and custom names."""
        from meshchatx.src.backend.lifecycle.announce_convert import (
            batch_convert_announces_to_api_dicts,
        )

        return batch_convert_announces_to_api_dicts(
            self, results, aspect=aspect, include_hops=include_hops
        )

    def convert_db_announce_to_dict(self, announce):
        # convert to dict if it's a sqlite3.Row
        from meshchatx.src.backend.lifecycle.announce_convert import (
            convert_db_announce_to_dict as _convert_db_announce_to_dict,
        )

        return _convert_db_announce_to_dict(self, announce)

    def on_lxmf_delivery(self, lxmf_message: LXMF.LXMessage, context=None):
        from meshchatx.src.backend.lifecycle.lxmf_delivery import handle_lxmf_delivery

        return handle_lxmf_delivery(self, lxmf_message, context)

    def handle_forwarding(self, lxmf_message: LXMF.LXMessage, context=None):
        from meshchatx.src.backend.lifecycle.lxmf_forwarding import handle_forwarding

        return handle_forwarding(self, lxmf_message, context)

    def _merge_stored_path_fields_from_db(self, ctx, msg_hash_hex, msg_dict):
        try:
            row = ctx.database.messages.get_lxmf_message_by_hash(msg_hash_hex)
            if not row:
                return

            def _scalar_row_value(key):
                try:
                    if hasattr(row, "get"):
                        v = row.get(key)
                    elif hasattr(row, "keys") and key in row.keys():
                        v = row[key]
                    else:
                        return None
                except Exception:
                    return None
                if isinstance(v, (bool, int, float, str)):
                    return v
                return None

            hops = _scalar_row_value("path_hops_at_send")
            if hops is not None:
                msg_dict["path_hops_at_send"] = hops
            iface = _scalar_row_value("path_interface_at_send")
            if iface is not None:
                msg_dict["path_interface_at_send"] = iface
            pfm = _scalar_row_value("path_finding_measure")
            if pfm is not None:
                msg_dict["path_finding_measure"] = pfm
            prh = _scalar_row_value("path_row_hash_hex")
            if prh is not None:
                msg_dict["path_row_hash_hex"] = prh
        except Exception:
            pass

    def _reticulum_path_hops_and_interface_to_identity(self, ctx, identity_hash_bytes):
        if not identity_hash_bytes:
            return None, None
        try:
            destination_hash = (
                identity_hash_bytes
                if isinstance(identity_hash_bytes, (bytes, bytearray))
                else bytes.fromhex(str(identity_hash_bytes))
            )
        except Exception:
            return None, None
        destination_hash_hex = destination_hash.hex()
        local_hashes: set[str] = set()
        with contextlib.suppress(Exception):
            if ctx and ctx.identity:
                local_hashes.add(ctx.identity.hash.hex())
        with contextlib.suppress(Exception):
            if self.local_lxmf_destination is not None:
                local_hashes.add(self.local_lxmf_destination.hash.hex())
        with contextlib.suppress(Exception):
            if ctx and ctx.message_router:
                pdest = ctx.message_router.propagation_destination
                if pdest is not None and getattr(pdest, "hash", None):
                    local_hashes.add(pdest.hash.hex())

        if destination_hash_hex in local_hashes:
            return 0, "Local"
        if not RNS.Transport.has_path(destination_hash):
            return None, None
        hops = RNS.Transport.hops_to(destination_hash)
        next_hop_bytes = None
        if hasattr(self, "reticulum") and self.reticulum:
            next_hop_bytes = self.reticulum.get_next_hop(destination_hash)
        if next_hop_bytes is None:
            return None, None
        iface = (
            self.reticulum.get_next_hop_if_name(destination_hash)
            if hasattr(self, "reticulum") and self.reticulum
            else None
        )
        return hops, iface

    def _maybe_store_path_at_send_for_lxmf(self, ctx, lxmf_message):
        try:
            msg_hash = lxmf_message.hash.hex()
            row = ctx.database.messages.get_lxmf_message_by_hash(msg_hash)
            if not row or row.get("path_hops_at_send") is not None:
                return
            if getattr(lxmf_message, "incoming", False):
                dest_bytes = lxmf_message.source_hash
            else:
                dest_bytes = lxmf_message.destination_hash
            hops, iface = self._reticulum_path_hops_and_interface_to_identity(
                ctx,
                dest_bytes,
            )
            if hops is None:
                return
            ctx.database.messages.set_lxmf_message_path_at_send_if_unset(
                msg_hash,
                hops,
                iface,
            )
        except Exception:
            pass

    def on_lxmf_sending_state_updated(self, lxmf_message, context=None):
        ctx = context or self.current_context
        if not ctx or not ctx.database:
            return

        progress_pct = round(lxmf_message.progress * 100, 2)
        rssi = lxmf_message.rssi
        snr = lxmf_message.snr
        quality = lxmf_message.q
        if self.reticulum:
            if rssi is None:
                rssi = self.reticulum.get_packet_rssi(lxmf_message.hash)
            if snr is None:
                snr = self.reticulum.get_packet_snr(lxmf_message.hash)
            if quality is None:
                quality = self.reticulum.get_packet_q(lxmf_message.hash)

        ctx.database.messages.update_lxmf_message_state(
            message_hash=lxmf_message.hash.hex(),
            state=convert_lxmf_state_to_string(lxmf_message),
            progress=progress_pct,
            delivery_attempts=lxmf_message.delivery_attempts,
            next_delivery_attempt_at=getattr(
                lxmf_message,
                "next_delivery_attempt",
                None,
            ),
            rssi=rssi,
            snr=snr,
            quality=quality,
            method=convert_lxmf_method_to_string(lxmf_message),
        )
        self._maybe_store_path_at_send_for_lxmf(ctx, lxmf_message)

        msg_dict = convert_lxmf_message_to_dict(
            lxmf_message,
            include_attachments=False,
            reticulum=self.reticulum,
            message_router=ctx.message_router,
        )
        self._merge_stored_path_fields_from_db(ctx, lxmf_message.hash.hex(), msg_dict)

        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "lxmf_message_state_updated",
                        "lxmf_message": msg_dict,
                    },
                ),
            ),
        )

    # handle delivery failed for an outbound lxmf message
    def on_lxmf_sending_failed(self, lxmf_message, context=None):
        ctx = context if context is not None else self.current_context
        # check if this failed message should fall back to sending via a propagation node
        if (
            lxmf_message.state == LXMF.LXMessage.FAILED
            and hasattr(lxmf_message, "try_propagation_on_fail")
            and lxmf_message.try_propagation_on_fail
        ):
            self.send_failed_message_via_propagation_node(lxmf_message, context=ctx)

        # update state
        self.on_lxmf_sending_state_updated(lxmf_message, context=ctx)

    # sends a previously failed message via a propagation node
    def send_failed_message_via_propagation_node(
        self,
        lxmf_message: LXMF.LXMessage,
        context=None,
    ):
        ctx = context or self.current_context
        if not ctx:
            return

        # reset internal message state
        lxmf_message.packed = None
        lxmf_message.delivery_attempts = 0
        if hasattr(lxmf_message, "next_delivery_attempt"):
            del lxmf_message.next_delivery_attempt

        # this message should now be sent via a propagation node
        lxmf_message.desired_method = LXMF.LXMessage.PROPAGATED
        lxmf_message.try_propagation_on_fail = False

        # resend message
        source_hash = lxmf_message.source_hash.hex()
        router = ctx.message_router
        if (
            ctx.forwarding_manager
            and source_hash in ctx.forwarding_manager.forwarding_routers
        ):
            router = ctx.forwarding_manager.forwarding_routers[source_hash]
        router.handle_outbound(lxmf_message)

    # upserts the provided lxmf message to the database
    def _is_self_lxmf_destination(self, destination_hash: str, context=None) -> bool:
        """True when destination_hash refers to this identity's own LXMF peer."""
        ctx = context or self.current_context
        if not ctx or not ctx.local_lxmf_destination:
            return False
        norm_dest = normalize_hex_identifier(destination_hash)
        if not norm_dest:
            return False
        local_lxmf = normalize_hex_identifier(ctx.local_lxmf_destination.hexhash)
        if norm_dest == local_lxmf:
            return True
        if ctx.identity:
            local_id = normalize_hex_identifier(ctx.identity.hash.hex())
            if norm_dest == local_id:
                return True
        try:
            resolved = self.get_lxmf_destination_hash_for_identity_hash(norm_dest)
            if resolved and normalize_hex_identifier(resolved) == local_lxmf:
                return True
        except Exception:
            pass
        return False

    def db_upsert_lxmf_message(
        self,
        lxmf_message: LXMF.LXMessage,
        is_spam: bool = False,
        attachments_stripped: bool = False,
        context=None,
        path_finding_measure: str | None = None,
        path_row_hash_hex: str | None = None,
        state_override: str | None = None,
        method_override: str | None = None,
    ):
        ctx = context or self.current_context
        if not ctx:
            return

        # convert lxmf message to dict
        lxmf_message_dict = convert_lxmf_message_to_dict(
            lxmf_message,
            reticulum=self.reticulum,
            message_router=ctx.message_router,
        )
        if state_override is not None:
            lxmf_message_dict["state"] = state_override
        if method_override is not None:
            lxmf_message_dict["method"] = method_override
        lxmf_message_dict["is_spam"] = 1 if is_spam else 0
        lxmf_message_dict["attachments_stripped"] = 1 if attachments_stripped else 0
        if path_finding_measure is not None:
            lxmf_message_dict["path_finding_measure"] = path_finding_measure
        if path_row_hash_hex is not None:
            lxmf_message_dict["path_row_hash_hex"] = path_row_hash_hex

        # calculate peer hash. Direction decides the peer rather than comparing
        # source to the main identity: outbound copies sent via forwarding
        # aliases have a different source hash but are still our messages, so
        # the peer is the destination, not the alias.
        if lxmf_message_dict.get("is_incoming"):
            lxmf_message_dict["peer_hash"] = lxmf_message_dict["source_hash"]
        else:
            lxmf_message_dict["peer_hash"] = lxmf_message_dict["destination_hash"]

        try:
            ctx.database.messages.upsert_lxmf_message(lxmf_message_dict)
        except Exception:
            message_hash = getattr(lxmf_message, "hash", None)
            hash_label = message_hash.hex() if message_hash is not None else "unknown"
            logger.exception(
                "Failed to persist inbound LXMF message %s from %s",
                hash_label,
                lxmf_message_dict.get("source_hash", "unknown"),
            )
            raise

    def process_incoming_telemetry(
        self,
        source_hash,
        telemetry_data,
        lxmf_message,
        timestamp_override=None,
        context=None,
    ):
        ctx = context or self.current_context
        if not ctx:
            return

        try:
            unpacked = Telemeter.from_packed(telemetry_data)
            if unpacked:
                timestamp = timestamp_override or (
                    unpacked["time"]["utc"] if "time" in unpacked else int(time.time())
                )

                # physical link info
                physical_link = {
                    "rssi": self.reticulum.get_packet_rssi(lxmf_message.hash)
                    if hasattr(self, "reticulum") and self.reticulum
                    else None,
                    "snr": self.reticulum.get_packet_snr(lxmf_message.hash)
                    if hasattr(self, "reticulum") and self.reticulum
                    else None,
                    "q": self.reticulum.get_packet_q(lxmf_message.hash)
                    if hasattr(self, "reticulum") and self.reticulum
                    else None,
                }

                ctx.database.telemetry.upsert_telemetry(
                    destination_hash=source_hash,
                    timestamp=timestamp,
                    data=telemetry_data,
                    received_from=ctx.local_lxmf_destination.hexhash,
                    physical_link=physical_link,
                )

                # broadcast telemetry update via websocket
                AsyncUtils.run_async(
                    self.websocket_broadcast(
                        json.dumps(
                            {
                                "type": "lxmf.telemetry",
                                "destination_hash": source_hash,
                                "timestamp": timestamp,
                                "telemetry": unpacked,
                                "physical_link": physical_link,
                                "is_tracking": ctx.database.telemetry.is_tracking(
                                    source_hash,
                                ),
                            },
                        ),
                    ),
                )
        except Exception as e:
            print(f"Error processing incoming telemetry: {e}")

    # updates lxmf message in database and broadcasts to websocket until it's delivered, or it fails
    async def handle_lxmf_message_progress(self, lxmf_message, context=None):
        ctx = context or self.current_context
        if not ctx:
            return

        should_update_message = True
        while should_update_message:
            progress_pct = round(lxmf_message.progress * 100, 2)
            ctx.database.messages.update_lxmf_message_state(
                message_hash=lxmf_message.hash.hex(),
                state=convert_lxmf_state_to_string(lxmf_message),
                progress=progress_pct,
                delivery_attempts=lxmf_message.delivery_attempts,
                next_delivery_attempt_at=getattr(
                    lxmf_message,
                    "next_delivery_attempt",
                    None,
                ),
                method=convert_lxmf_method_to_string(lxmf_message),
            )
            self._maybe_store_path_at_send_for_lxmf(ctx, lxmf_message)

            msg_dict = convert_lxmf_message_to_dict(
                lxmf_message,
                include_attachments=False,
                reticulum=self.reticulum,
                message_router=ctx.message_router,
            )
            self._merge_stored_path_fields_from_db(
                ctx,
                lxmf_message.hash.hex(),
                msg_dict,
            )

            await self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "lxmf_message_state_updated",
                        "lxmf_message": msg_dict,
                    },
                ),
            )

            # check if we should stop updating
            if is_lxmf_outbound_progress_terminal(lxmf_message):
                should_update_message = False
            else:
                await asyncio.sleep(1)

    def _note_announce_timestamp(self) -> None:
        now = time.time()
        self.announce_timestamps.append(now)
        self.announce_timestamps = prune_announce_timestamps(
            self.announce_timestamps,
            now=now,
        )

    def on_telephone_announce_received(
        self,
        aspect,
        destination_hash,
        announced_identity,
        app_data,
        announce_packet_hash,
        context=None,
    ):
        """Handle lxst.telephony announces (synchronous Reticulum callback)."""
        ctx = context or self.current_context
        if not ctx or not ctx.running or not ctx.announce_manager or not ctx.database:
            return
        identity_hash = announced_identity.hash.hex()
        verdict = ctx.announce_manager.classify_announce(
            destination_hash,
            identity_hash,
        )
        if verdict == "blocked":
            logger.debug(
                "Dropping telephone announce from blocked source: %s",
                identity_hash,
            )
            if hasattr(self, "reticulum") and self.reticulum:
                self.reticulum.drop_path(destination_hash)
            return

        if not ctx.announce_manager.is_storing_announce_for_aspect(aspect):
            return

        logger.debug(
            "Received an announce from %s for [lxst.telephony]",
            RNS.prettyhexrep(destination_hash),
        )

        # track announce timestamp
        self._note_announce_timestamp()

        if verdict == "background":
            ctx.announce_manager.upsert_announce(
                self.reticulum,
                announced_identity,
                destination_hash,
                aspect,
                app_data,
                announce_packet_hash,
                defer=True,
            )
            self._broadcast_announce_event(
                self.build_pending_announce_dict(
                    aspect,
                    destination_hash,
                    announced_identity,
                    app_data,
                    announce_packet_hash,
                ),
            )
            return

        # upsert announce to database
        ctx.announce_manager.upsert_announce(
            self.reticulum,
            announced_identity,
            destination_hash,
            aspect,
            app_data,
            announce_packet_hash,
        )

        # find announce from database
        announce = ctx.database.announces.get_announce_by_hash(destination_hash.hex())
        if not announce:
            return

        # send database announce to all websocket clients
        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "announce",
                        "announce": self.convert_db_announce_to_dict(announce),
                    },
                ),
            ),
        )

    def on_lxmf_announce_received(
        self,
        aspect,
        destination_hash,
        announced_identity,
        app_data,
        announce_packet_hash,
        context=None,
    ):
        """Handle lxmf.delivery announces (synchronous Reticulum callback)."""
        from meshchatx.src.backend.lifecycle.lxmf_announce import (
            on_lxmf_announce_received,
        )

        return on_lxmf_announce_received(
            self,
            aspect,
            destination_hash,
            announced_identity,
            app_data,
            announce_packet_hash,
            context,
        )

    def on_lxmf_propagation_announce_received(
        self,
        aspect,
        destination_hash,
        announced_identity,
        app_data,
        announce_packet_hash,
        context=None,
    ):
        """Handle lxmf.propagation announces (synchronous Reticulum callback)."""
        ctx = context or self.current_context
        if not ctx or not ctx.running or not ctx.announce_manager or not ctx.database:
            return

        verdict = ctx.announce_manager.classify_announce(
            destination_hash,
            getattr(announced_identity, "hash", None),
        )
        if verdict == "blocked":
            if hasattr(self, "reticulum") and self.reticulum:
                self.reticulum.drop_path(destination_hash)
            return

        if not ctx.announce_manager.is_storing_announce_for_aspect(aspect):
            return

        logger.debug(
            "Received an announce from %s for [lxmf.propagation]",
            RNS.prettyhexrep(destination_hash),
        )

        # track announce timestamp
        self._note_announce_timestamp()

        if verdict == "background":
            ctx.announce_manager.upsert_announce(
                self.reticulum,
                announced_identity,
                destination_hash,
                aspect,
                app_data,
                announce_packet_hash,
                defer=True,
            )
            self._broadcast_announce_event(
                self.build_pending_announce_dict(
                    aspect,
                    destination_hash,
                    announced_identity,
                    app_data,
                    announce_packet_hash,
                ),
            )
            return

        # upsert announce to database
        ctx.announce_manager.upsert_announce(
            self.reticulum,
            announced_identity,
            destination_hash,
            aspect,
            app_data,
            announce_packet_hash,
        )

        # find announce from database
        announce = ctx.database.announces.get_announce_by_hash(destination_hash.hex())
        if not announce:
            return

        # send database announce to all websocket clients
        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "announce",
                        "announce": self.convert_db_announce_to_dict(announce),
                    },
                ),
            ),
        )

    # resends all messages that previously failed to send to the provided destination hash
    async def resend_failed_messages_for_destination(
        self,
        destination_hash: str,
        context=None,
    ):
        from meshchatx.src.backend.lifecycle.lxmf_resend import (
            resend_failed_messages_for_destination as _resend_failed,
        )

        return await _resend_failed(self, destination_hash, context)

    def on_map_data_announce_received(
        self,
        aspect,
        destination_hash,
        announced_identity,
        app_data,
        announce_packet_hash,
        context=None,
    ):
        """Handle map-data-v1 announces (synchronous Reticulum callback)."""
        ctx = context or self.current_context
        if not ctx or not ctx.running or not ctx.announce_manager or not ctx.database:
            return
        if not announced_identity or not announced_identity.hash:
            return
        identity_hash = announced_identity.hash.hex()
        verdict = ctx.announce_manager.classify_announce(
            destination_hash,
            identity_hash,
        )
        if verdict == "blocked":
            if hasattr(self, "reticulum") and self.reticulum:
                self.reticulum.drop_path(destination_hash)
            return
        if not ctx.announce_manager.is_storing_announce_for_aspect(aspect):
            return
        logger.debug(
            "Received an announce from %s for [map-data-v1]",
            RNS.prettyhexrep(destination_hash),
        )
        self._note_announce_timestamp()
        if verdict == "background":
            ctx.announce_manager.upsert_announce(
                self.reticulum,
                announced_identity,
                destination_hash,
                aspect,
                app_data,
                announce_packet_hash,
                defer=True,
            )
            self._broadcast_announce_event(
                self.build_pending_announce_dict(
                    aspect,
                    destination_hash,
                    announced_identity,
                    app_data,
                    announce_packet_hash,
                ),
            )
            return
        ctx.announce_manager.upsert_announce(
            self.reticulum,
            announced_identity,
            destination_hash,
            aspect,
            app_data,
            announce_packet_hash,
        )
        announce = ctx.database.announces.get_announce_by_hash(destination_hash.hex())
        if not announce:
            return
        AsyncUtils.run_async(
            self.websocket_broadcast(
                json.dumps(
                    {
                        "type": "announce",
                        "announce": self.convert_db_announce_to_dict(announce),
                    },
                ),
            ),
        )

    # gets the custom display name a user has set for the provided destination hash
    def get_custom_destination_display_name(self, destination_hash: str):
        db_destination_display_name = self.database.announces.get_custom_display_name(
            destination_hash,
        )
        if db_destination_display_name is not None:
            return db_destination_display_name

        return None

    # get name to show for an lxmf conversation (from most recent announce app data)
    def get_lxmf_conversation_name(
        self,
        destination_hash,
        default_name: str | None = "Anonymous Peer",
    ):
        # Optimized to fetch only the needed announce
        lxmf_announce = self.database.announces.get_announce_by_hash(destination_hash)

        # if app data is available in database, it should be base64 encoded text that was announced
        # we will return the parsed lxmf display name as the conversation name
        if lxmf_announce is not None and lxmf_announce["app_data"] is not None:
            return parse_lxmf_display_name(
                app_data_base64=lxmf_announce["app_data"],
            )

        # announce did not have app data, so provide a fallback name
        return default_name

    # returns true if the conversation has messages newer than the last read at timestamp
    def is_lxmf_conversation_unread(self, destination_hash):
        return self.database.messages.is_conversation_unread(destination_hash)

    # returns number of messages that failed to send in a conversation
    def lxmf_conversation_failed_messages_count(self, destination_hash: str):
        return self.database.messages.get_failed_messages_count(destination_hash)

    # find an interface by name
    @staticmethod
    def find_interface_by_name(name: str):
        for interface in RNS.Transport.interfaces:
            interface_name = str(interface)
            if name == interface_name:
                return interface

        return None
