"""Extracted mixin for ReticulumMeshChat::parse.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

import RNS

class ParseMixin:
    @staticmethod
    def _parse_rns_config_bool(value, default=False):
        """Parse Reticulum config Yes/No / bool-ish values."""
        if value is None:
            return bool(default)
        if isinstance(value, bool):
            return value
        if isinstance(value, (int, float)):
            return value != 0
        text = str(value).strip().lower()
        if text in ("yes", "true", "1", "on"):
            return True
        if text in ("no", "false", "0", "off", ""):
            return False
        return bool(default)

    @staticmethod
    def _format_rns_config_bool(value):
        return "Yes" if bool(value) else "No"

    @staticmethod
    def _parse_rns_hash_list(value):
        """Parse a RNS config identity-hash list into lowercase hex strings."""
        items = []
        if value is None:
            return items
        if isinstance(value, (list, tuple)):
            raw_items = value
        else:
            raw_items = str(value).replace(",", " ").split()
        try:
            expected = int(RNS.Reticulum.TRUNCATED_HASHLENGTH) // 8 * 2
        except Exception:
            expected = 32
        if expected <= 0:
            expected = 32
        for item in raw_items:
            text = str(item).strip().lower()
            if not text:
                continue
            if len(text) != expected:
                raise ValueError(
                    f"Identity hash {text} must be {expected} hexadecimal characters",
                )
            try:
                bytes.fromhex(text)
            except ValueError as exc:
                raise ValueError(f"Invalid identity hash: {text}") from exc
            if text not in items:
                items.append(text)
        return items

    def _safe_remote_management_allowed(self, value):
        try:
            return self._parse_rns_hash_list(value)
        except ValueError:
            return []
