"""Extracted mixin for ReticulumMeshChat::peer.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

from meshchatx.src.backend.meshchat_utils import (
    cancel_inbound_deliveries,
    convert_db_favourite_to_dict,
    convert_propagation_node_state_to_string,
    hex_identifier_to_bytes,
    interval_action_due,
    message_fields_have_attachments,
    normalize_hex_identifier,
    normalize_identity_storage_hash,
    parse_bool_query_param,
    parse_lxmf_display_name,
    parse_lxmf_propagation_node_app_data,
    parse_lxmf_stamp_cost,
    parse_nomadnetwork_node_display_name,
    propagation_sync_idle_like,
    propagation_sync_is_terminal,
)

class PeerMixin:
    def _peer_hashes_for_banishment(self, destination_hash: str, context=None) -> list:
        """Identity and destination hashes that must be blocked or unblocked together."""
        destination_hash = normalize_hex_identifier(destination_hash)
        related = self._related_hashes_for_contact_lookup(
            destination_hash,
            context=context,
        )
        hashes = []
        seen = set()
        for peer_hash in (destination_hash, *related):
            if not peer_hash or peer_hash in seen:
                continue
            if len(peer_hash) != 32:
                continue
            seen.add(peer_hash)
            hashes.append(peer_hash)
        return hashes
