"""Extracted mixin for ReticulumMeshChat::probe.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""


class ProbeMixin:
    @staticmethod
    def _probe_host_audio_unavailable() -> bool:
        """Return True when LXST cannot open a host capture device."""
        try:
            from LXST.Sources import Backend

            if Backend is None:
                return True
            Backend()
            return False
        except Exception:
            return True
