"""Extracted mixin for ReticulumMeshChat::process.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""


class ProcessMixin:
    async def process_crawler_task(self, task, context=None):
        from meshchatx.src.backend.lifecycle.crawler_task import (
            process_crawler_task as _process_crawler_task,
        )

        return await _process_crawler_task(self, task, context)
