"""Extracted mixin for ReticulumMeshChat::schedule.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

from meshchatx.src.backend.async_utils import AsyncUtils
import threading
from ..meshchat_shared import _install_reticulum_signal_handlers

class ScheduleMixin:
    def _schedule_reticulum_signal_handlers(self) -> None:
        """Install RNS signal handlers on the main asyncio loop when possible."""
        if threading.current_thread() is threading.main_thread():
            _install_reticulum_signal_handlers()
            return
        loop = AsyncUtils.main_loop
        if loop is None or not loop.is_running():
            return
        try:
            loop.call_soon_threadsafe(_install_reticulum_signal_handlers)
        except Exception:
            pass
