"""Extracted mixin for ReticulumMeshChat::try_kw.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

import re
import time

class TryKwMixin:
    def _try_serve_local_page_node(
        self,
        destination_hash,
        page_path,
        request_data=None,
        link_id=None,
        remote_identity=None,
    ):
        """Serve a page from disk when the hash matches a local page node.

        Returns the page content string, or None.
        """
        from meshchatx.src.backend.page_node import _safe_mesh_file_basename

        for node in self.page_node_manager.nodes.values():
            if not node.running or not node.destination:
                continue
            if node.destination.hash == destination_hash:
                page_name = page_path.lstrip("/")
                page_name = page_name.removeprefix("page/")
                try:
                    page_name = _safe_mesh_file_basename(page_name)
                except ValueError:
                    return None
                raw = node.serve_page_content(
                    page_name,
                    data=request_data,
                    link_id=link_id,
                    remote_identity=remote_identity,
                )
                if raw is None:
                    return None
                return raw.decode("utf-8", errors="replace")
        return None

    def _extract_page_file_links(self, page_content: str) -> set[str]:
        """Return file paths referenced by a Nomad page for image grants."""
        if not isinstance(page_content, str):
            return set()
        links = set()
        # Match "hash:/media/..." and "hash:/file/..." image links.
        pattern = re.compile(
            r"(?:[a-f0-9]{32})?:/(?:media|file)/([^\s)`\"'\\]+\.(?:webp|png|jpe?g|bmp|gif|tiff))",
            re.IGNORECASE,
        )
        for m in pattern.finditer(page_content):
            path = m.group(1)
            if not path or ".." in path:
                continue
            links.add(path)
        return links

    def _register_page_file_grant(
        self,
        client,
        destination_hash: bytes,
        page_path: str,
        page_content: str,
        ttl: float = 300,
    ) -> None:
        """Remember the files a client is allowed to fetch from a page."""
        key = id(client)
        now = time.time()
        # Prune expired entries and old clients.
        self._page_file_grants = {
            k: v for k, v in self._page_file_grants.items() if v.get("expires", 0) > now
        }
        grant = self._page_file_grants.setdefault(
            key,
            {"expires": now + ttl, "destinations": {}},
        )
        grant["expires"] = now + ttl
        destinations = grant.setdefault("destinations", {})
        dest_pages = destinations.setdefault(destination_hash.hex(), {})
        norm_path = self._normalize_grant_page_path(destination_hash, page_path)
        dest_pages[norm_path] = self._extract_page_file_links(page_content)

    def _clear_page_file_grants_for_client(self, client) -> None:
        """Drop all page-file grants held by a disconnected client."""
        self._page_file_grants.pop(id(client), None)

    @staticmethod
    def _normalize_grant_page_path(destination_hash: bytes, page_path: str) -> str:
        """Strip the "hash:" prefix the frontend sends inside page_path."""
        prefix = f"{destination_hash.hex()}:"
        if page_path.startswith(prefix):
            return page_path[len(prefix) :]
        return page_path

    def _check_page_file_grant(
        self,
        client,
        destination_hash: bytes,
        page_path: str,
        file_path: str,
    ) -> bool:
        """Check whether a client may fetch a file from a recently loaded page."""
        key = id(client)
        grant = self._page_file_grants.get(key)
        if not grant or grant.get("expires", 0) <= time.time():
            return False
        by_dest = grant.get("destinations", {})
        by_page = by_dest.get(destination_hash.hex(), {}).get(
            self._normalize_grant_page_path(destination_hash, page_path)
        )
        if not by_page:
            return False
        name = file_path.lstrip("/")
        if name.startswith("media/"):
            name = name.removeprefix("media/")
        elif name.startswith("file/"):
            name = name.removeprefix("file/")
        return name in by_page

    def _try_serve_local_page_node_file(
        self,
        destination_hash,
        file_path,
        *,
        client=None,
        page_path=None,
        request_data=None,
    ):
        """Serve a file from disk when the hash matches a local page node.

        Returns (file_name, file_bytes), or None.
        """
        from meshchatx.src.backend.page_node import _safe_mesh_file_basename

        # Image downloads must be tied to a recently loaded page grant.
        if isinstance(request_data, dict) and request_data.get("image_id") is not None:
            if client is None or page_path is None:
                return None
            if not self._check_page_file_grant(
                client, destination_hash, page_path, file_path
            ):
                return None

        for node in self.page_node_manager.nodes.values():
            if not node.running or not node.destination:
                continue
            if node.destination.hash == destination_hash:
                if file_path.startswith("/media/"):
                    return node.serve_media(file_path)
                file_name = file_path.lstrip("/")
                file_name = file_name.removeprefix("file/")
                try:
                    file_name = _safe_mesh_file_basename(file_name)
                except ValueError:
                    return None
                return node.read_hosted_file(file_name)
        return None
