"""Extracted mixin for ReticulumMeshChat shared helpers.

Generated by scripts/refactor/godclass.py. Method bodies are verbatim
slices of the original file; do not edit ordering casually.
"""

from meshchatx.src.backend.rns_startup_recovery import (
    create_reticulum_with_recovery,
    install_rns_panic_containment,
)
from meshchatx.src.env_utils import env_bool, env_str
from meshchatx.src.path_utils import (
    get_file_path,
    is_loopback_bind_host,
    is_path_within_dir,
    resolve_log_dir,
    resolve_meshchat_data_roots,
    safe_path_under_dir,
)
import RNS
import logging
import signal
import sys
import threading

log_dir = resolve_log_dir()

logger = logging.getLogger("meshchatx")

def _parse_rns_loglevel_value(raw: str | None) -> int | None:
    if not raw or not str(raw).strip():
        return None
    raw = str(raw).strip().lower()
    named = {
        "none": RNS.LOG_NONE,
        "critical": RNS.LOG_CRITICAL,
        "error": RNS.LOG_ERROR,
        "warning": RNS.LOG_WARNING,
        "notice": RNS.LOG_NOTICE,
        "verbose": RNS.LOG_VERBOSE,
        "debug": RNS.LOG_DEBUG,
        "extreme": RNS.LOG_EXTREME,
    }
    if raw in named:
        return named[raw]
    try:
        return int(raw)
    except ValueError:
        return None

def _resolve_rns_loglevel(cli_override: str | None) -> int | None:
    if cli_override is not None and str(cli_override).strip():
        return _parse_rns_loglevel_value(cli_override)
    return _parse_rns_loglevel_value(env_str("MESHCHAT_RNS_LOG_LEVEL"))

_rns_bridge_logger = logging.getLogger("meshchatx.rns")

def _rns_log_to_python_logging(logstring: str) -> None:
    """Forward already-formatted RNS log lines into the MeshChatX logger."""
    try:
        _rns_bridge_logger.info("%s", logstring)
    except Exception:
        pass

def _resolve_rns_logdest():
    """Choose RNS log destination.

    When a writable log_dir exists, default to a callback into Python logging
    so RNS output shares SafeRotatingFileHandler and does not flood Docker
    stdout. Set MESHCHAT_RNS_LOG_DEST=stdout to keep the RNS console default.
    """
    raw = (env_str("MESHCHAT_RNS_LOG_DEST") or "").strip().lower()
    if raw in ("stdout", "console", "stderr"):
        return None
    if raw in ("", "logging", "callback", "file") and log_dir:
        return _rns_log_to_python_logging
    return None

def _restore_rns_console_logging_after_reticulum_init(app) -> None:
    """Undo shutdown side effects from RNS.Reticulum.exit_handler.

    That handler sets RNS.loglevel to LOG_NONE and points sys.stdout /
    sys.stderr at os.devnull. Without this, hot reload appears to stop all
    announce traffic logging even though interfaces are up.

    When no CLI or MESHCHAT_RNS_LOG_LEVEL value applies and the level is still
    LOG_NONE after reading config, fall back to LOG_WARNING so notices are
    visible. Explicit none in the environment remains respected.
    """
    try:
        if hasattr(sys, "__stdout__"):
            sys.stdout = sys.__stdout__
        if hasattr(sys, "__stderr__"):
            sys.stderr = sys.__stderr__
    except Exception:
        pass
    resolved = _resolve_rns_loglevel(getattr(app, "_rns_loglevel_cli", None))
    if resolved is None and RNS.loglevel == RNS.LOG_NONE:
        RNS.loglevel = RNS.LOG_WARNING

def _create_reticulum_instance(
    config_dir: str,
    loglevel: int | None = None,
    logdest=None,
):
    """Construct RNS.Reticulum even when called off the main thread.

    Reticulum registers SIGINT/SIGTERM handlers in __init__. Python only allows
    signal.signal on the main thread, so deferred network setup must skip that
    registration when running in a background worker and install handlers later.

    On failure, progressively disables risky interfaces (I2P, unsupported RNode,
    AutoInterface, etc.) and retries so Android/desktop can recover without
    wiping app data or the whole .reticulum tree. RNS.panic is contained
    so it cannot os._exit the MeshChatX process.
    """
    kwargs = {}
    if loglevel is not None:
        kwargs["loglevel"] = loglevel
    resolved_logdest = logdest if logdest is not None else _resolve_rns_logdest()
    if resolved_logdest is not None:
        kwargs["logdest"] = resolved_logdest

    def _construct():
        if threading.current_thread() is threading.main_thread():
            return RNS.Reticulum(config_dir, **kwargs)

        real_signal = signal.signal

        def _signal_allow_non_main(signum, handler):
            try:
                return real_signal(signum, handler)
            except ValueError:
                return signal.getsignal(signum)

        signal.signal = _signal_allow_non_main
        try:
            return RNS.Reticulum(config_dir, **kwargs)
        finally:
            signal.signal = real_signal

    return create_reticulum_with_recovery(
        config_dir,
        construct=_construct,
    )

def _install_reticulum_signal_handlers() -> bool:
    """Install MeshChat SIGINT/SIGTERM handlers (flush DB, then GracefulExit).

    Must run on the main thread. Replaces raw RNS handlers that used to call
    RNS.exit / os._exit and skip SQLite WAL checkpoint.
    """
    from meshchatx.src.backend.lifecycle.signal_shutdown import (
        install_meshchat_signal_handlers,
    )

    return install_meshchat_signal_handlers()
